magento/devdocs#7701: In-Store Pickup GraphQl intersection products assignments filter.
magento/devdocs pull request #7702
Opened 2020-08-08 15:35 UTC by swnsma

## Purpose of this pull request

See https://github.com/magento/devdocs/issues/7701

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.4/graphql/queries/pickup-locations.html

## Links to Magento source code
magento/inventory#3161

2020-08-08 15:37 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-08-16 20:53 UTC, keharper commented
@swnsma This appears to be a 2.4.1 addition. If so, I'll need you to either rebase this PR to 2.4.1-develop or open a new PR against that branch. If it's questionable whether this code will make it into the 2.4.1, you might need to wait until we create a 2.4.2-develop branch.

2020-09-03 01:51 UTC, keharper commented
This didn't make it into 2.4.1. Retagged to 2.4.2.

2020-09-30 08:00 UTC, swnsma commented
@keharper 
Related PR to source code has been merged.

2020-10-18 17:58 UTC, swnsma commented
Hi @keharper !
Any future for this PR?

2020-10-20 14:08 UTC, keharper commented
@swnsma I don't understand the `ProductInfoInput` object. Is it being used to search for locations that have all the listed SKUs or that do not have the listed SKUs?

2020-10-20 16:36 UTC, swnsma commented
Hi @keharper,

It will leave only locations which have relations with listed SKU.
If at least one SKU is missing in location, location will not be added to the result list.

2020-10-23 20:16 UTC, keharper requested changes
@swnsma  I think the note on lines 17-18 needs to be deleted.  I suspect that `productsInfo` or `sku` should be added to the bulleted list at line 14. If yes, then use a variant of my suggestion for line 176.

2020-10-23 20:16 UTC, keharper commented on src/guides/v2.4/graphql/queries/pickup-locations.md
> +`productsInfo` |[[ProductInfoInput]](#ProductInfoInput)| Information about products which should be delivered. The information is used to filter Pickup Locations which do not have relations with ment
```suggestion
`productsInfo` |[[ProductInfoInput]](#ProductInfoInput)| Contains an array of SKUs to filter on.
```

2020-11-03 02:07 UTC, keharper commented
@swnsma can you take a look at this PR again?

2020-11-10 14:51 UTC, keharper approved these changes

2020-11-10 14:52 UTC, keharper commented
running tests

2020-11-10 15:09 UTC, merged