Mae mcloud 6033 bypass fastly cleanup
magento/devdocs pull request #7795
Opened 2020-09-01 15:13 UTC by meker12

## Purpose of this pull request

Changes the title of [Custom VCL to bypass Fastly](https://devdocs.magento.com/cloud/cdn/fastly-vcl-bypass-to-origin.html) to "Custom VCL to bypass Fastly cache" to clarify purpose of the VCL.

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/cdn/fastly-vcl-bypass-to-origin.html

2020-09-01 16:19 UTC, BarnyShergold requested changes
Please also correct typo in PR title (Mae should read Magento)

2020-09-01 16:19 UTC, BarnyShergold commented on src/cloud/cdn/fastly-vcl-bypass-to-origin.md
> +You can create a custom VCL snippet to bypass Fastly caching and submit requests directly to the origin server, for example to determine whether site issues are caused by caching, or to troubleshoot
I would suggest "Fastly caching" as this eliminates the ambiguity between Fastly cache and Magento cache

2020-09-02 17:21 UTC, meker12 commented
> Please also correct typo in PR title (Mae should read Magento)

I can provide a better title, but "MAE" are my initials ;-).

2020-09-02 17:22 UTC, meker12 commented on src/cloud/cdn/fastly-vcl-bypass-to-origin.md
> +title: Custom VCL to bypass Fastly cache
```suggestion
title: Custom VCL to bypass Fastly caching
```

2020-09-02 17:22 UTC, meker12 commented on src/cloud/cdn/fastly-vcl-bypass-to-origin.md
> +You can create a custom VCL snippet to bypass Fastly caching and submit requests directly to the origin server, for example to determine whether site issues are caused by caching, or to troubleshoot
```suggestion
You can create a custom VCL snippet to bypass Fastly caching and submit requests directly to the origin server, for example to determine whether site issues are caused by caching, or to troubleshoot headers. You can configure the snippet to bypass Fastly caching for requests from a specific IP address or URL.
```

2020-09-02 18:53 UTC, BarnyShergold approved these changes
Apologies about the title - thought it was a typo of Magento :)

2020-09-03 13:36 UTC, jeff-matthews approved these changes

2020-09-03 16:03 UTC, meker12 commented
running tests

2020-09-03 16:03 UTC, meker12 commented
running tests

2020-09-03 16:18 UTC, meker12 commented
running tests

2020-09-03 16:40 UTC, merged