Update using-fonts.md
magento/devdocs pull request #7800
Opened 2020-09-02 06:58 UTC by abrarpathan19

## Purpose of this pull request

This pull request (PR) will correct the fonts format eot not oet.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.html
## Links to Magento source code

-  ...

2020-09-02 06:59 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-02 08:43 UTC, BarnyShergold requested changes

2020-09-02 08:43 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
> -   `@font-format` is optional. If you need to specify a format, enclose it in single quotes. For example, `@font-format: 'ttf'` for TrueType Fonts. The available types are: "woff", "woff2", "ttf", "o
Should this not also be corrected in - src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md

2020-09-03 08:53 UTC, BarnyShergold approved these changes

2020-09-03 08:54 UTC, BarnyShergold commented
running tests

2020-09-03 08:57 UTC, BarnyShergold commented
@magento run all tests

2020-09-03 13:33 UTC, jeff-matthews approved these changes

2020-09-04 13:08 UTC, dobooth commented
running tests

2020-09-04 13:44 UTC, merged