MCLOUD-6430: Xdebug not working on Magento Cloud Docker 1.1
magento/devdocs pull request #7810
Opened 2020-09-02 20:46 UTC by oshmyheliuk

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2020-09-02 20:47 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-02 21:42 UTC, BarnyShergold requested changes

2020-09-02 21:42 UTC, BarnyShergold commented on src/cloud/docker/docker-development-debug.md
> +   For Linux system also need to be added option `--set-docker-host` for automatically adding `host.docker.internal` into `/etc/hosts` of `fpm_xdebug` container.
Better English syntax
```suggestion
   For Linux systems, the option `--set-docker-host` also needs to be added for automatically adding `host.docker.internal` into the `/etc/hosts` for the `fpm_xdebug` container.
```

2020-09-02 22:02 UTC, oshmyheliuk commented on src/cloud/docker/docker-development-debug.md
> +   For Linux system also need to be added option `--set-docker-host` for automatically adding `host.docker.internal` into `/etc/hosts` of `fpm_xdebug` container.
Thank you!

2020-09-02 22:04 UTC, BarnyShergold approved these changes
No problems!

2020-09-03 13:39 UTC, jeff-matthews requested changes

2020-09-03 13:39 UTC, jeff-matthews commented on src/cloud/docker/docker-development-debug.md
> +   For Linux systems, the option `--set-docker-host` also needs to be added for automatically adding `host.docker.internal` into the `/etc/hosts` for the `fpm_xdebug` container.
```suggestion
   For Linux systems, you must use the `--set-docker-host` option to add the `host.docker.internal` entry to the `/etc/hosts` file for the `fpm_xdebug` container.
```

2020-09-03 13:41 UTC, BarnyShergold commented on src/cloud/docker/docker-development-debug.md
> +   For Linux systems, the option `--set-docker-host` also needs to be added for automatically adding `host.docker.internal` into the `/etc/hosts` for the `fpm_xdebug` container.
So it's a compulsory option?

2020-09-03 13:43 UTC, jeff-matthews commented on src/cloud/docker/docker-development-debug.md
> +   For Linux systems, the option `--set-docker-host` also needs to be added for automatically adding `host.docker.internal` into the `/etc/hosts` for the `fpm_xdebug` container.
The original text implies that it is.

2020-09-03 15:59 UTC, jeff-matthews approved these changes

2020-09-03 17:11 UTC, meker12 approved these changes

2020-09-03 17:19 UTC, merged