Removed "A branch name of Sprint2 and sprint2 are just fine." #7825
magento/devdocs pull request #7826
Opened 2020-09-06 09:21 UTC by medigeek

Removed "A branch name of Sprint2 and sprint2 are just fine." #7825

## Purpose of this pull request

proposed solution to #7825

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/reference/git-integration.html

## Links to Magento source code

-  https://github.com/magento/devdocs/blob/master/src/cloud/reference/git-integration.md

2020-09-06 09:23 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-06 13:53 UTC, rogyar approved these changes
Hi @medigeek. Thank you for your collaboration.

Another option might be to replace "and" with "or" and have the following sentence as a result

> A branch name of `Sprint2` or `sprint2` are just fine

But I agree that this sentence with example is more confusing than useful

2020-09-08 15:07 UTC, meker12 requested changes

2020-09-08 15:07 UTC, meker12 commented on src/cloud/reference/git-integration.md
> +*  Branch names must be case-insensitively unique. In other words, the names must be entirely unique regardless of the case you use. For example, if you have a branch named `Sprint`, you cannot creat
```suggestion
*  Branch names are not case-sensitive. 
Each branch name must be unique regardless of the case used for each letter. For example, if you have a branch named `Sprint`, you cannot create another branch named `sprint`.
```

2020-09-08 15:59 UTC, meker12 approved these changes

2020-09-08 17:49 UTC, meker12 commented
running tests

2020-09-08 18:57 UTC, merged