Db b2b table
magento/devdocs pull request #7849
Opened 2020-09-09 17:19 UTC by dobooth

## Purpose of this pull request

This pull request (PR) adds B2B to the Compatibility table.

## Affected DevDocs pages

- https://devdocs.magento.com/release/availability.html

2020-09-09 17:39 UTC, jeff-matthews requested changes
We need to add new versions for all other modules. There's an internal wiki page that lists what those module versions are.

2020-09-11 18:48 UTC, dobooth commented
Going to leave this as draft until just before release. Some extensions are marked as beta and I suspect will change at release.

2020-09-25 22:44 UTC, dshevtsov commented
The following tests will be run for internal CI/CD testing, without an intention to merge.

2020-09-25 22:45 UTC, dshevtsov commented
running tests

2020-09-28 18:59 UTC, jeff-matthews requested changes
You're still missing Q4 entries (2.3.6/2.4.1) for Inventory and Product Recommendations.

2020-09-28 19:02 UTC, hickskenh approved these changes
only one change.  the rest looks to be formatted and outputs correctly.

2020-09-28 19:24 UTC, dobooth commented
I hosed myself when I merged master instead of 2.4.1-develop. I forgot to add the work back in.

2020-09-28 19:38 UTC, jeff-matthews requested changes

2020-09-28 19:38 UTC, jeff-matthews commented on src/_data/mde.yml
> +          2.4.0: compatible
Shouldn't 1.2.0 + 2.4.0 be "supported"?

2020-09-29 13:21 UTC, dobooth commented on src/_data/mde.yml
> +          2.4.0: compatible
Yes.

2020-09-29 13:42 UTC, jeff-matthews approved these changes

2020-09-30 11:08 UTC, dobooth commented
running tests

2020-09-30 12:23 UTC, merged