Cloud platform tls integration branch
magento/devdocs pull request #7885
Opened 2020-09-16 16:17 UTC by meker12

## Purpose of this pull request

- Updated Site launch and launch checklist for Platform TLS and DNS configuration updates for production
- Updated Fastly set up topic with instructions for SSL/TLS certificate provisioning and DNS configuration updates
- Added links to Fastly docs for basic authentication and edge module sections in Customi
- Fixed format and links in Fastly set up topic
- Updated Fastly overview topic
   - Updated security section to add bullet points for origin cloaking and SSL/TLS certificates
   -  Removed duplicated content covered in custom cache configuration sections
   - Changed inline links to reference links in "link definitions" section
   remove duplicated content covered in custom cache configuration sections
- New _Custom cache configuration_ topic
   - Moved custom cache configuration sections from Fastly set up topic
   - Added instructions and screen cap for Managing domains on Starter
projects
   - Add instructions and screen cap for Enabling maintenance mode
during development

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/cdn/cloud-fastly.html
- https://devdocs.magento.com/cloud/cdn/configure-fastly-customize-cache.html
- https://devdocs.magento.com/cloud/cdn/configure-fastly.html
- https://devdocs.magento.com/cloud/live/live.html
- https://devdocs.magento.com/cloud/live/site-launch-checklist.html
- https://devdocs.magento.com/cloud/live/stage-prod-migrate-prereq.html
- https://devdocs.magento.com/cloud/cdn/cloud-vcl-custom-snippets.html
- https://devdocs.magento.com/cloud/cdn/fastly-image-optimization.html

whatsnew

- Moved documentation for Fastly cache customization options to a new Custom cache configuration topic. Added instructions for managing domains and enabling maintenance mode using the Fastly CDN module for Magento 2. See Custom cache configuration.

- Updated Fastly set up and Site launch documentation in the Cloud Guide to reflect change from shared certificates for Fastly for each project to have a unique Domain-Validated SSL/TLS certificate issued by Let's Encrypt. Also, updated DNS configuration instructions for adding domains, CNAME, and A records.

2020-09-16 16:34 UTC, hguthrie commented
It's the big one! I'm on it...

2020-09-16 21:31 UTC, hguthrie requested changes
I have to request a change for one broken link.
I did see a couple of other things that might be confusing, but they are not show-stoppers.
Otherwise, good to go!

2020-09-16 21:31 UTC, hguthrie commented on src/cloud/cdn/configure-fastly-customize-cache.md
> +Fastly gets the Magento Admin path for generating the VCL file from the `app/etc/env.php` configuration file.
"gets" is a little vague.

2020-09-16 21:31 UTC, hguthrie commented on src/cloud/cdn/configure-fastly-customize-cache.md
> +1. All purge options display. Select "Yes" per purge option to enable automatic purging. Select "No" to disable automatic purging, allowing you to manually purge caches through the Cache Management p
"per purge option" I wonder if the use of **per** will be confusing to some readers. Maybe use "for each" or something similar?

2020-09-16 21:31 UTC, hguthrie commented on src/cloud/cdn/trouble-fastly.md
> +({{site.baseurl}}/cloud/cdn/configure-fastly-customize-cache.html#extend-fastly-timeout).
Line break in the middle of a URL. Note is not showing properly.

2020-09-16 23:12 UTC, meker12 commented on src/cloud/cdn/configure-fastly-customize-cache.md
> +Fastly gets the Magento Admin path for generating the VCL file from the `app/etc/env.php` configuration file.
```suggestion
Fastly retrieves the Magento Admin path for generating the VCL file from the `app/etc/env.php` configuration file.
```

2020-09-16 23:13 UTC, meker12 commented on src/cloud/cdn/trouble-fastly.md
> +({{site.baseurl}}/cloud/cdn/configure-fastly-customize-cache.html#extend-fastly-timeout).
```suggestion
If the timeout occurs when running bulk operations, you can [extend the Fastly timeout for the Magento Admin UI]({{site.baseurl}}/cloud/cdn/configure-fastly-customize-cache.html#extend-fastly-timeout).
```

2020-09-17 13:53 UTC, hguthrie approved these changes

2020-09-17 14:08 UTC, meker12 commented
running tests

2020-09-17 14:43 UTC, merged