Added info about Fastly Admin UI Not Being Available (Cloud)
magento/devdocs pull request #7899
Opened 2020-09-18 00:17 UTC by BarnyShergold

## Purpose of this pull request

This pull request (PR) fulfils #7892 

## Affected DevDocs pages

https://devdocs.magento.com/cloud/cdn/configure-fastly.html

2020-09-18 00:19 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-21 17:09 UTC, meker12 commented on src/cloud/cdn/configure-fastly.md
> +With Magento Cloud, Fastly Admin UI access is not provided. Any issue that cannot be solved through the Fastly Admin in Magento should be referred to [Magento Support](https://support.magento.com/hc/
```suggestion
With {{ site.data.var.ece }}Magento Cloud, you cannot access the Fastly Admin UI directly. You must use the Magento Admin UI to review and update the Fastly configuration for your environments.  If you cannot resolve an issue using the Fastly capabilities in the Magento Admin UI, submit a [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket) ticket.
```

2020-09-21 17:44 UTC, meker12 requested changes
Added suggested clarifications.

2020-09-21 23:38 UTC, meker12 approved these changes

2020-09-21 23:39 UTC, meker12 commented
running tests

2020-09-22 00:12 UTC, merged