MCLOUD-6896: Add possibility to pass ECE-Tools environment variables
magento/devdocs pull request #7907
Opened 2020-09-21 18:39 UTC by oshmyheliuk

## Purpose of this pull request

This pull request (PR)  will add info on how to configure environment variables for docker containers.

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/docker/docker-config.html

2020-09-21 18:41 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-21 20:32 UTC, meker12 requested changes

2020-09-21 20:32 UTC, meker12 commented on src/cloud/docker/docker-config.md
> +You can launch a Docker with predefined environment variable by passing them in `--env-vars` option.
```suggestion
You can launch a Cloud Docker environment with predefined environment variables by adding the `--env-vars` option to the `ece-docker build:compose` command.
```

2020-09-21 20:32 UTC, meker12 commented on src/cloud/docker/docker-config.md
> +Use the next php script to generate value for `--env-vars` option:
```suggestion
You must escape special characters when specifying the value for the `--env-vars` option. Use the following PHP script to generate the escaped value for the configuration. Update the values with the values required for your Cloud Docker environment configuration.
```

2020-09-22 02:13 UTC, meker12 commented on src/cloud/docker/docker-config.md
> +```php
```suggestion

```php
```

2020-09-22 02:30 UTC, meker12 approved these changes

2020-09-22 14:24 UTC, meker12 commented
running tests

2020-09-22 15:12 UTC, merged