Added Field type reference
magento/devdocs pull request #7910
Opened 2020-09-22 16:57 UTC by DavidLambauer

Added all the common field types that can be used in the system.xml

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2020-09-22 16:59 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-22 21:56 UTC, BarnyShergold requested changes
You need to update the description to the proper format. Please put the description in the "Pull request purpose", add full URL links to affected pages and remove the "Links to Magento Source Code"

As 2.3 documentation is identical but not symlinked, you will need to apply the corrected changes to the 2.3 file as well.

You also have some Lint errors (trailing spaces on line 279), these will need to be corrected. It is advised to run -
mdl --style=_checks/styles/style-rules-prod --ignore-front-matter --git-recurse -- .
before commiting.

2020-09-22 21:56 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +Each field has the default type of ´text´ to display it's frontend input type. The following input fields types can be found and used in the core at the time of this writing:
```suggestion
Each field has the default type of ´text´ to display its frontend input type. The following input field types can be found and used in the core at this time :
```

2020-09-22 21:56 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´select´      | A common html select. Only one item can be selected.                                                              |
```suggestion
| ´select´      | A common HTML select. Only one item can be selected.                                                              |
```

2020-09-22 21:56 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´multiselect´ | A common html select. Multiple items can be selected at once.                                                     |
```suggestion
| ´multiselect´ | A common HTML select. Multiple items can be selected at once.                                                     |
```

2020-09-22 21:56 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´textarea´    | A common html textarea.                                                                                           |
```suggestion
| ´textarea´    | A common HTML textarea.                                                                                           |
```

2020-09-22 21:56 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´button´      | A common html button. It is necessary to declare a custom ´frontend_model´ in order to use the button field type. |
```suggestion
| ´button´      | A common HTML button. It is necessary to declare a custom ´frontend_model´ in order to use the button field type. | 
```

2020-09-22 21:56 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´image´       | Possible Image upload. The nodes ´backend_model´, ´upload_dir´ and ´base_url´ needs to be defined as well.        |
```suggestion
| ´image´       | Possible image upload. The nodes ´backend_model´, ´upload_dir´ and ´base_url´ need to be defined as well.        |
```

2020-09-23 13:30 UTC, DavidLambauer commented
Well, I made this whole PR via ´edit this site on github´ link. I won't be able to finish the changes you asked for in near time. Maybe you can fix it on your own?

2020-09-23 13:35 UTC, BarnyShergold commented
Okay - I can update the description - but for the proposed changes, you just need to click the "Commit Suggestion" on this PR and Github will update. The rest I can do on Git if you have no way to correct.

2020-09-28 23:07 UTC, BarnyShergold requested changes

2020-09-28 23:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´select´      | A common HTML select. Only one item can be selected.                                                              |
It should also be mentioned that this covers a YES/NO and it requires a source_model to manage the items on the list

EG - Normal dropdown, may need custom `source_model` - also used for Yes/No. See `Magento\Search\Model\Adminhtml\System\Config\Source\Engine` for an example

2020-09-28 23:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´multiselect´ | A common HTML select. Multiple items can be selected at once.                                                     |
Also requires a source_model

2020-09-28 23:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´obscure´     | Commonly used for passwords. Shows asterisks as values.                                                           |
Also mention that the value is encrypted and forcibly changing type using "Inspect Element" in browser will not show the value

2020-09-28 23:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´time´        | A string of the current time. Cannot be configured.                                                               |
Incorrect definition : Allows a time to be set. This is done by using 3 dropdowns - Hour, minute and second.

2020-09-28 23:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´textarea´    | A common HTML textarea.                                                                                           |
Would suggest that this be moved to under 'text'

2020-09-28 23:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´button´      | A common html button. It is necessary to declare a custom ´frontend_model´ in order to use the button field type. |
Would also recommend mentioning : Requires custom front-end model to define the button text and the action. See `Magento\ScheduledImportExport\Block\Adminhtml\System\Config\Clean` for an example

2020-09-28 23:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
> +| ´image´       | Possible Image upload. The nodes ´backend_model´, ´upload_dir´ and ´base_url´ needs to be defined as well.        |
'password'
'file'
'label'
'allowspecific'

Need defining. Password is different to obscure.

2020-09-28 23:14 UTC, BarnyShergold commented
@DavidLambauer - I have added a lot of additional changes to be made and the 2.4 version of the file needs doing.

I accidentally created a second PR as this one wasn't linked to the issue (which is why I have made other suggestions). Therefore, if you want me to complete the work, I can arrange for THIS PR to be closed and use my PR to solve the issue.

The only downside is that you won't get any contributor points for this. Perhaps we can swap roles? If you were to review MY PR you would score points but as a Maintainer? (On DevDocs Maintainer = Contributor)

I'll leave this open for a few days

2020-09-29 10:20 UTC, DavidLambauer commented
All good. I don't contribute for the reason of "points", so feel free to continue in the new PR.

2020-09-29 10:22 UTC, BarnyShergold commented
> All good. I don't contribute for the reason of "points", so feel free to continue in the new PR.

Okay @DavidLambauer - that's great and thanks for the understanding . I'll get the PRs sorted and then ask you to review - that way it all gets done and your valuable input will be used :)

2020-10-02 03:48 UTC, meker12 commented
@BarnyShergold  I believe this can be closed because changes merged in PR #7948. Please confirm.

2020-10-02 08:09 UTC, BarnyShergold commented
Closed because changes merged in PR #7948.

2020-10-02 08:09 UTC, closed without merging