Added Slave Database Connection Information
magento/devdocs pull request #7924
Opened 2020-09-23 16:32 UTC by BarnyShergold

## Purpose of this pull request

This pull request (PR) fixes #6067 

## Affected DevDocs pages
https://devdocs.magento.com/cloud/project/services-mysql.html

2020-09-23 16:33 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-23 16:34 UTC, BarnyShergold commented
@meker12  & @hguthrie - I thought I'd get this issue underway and start with some basic information. Where shall we go from here?

2020-09-24 09:07 UTC, rogyar approved these changes
In the future, it would be great to provide some information on how the fact of different ports affects the configuration (configuration examples)

2020-09-24 09:38 UTC, BarnyShergold commented
> In the future, it would be great to provide some information on how the fact of different ports affects the configuration (configuration examples)

@rogyar - I agree but where can we get the definitive port information from? (BTW I wasn't expecting this PR to be reviewed yet, was waiting to discuss and expand with @hguthrie & @meker12 )

2020-09-24 17:58 UTC, dobooth commented
Slave isn't going to work as a term. Let's use 'secondary'.

2020-09-24 18:06 UTC, meker12 commented
> Slave isn't going to work as a term. Let's use 'secondary'.
We can use that in the text, but the Magento code base still uses master/slave for databases.

2020-09-24 19:43 UTC, meker12 requested changes

2020-09-24 19:43 UTC, meker12 commented on src/cloud/project/services-mysql.md
> +accessing the Slave database, consult the [Magento Commerce Cloud best practice for slave connection](https://support.magento.com/hc/en-us/articles/360049045351) article.
```suggestion
## Connect to secondary database

In some cases, you might need to connect to the secondary database, for example to improve database performance or resolve database locking issues. If this configuration is required, use port **3304** to establish the connection. See the [Magento Commerce Cloud best practice for slave connection](https://support.magento.com/hc/en-us/articles/360049045351) article in the _Magento Help Center_].   
```

2020-09-24 19:59 UTC, meker12 approved these changes

2020-09-24 20:01 UTC, meker12 commented
running tests

2020-09-24 21:30 UTC, merged