MQE-2298: Move and update test BIC document to DevDocs
magento/devdocs pull request #7934
Opened 2020-09-24 23:24 UTC by jilu1

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2020-09-24 23:25 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-25 08:02 UTC, BarnyShergold requested changes
Please add an appropriate description of the PR as per DevDocs guidelines
Correct linting errors.

Also this is a new page but there is no menu point to get to this page - this should be created.

Reviewer assumes that new technical content is correct.

2020-10-02 13:21 UTC, dobooth commented on src/guides/v2.4/extension-dev-guide/versioning/mftf-tests-codebase-changes.md
> +For instance: a fix which aims to resolve test flakiness. This can be done by updating an unreliable selector, adding a `wait` to an element, or updating a data entity value.
I think "flakiness" is almost a  term of art in testing.

2020-10-02 13:50 UTC, dobooth commented
running tests

2020-10-02 13:50 UTC, dobooth approved these changes

2020-10-02 14:10 UTC, merged