Space added
magento/devdocs pull request #7975
Opened 2020-10-02 12:48 UTC by ejaz-alam

added a space.

## Purpose of this pull request

added space to make separate the **query** Key

2020-10-02 12:53 UTC, BarnyShergold requested changes
Please update the PR description show what pages are being addresses (see other PRs for examples)

Also the 2.3 version of the file has the same error - please fix on this file and add to this PR.

2020-10-02 16:39 UTC, dobooth approved these changes

2020-10-07 14:25 UTC, dobooth commented
Hi @ejaz-alam Can you please make this same change to the v2.3 file? Thanks!

2020-10-16 13:12 UTC, dobooth commented
So close. Closing as abandoned.

2020-10-16 13:12 UTC, closed without merging