ES recommendedation > Removing inconsistencies
magento/devdocs pull request #7980
Opened 2020-10-02 15:55 UTC by rafaelstz

## Purpose of this pull request

The purpose is to remove the inconsistencies that were conflicting with the recommendations provided in those pages below.

- https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-nginx.html
- https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-apache.html

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html#es-arch

## Reference

-  https://github.com/magento/devdocs/issues/7562

2020-10-05 07:54 UTC, BarnyShergold requested changes
One teeny change

But this is much clearer now

2020-10-05 07:54 UTC, BarnyShergold commented on src/guides/v2.4/install-gde/prereq/elasticsearch.md
> +   Running on separate hosts require proxying to work. (Clustering Elasticsearch is beyond the scope of this guide but you can find more information in the [Elasticsearch clustering documentation][].
```suggestion
   Running on separate hosts requires proxying to work. (Clustering Elasticsearch is beyond the scope of this guide but you can find more information in the [Elasticsearch clustering documentation][].)
```

2020-10-07 14:27 UTC, dobooth approved these changes

2020-10-07 17:47 UTC, dobooth commented
running tests

2020-10-07 18:04 UTC, merged