Mc 37903
magento/devdocs pull request #8008
Opened 2020-10-07 18:36 UTC by thiaramus

## Purpose of this pull request

This pull request (PR) is to separate patch application methods from one single page to individual pages.
MQP section is rather large and it would be nice to have it on a separate page, alongside the composer and command line patch application methods.

The work was done in the scope of the JIRA story: https://jira.corp.magento.com/browse/MC-37903

Certain Help Center pages are currently pointing to the https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html and https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html#mpq, the change should not break the links, but I will work on updating the related articles to point directly to the new MQP page after the PR is merged.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html
- https://devdocs.magento.com/quality-patches/release-notes.html
- https://devdocs.magento.com/cloud/project/project-patch.html

2020-10-07 18:36 UTC, magento-engcom-team commented
@thiaramus thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-10-08 14:23 UTC, viktym commented on src/cloud/project/project-patch.md
> +You can use the [Magento Quality Patches]({{ site.baseurl }}/guides/v2.4/comp-mgr/patching/mqp.html#mqp) and [{{ site.data.var.mcp-prod }}](#standalone) packages as stand-alone packages for {{ site.d
```suggestion
You can use the [Magento Quality Patches]({{ site.baseurl }}/guides/v2.4/comp-mgr/patching/mqp.html) and [{{ site.data.var.mcp-prod }}](#standalone) packages as stand-alone packages for {{ site.data.var.ce }} and {{ site.data.var.ee }} projects. We recommend using the Magento Quality Patches package for non-Cloud projects.
```

2020-10-08 14:24 UTC, viktym commented on src/cloud/project/project-patch.md
> +Use the [Magento Quality Patches]({{ site.baseurl }}/guides/v2.4/comp-mgr/patching/mqp.html#mqp) package for {{ site.data.var.ce }} and {{ site.data.var.ee }} projects.
```suggestion
Use the [Magento Quality Patches]({{ site.baseurl }}/guides/v2.4/comp-mgr/patching/mqp.html) package for {{ site.data.var.ce }} and {{ site.data.var.ee }} projects.
```

2020-10-08 14:36 UTC, viktym commented on src/guides/v2.3/comp-mgr/patching/mqp.md
> +If it is not already installed, you must install [Git](https://github.com/git-guides/install-git) before installing the MQP package.
```suggestion
If it is not already installed, you must install [Git](https://github.com/git-guides/install-git) or [Patch](https://man7.org/linux/man-pages/man1/patch.1.html) before installing the MQP package.
```

2020-10-08 14:36 UTC, viktym commented on src/quality-patches/release-notes.md
> +See [Apply patches]({{ site.baseurl }}/guides/v2.4/comp-mgr/patching/mqp.html#mqp) for instructions on applying patches to your Magento projects.
```suggestion
See [Apply patches]({{ site.baseurl }}/guides/v2.4/comp-mgr/patching/mqp.html) for instructions on applying patches to your Magento projects.
```

2020-10-08 17:56 UTC, meker12 requested changes

2020-10-08 17:56 UTC, meker12 commented on src/guides/v2.3/comp-mgr/patching/command-line.md
> +1. Upload the local file into the `<Magento_root>` on the server using FTP, SFTP, SSH or your normal transport method.
```suggestion
1. Upload the local file into the `<Magento_root>` directory on the server using FTP, SFTP, SSH or your normal transport method.
```

2020-10-08 17:56 UTC, meker12 commented on src/guides/v2.3/comp-mgr/patching/mqp.md
> +The [MQP package][] delivers individual patches developed by Magento and allows you to apply, revert, and view general information about all individual patches that are available for the installed ve
```suggestion
The [Magento Quality Package (MQP) package][] delivers individual patches developed by Magento and allows you to apply, revert, and view general information about all individual patches that are available for the installed version of {{ site.data.var.ee }} or {{ site.data.var.ce }}.
```

2020-10-08 17:56 UTC, meker12 commented on src/guides/v2.3/comp-mgr/patching/mqp.md
> +[MQP package]: https://github.com/magento/quality-patches
```suggestion
[Magento Quality Package (MQP) package]: https://github.com/magento/quality-patches
```

2020-10-08 17:56 UTC, meker12 commented on src/guides/v2.3/comp-mgr/patching/composer.md
> +To apply a custom patch using Composer:
```suggestion
{.:procedure}
To apply a custom patch using Composer:
```

2020-10-08 20:16 UTC, meker12 approved these changes

2020-10-08 20:26 UTC, merged