Update Compatibility table
magento/devdocs pull request #8009
Opened 2020-10-07 18:48 UTC by hickskenh

## Purpose of this pull request

This pull request (PR) adds Amazon Sales Channel 4.3.0 to the release/compatibility table.

## Affected DevDocs pages

-  https://devdocs.magento.com/release/availability.html

2020-10-07 18:55 UTC, BarnyShergold requested changes
You have some linting errors but everything else seems fine

2020-10-07 20:22 UTC, hickskenh commented
running tests

2020-10-07 20:55 UTC, hickskenh commented
@BarnyShergold  looks like linting errors appear to be a bug in the super linter, and do not block merge.  can you provide approval?

2020-10-07 21:45 UTC, dshevtsov approved these changes

2020-10-08 12:24 UTC, BarnyShergold approved these changes

2020-10-08 14:34 UTC, merged