update inventory-cli-reference.md incorrect info
magento/devdocs pull request #8023
Opened 2020-10-10 08:19 UTC by irajneeshgupta

Since the CLI command inventory:reservation:create-compensations yet not  accepting the -c -d & -i argument ,  I rectified few points here for incorrect message string and the arguments.

Correct way to use this command is to pipe both commands like this :
```bash
bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations
```
& if any one need to run it for -i (incomplete orders ) OR -c for complete orders , they may run like by piping and use :
```bash
bin/magento inventory:reservation:list-inconsistencies -r -i | bin/magento inventory:reservation:create-compensations 
``` 
```bash
bin/magento inventory:reservation:list-inconsistencies -r -c | bin/magento inventory:reservation:create-compensations
```
And if anyone wants for all orders , there is no need to specify any argument here like this :

bin/magento inventory:reservation:list-inconsistencies  | bin/magento inventory:reservation:create-compensations (For complete orders)

-r  was used to output raw result.
 

## Purpose of this pull request

This pull request (PR) is for rectifying the given page for more clarity to users since those arguments are useless for anyone using 2.3.x or 2.4.x and **the command ``inventory:reservation:create-compensations`` was meant for accepting only STDIN and -r argument only.**

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/inventory/inventory-cli-reference.html
- File : inventory-cli-reference.md

## Links to Magento source code

2020-10-10 08:47 UTC, irajneeshgupta commented
#dmcdindia2020

2020-10-10 12:47 UTC, rogyar approved these changes
Hi @irajneeshgupta, thank you for your contribution. 
I can confirm that the mentioned command accepts only `-r` parameter. Example from the codebase below

https://github.com/magento/inventory/blob/1.2-develop/InventoryReservationCli/Command/CreateCompensations.php#L65

2020-10-12 22:45 UTC, meker12 requested changes

2020-10-14 18:05 UTC, meker12 approved these changes

2020-10-14 18:51 UTC, meker12 commented
running tests

2020-10-15 15:26 UTC, keharper commented on src/guides/v2.3/inventory/inventory-cli-reference.md
> +You can also pipe the commands to detect inconsistencies and create compensations for only incomplete (`-i`) or complete (`-c`) orders.
The line "No order inconsistencies were found." above is output. Separate the output  from the input, as you did for the previous example.

2020-10-15 15:45 UTC, keharper commented on src/guides/v2.3/inventory/inventory-cli-reference.md
> +-  `-b`, `--bunchsize` - Defines how many orders to load at once.
```suggestion
-  `-b`, `--bunch-size` - Defines how many orders to load at once.
```

2020-10-15 18:48 UTC, keharper approved these changes

2020-10-15 18:50 UTC, meker12 commented
running tests

2020-10-16 19:07 UTC, meker12 commented
running tests

2020-10-16 19:34 UTC, merged