Update cloud-architecture.md
magento/devdocs pull request #8024
Opened 2020-10-10 16:36 UTC by seeni9589

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2020-10-10 16:36 UTC, magento-engcom-team commented
@seeni9589 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-10-10 17:36 UTC, BarnyShergold requested changes
Good spot @seeni9589 and the correction is fine but you need to -
1. Sign the Adobe CLA
2. Correctly fill in the PR description. PLease check this one for reference : https://github.com/magento/devdocs/pull/8000

2020-10-10 18:37 UTC, seeni9589 commented
@BarnyShergold Both actions are done.

2020-10-12 14:26 UTC, meker12 approved these changes

2020-10-12 14:27 UTC, meker12 commented
running tests

2020-10-12 14:57 UTC, merged