Fix link format
magento/devdocs pull request #8032
Opened 2020-10-12 15:55 UTC by meker12

## Purpose of this pull request

Fixes an incorrect link format.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-var-name.html#how-to-use-environment-variables

2020-10-12 17:01 UTC, BarnyShergold requested changes

2020-10-12 17:01 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/prod/config-reference-var-name.md
> +*  For Magento Commerce Cloud, if you are attempting to override Magento configuration settings using the [Project Web Interface](https://devdocs.magento.com/guides/v2.3/cloud/project/project-webint-
Whilst this is being changed, perhaps change the link to the new one  - https://devdocs.magento.com/cloud/project/project-webint-basic.html#project-conf-env-var

2020-10-12 20:22 UTC, dobooth commented
Hardcoded link to v2.3?

2020-10-12 20:49 UTC, meker12 commented on src/guides/v2.3/config-guide/prod/config-reference-var-name.md
> +*  For Magento Commerce Cloud, if you are attempting to override Magento configuration settings using the [Project Web Interface](https://devdocs.magento.com/guides/v2.3/cloud/project/project-webint-
```suggestion
*  For Magento Commerce Cloud, if you are attempting to override Magento configuration settings using the [Project Web Interface]({{ site.baseurl }}/cloud/project/project-webint-basic.html#project-conf-env-var), you must prepend the variable name with `env:`. For example:
```

2020-10-12 22:30 UTC, BarnyShergold approved these changes

2020-10-14 14:13 UTC, dobooth approved these changes

2020-10-14 14:14 UTC, dobooth commented
running tests

2020-10-14 14:28 UTC, merged