Add note about snapshot best practice
magento/devdocs pull request #8044
Opened 2020-10-14 16:27 UTC by meker12

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/architecture/pro-architecture.html

2020-10-14 16:50 UTC, meker12 commented on src/cloud/architecture/pro-architecture.md
> +On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging e
```suggestion
On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging environments using CLI commands. See [Dump your database]({{  site.baseurl }}/cloud/project/project-webint-snap.html#db-dumpump] and [bin/magento setup:backup]({{site.baseurl }}/guides/v2.4/reference/cli/magento-commerce.htm#setupbackup). For Integration environments, we highly recommend that you create a snapshot as a first step after accessing your {{site.data.var.ece}} project and before applying any major changes. See [Snapshots and backup management](https://devdocs.magento.com/cloud/project/project-webint-snap.html).
```

2020-10-14 19:49 UTC, hguthrie requested changes
Couple of broken things to fix.

2020-10-14 19:49 UTC, hguthrie commented on src/cloud/architecture/pro-architecture.md
> +{:.tip}
This does nothing.

Maybe need to use: 
```suggestion
{:.bs-callout-tip}
```

2020-10-14 19:49 UTC, hguthrie commented on src/cloud/architecture/pro-architecture.md
> +On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging e
Broken links

```suggestion
On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging environments using CLI commands. See [Dump your database]({{  site.baseurl }}/cloud/project/project-webint-snap.html#db-dump) and [bin/magento setup:backup]({{site.baseurl }}/guides/v2.4/reference/cli/magento-commerce.htm#setupbackup). For Integration environments, we highly recommend that you create a snapshot as a first step after accessing your {{site.data.var.ece}} project and before applying any major changes. See [Snapshots and backup management](https://devdocs.magento.com/cloud/project/project-webint-snap.html).
```

2020-10-14 22:18 UTC, meker12 commented on src/cloud/architecture/pro-architecture.md
> +On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging e
```suggestion
On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging environments using CLI commands. See [Dump your database]({{site.baseurl}}/cloud/project/project-webint-snap.html#db-dump) and [bin/magento setup:backup]({{site.baseurl }}/guides/v2.4/reference/cli/magento-commerce.htm#setupbackup). For Integration environments, we highly recommend that you create a snapshot as a first step after accessing your {{site.data.var.ece}} project and before applying any major changes. See [Snapshots and backup management]({{ site.baseurl}}/cloud/project/project-webint-snap.html).
```

2020-10-14 22:18 UTC, meker12 commented on src/cloud/architecture/pro-architecture.md
> +On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging e
```suggestion
On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging environments using CLI commands. See [Dump your database]({{site.baseurl}}/cloud/project/project-webint-snap.html#db-dump) and [bin/magento setup:backup]({{site.baseurl }}/guides/v2.4/reference/cli/magento-commerce.htm#setupbackup). For Integration environments, we highly recommend that you create a snapshot as a first step after accessing your {{site.data.var.ece}} project and before applying any major changes. See [Snapshots and backup management]({{site.baseurl}}/cloud/project/project-webint-snap.html).
```

2020-10-15 13:36 UTC, hguthrie approved these changes

2020-10-15 14:52 UTC, meker12 commented
running tests

2020-10-15 15:16 UTC, meker12 commented on src/cloud/architecture/pro-architecture.md
> +On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging e
```suggestion
On Pro Staging and Production environments, you must submit a support ticket to restore an environment from an automatic backup. You can backup the database and code for your Production and Staging environments using CLI commands. See [Dump your database]({{site.baseurl}}/cloud/project/project-webint-snap.html#db-dump) and [bin/magento setup:backup]({{site.baseurl }}/guides/v2.4/reference/cli/magento-commerce.html#setupbackup). For Integration environments, we highly recommend that you create a snapshot as a first step after accessing your {{site.data.var.ece}} project and before applying any major changes. See [Snapshots and backup management]({{site.baseurl}}/cloud/project/project-webint-snap.html).
```

2020-10-15 15:29 UTC, meker12 commented
running tests

2020-10-15 15:47 UTC, merged