Session garbage collection configuration
magento/devdocs pull request #8053
Opened 2020-10-15 14:12 UTC by victorpetryk

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2020-10-15 14:12 UTC, magento-engcom-team commented
@victorpetryk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-10-15 14:37 UTC, jeff-matthews commented
@victorpetryk, does this apply to both the 2.4.x and 2.3.x release lines or 2.4.x only?

2020-10-15 14:44 UTC, jeff-matthews requested changes

2020-10-15 14:44 UTC, jeff-matthews commented on src/_includes/config/locate-session.md
> +To clean up expired sessions Magento application calls `gc` (_garbage collection_) handler randomly according to probability which is calculated by `gc_probability / gc_divisor`. For example, if we s
```suggestion
To clean up expired sessions, Magento calls the `gc` (_garbage collection_) handler randomly according to a probability that is calculated by the `gc_probability / gc_divisor` directive. For example, if you set these directives to `1/100` respectively, it means a probability of `1%` (_probability of one call of garbage collection per 100 requests_).
```

2020-10-15 14:44 UTC, jeff-matthews commented on src/_includes/config/locate-session.md
> +The garbage collection handler uses the `gc_maxlifetime` directive - the number of seconds after which the sessions will be seen as _garbage_ and potentially cleaned up.
```suggestion
The garbage collection handler uses the `gc_maxlifetime` directive—the number of seconds after which the sessions will be seen as _garbage_ and potentially cleaned up.
```

2020-10-15 14:44 UTC, jeff-matthews commented on src/_includes/config/locate-session.md
> +On some operating systems (Debian/Ubuntu) `session.gc_probability` set to `0` by default, and the garbage collection handler will never be executed.
```suggestion
On some operating systems (Debian/Ubuntu), the default `session.gc_probability` directive is `0`, which prevents the garbage collection handler from running.
```

2020-10-15 14:44 UTC, jeff-matthews commented on src/_includes/config/locate-session.md
> +`session.gc_` directives from the `php.ini` file can be overwritten in `<magento_root>/app/etc/env.php`:
```suggestion
You can overwrite the `session.gc_` directives from the `php.ini` file in the `<magento_root>/app/etc/env.php` file:
```

2020-10-15 14:44 UTC, jeff-matthews commented on src/_includes/config/locate-session.md
> +The configuration depends on the traffic and specific needs of a certain Magento application.
```suggestion

The configuration depends on the traffic and specific needs of a certain Magento application.
```

2020-10-15 14:50 UTC, victorpetryk commented
> @victorpetryk, does this apply to both the 2.4.x and 2.3.x release lines or 2.4.x only?

@jeff-matthews This applies to 2.4.x only as changes to configure garbage collection from env.php file will be delivered to 2.4.2

2020-10-15 15:11 UTC, jeff-matthews commented
Thanks for confirming @victorpetryk. 

Since it applies to 2.4.x only, I need you to do the following:

1. Replace the symlinked `src/guides/v2.4/config-guide/sessions.md` file with a copy of the `src/guides/v2.3/config-guide/sessions.md` file.
1. Replace the `include` reference (`{% include config/locate-session.md %}`) from the new 2.4 file with the revised text of your new section (https://github.com/magento/devdocs/pull/8053/commits/e436d7744e420daa500aa4233f1022786d457140). We don't use this include file anywhere else inn devdocs, so I don't think we even need it.
1. Revert all changes to the `src/_includes/config/locate-session.md` file. This will be sued for 2.3 only and should not contain information about garbage collection.

I understand that may be tedious, so if you prefer, I would be happy to create a copy of your branch and do it myself. Just let me know what you prefer.

2020-10-15 15:19 UTC, victorpetryk commented
@jeff-matthews Let me ask PO about the necessity to backport a fix about GC to the 2.3.x release line. And if so the devdocs will need to be updated for 2.3.x as well.

2020-10-20 12:43 UTC, victorpetryk commented
@jeff-matthews I've created a backported fix for the 2.3.x release line. So we can continue to proceed with this PR.

2020-10-20 13:20 UTC, jeff-matthews commented
Sounds good @victorpetryk. Thanks!

2020-10-20 13:20 UTC, jeff-matthews commented
running tests

2020-10-20 13:38 UTC, jeff-matthews approved these changes

2020-10-20 13:39 UTC, merged