Update contributing.md
magento/devdocs pull request #8095
Opened 2020-10-20 15:35 UTC by lenaorobei

## Purpose of this pull request

This PR fixes information about test instance deployer:
- Fixed info about supported tags and branches.
- Removed part about `Environment` that is not yet implemented.

## Affected DevDocs pages

-  https://devdocs.magento.com/contributor-guide/contributing.html

2020-10-20 15:38 UTC, BarnyShergold requested changes
Tiny change recommended

2020-10-20 15:38 UTC, BarnyShergold commented on src/contributor-guide/contributing.md
> +Replace `{$version}` with the version tag or branch. The currently supported values are: the latest released version and the `2.4-develop` branch. For example:
```suggestion
Replace `{$version}` with the version tag or branch. The currently supported values are, the latest released version and the `2.4-develop` branch. For example:
```

2020-10-26 18:41 UTC, meker12 commented on src/contributor-guide/contributing.md
> +Replace `{$version}` with the version tag or branch. The currently supported values are, the latest released version and the `2.4-develop` branch. For example:
```suggestion
Replace `{$version}` with the version tag or branch. The following values are supported for `{$version}`: the version number for the latest release, and `2.4-develop` for the development branch.
```

2020-10-26 22:25 UTC, meker12 commented
running tests

2020-10-26 22:25 UTC, meker12 approved these changes

2020-10-26 22:44 UTC, merged