ISSUE-7986: The topics for the "Company Role" mutations and "checkCompanyRoleName" query have been created
magento/devdocs pull request #8097
Opened 2020-10-20 19:49 UTC by andrewbess

## Purpose of this pull request

This pull request (PR) add new topics for "Company Role" mutations and "checkCompanyRoleName" query for new 2.4.2 features.

fixes #7986 

### Fixed Issues (if relevant)

1. magento/devdocs#7986: GraphQL: Add company role mutations

### Whatsnew
Added the following mutations in support of B2B companies: [createCompanyRole](https://devdocs.magento.com/guides/v2.4/graphql/mutations/create-company-role.html), [updateCompanyRole](https://devdocs.magento.com/guides/v2.4/graphql/mutations/update-company-role.html), [deleteCompanyRole](https://devdocs.magento.com/guides/v2.4/graphql/mutations/delete-company-role.html), and [checkCompanyRoleName](https://devdocs.magento.com/guides/v2.4/graphql/queries/check-company-role-name.html) query.

2020-10-21 08:00 UTC, rogyar requested changes
Hi @andrewbess. Amazing job! Please, check my comments below

2020-10-21 09:56 UTC, andrewbess commented
Hello @rogyar 

Thank you for your review.
I completely agree with you.
I have fixed it. Please recheck.
Thank you in advance.

2020-10-26 21:01 UTC, andrewbess commented
The merge-conflict has been resolved.

2020-10-29 10:05 UTC, rogyar approved these changes

2020-10-29 10:05 UTC, rogyar commented
From the technical perspective looks good. Thanks @andrewbess for your work

2020-11-05 15:12 UTC, dobooth requested changes

2020-11-05 18:33 UTC, dobooth commented on src/guides/v2.4/graphql/mutations/create-company-role.md
> +        sort_order
My bad. Incoming code changes it to sort_order

2020-11-05 18:33 UTC, dobooth commented on src/guides/v2.4/graphql/mutations/update-company-role.md
> +        sort_order
Nope. This will be correct in the near future. Belay.

2020-11-09 11:34 UTC, dobooth approved these changes

2020-11-09 11:34 UTC, dobooth commented
running tests

2020-11-09 11:55 UTC, merged