Updated another way of string translation in js
magento/devdocs pull request #8098
Opened 2020-10-21 11:37 UTC by srsathish92

## Purpose of this pull request

This pull request (PR) to update the another way of strings translation in js.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/translations/translate_theory.html#add_strings_js
- https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/translations/translate_theory.html#add_strings_js

## Links to Magento source code
- https://github.com/magento/magento2/blob/2.4/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js#L91

2020-10-21 12:17 UTC, BarnyShergold requested changes
Nice addition

2020-10-21 12:17 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/translations/translate_theory.md
> +   (or)
Braces around a textual word look a little odd and may cause confusion
```suggestion
   or
```

2020-10-21 12:17 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/translations/translate_theory.md
> +   (or)
```suggestion
   or
```

2020-10-21 12:44 UTC, BarnyShergold approved these changes
Thanks!

2020-10-22 02:04 UTC, srsathish92 commented
@BarnyShergold Thank you for review

2020-11-06 13:34 UTC, dobooth approved these changes

2020-11-06 13:38 UTC, dobooth commented
running tests

2020-11-06 13:56 UTC, merged