Layout overview small typo fix
magento/devdocs pull request #8160
Opened 2020-10-30 13:28 UTC by gren236

## Purpose of this pull request

This pull request (PR) fixes a small typo error at `/guides/v2.4/frontend-dev-guide/layouts/layout-overview.html` page

## Affected DevDocs pages

-  /guides/v2.4/frontend-dev-guide/layouts/layout-overview.html

2020-10-30 13:28 UTC, magento-engcom-team commented
@gren236 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-10-30 14:45 UTC, BarnyShergold requested changes
Thanks for your submission! I've spotted a punctuation error earlier in the sentence!

Please can you also sign the CLA?

2020-10-30 14:45 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/layout-overview.md
> +The objective is to create a structured, common set of layout instructions to render pages. Most pages on a website can be categorized as a 1 column, 2 column, or 3 column layout. These page layouts
```suggestion
The objective is to create a structured, common set of layout instructions to render pages. Most pages on a website can be categorized as a 1 column, 2 column or 3 column layout. These page layouts can be applied to a page from within the admin panel.
```

2020-11-02 11:58 UTC, dobooth approved these changes

2020-11-02 12:01 UTC, BarnyShergold approved these changes

2020-11-02 12:03 UTC, merged