Added Note Type & Custom Type definitions
magento/devdocs pull request #8162
Opened 2020-10-30 17:32 UTC by BarnyShergold

## Purpose of this pull request

This pull request (PR) fixes #7961 & adds 'note' type

## Affected DevDocs pages
https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-systemxml.html
https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-systemxml.html

2020-11-02 19:42 UTC, dobooth requested changes

2020-11-02 19:42 UTC, dobooth commented on src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
> +-  Creating a Block in the `adminhtml` area
lowercase 'block'. Are there 3 quotes in `type=`?

2020-11-02 19:42 UTC, dobooth commented on src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
> +The block itself requires, at a minimum, a `__contstuct` method and a `getElementalHtml()` method. The [Magento_OfflineShipping](https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento/
`__construct`
The github link will fail after 2.4-develop is merged. There is a var for the repo.

2020-11-09 12:04 UTC, dobooth commented
@BarnyShergold

2020-11-09 21:25 UTC, dobooth approved these changes

2020-11-12 14:49 UTC, rogyar approved these changes

2020-11-17 11:15 UTC, BarnyShergold commented
@dobooth - Can this not be completed now? Approvals were done a week ago 😄

2020-11-17 16:19 UTC, keharper commented
running tests

2020-11-17 16:38 UTC, merged