Updating releases notes and image
magento/devdocs pull request #8176
Opened 2020-11-03 20:13 UTC by erikmarr

## Purpose of this pull request

This pull request (PR) updates the release notes for product recommendations as well as an outdated image.

## Affected DevDocs pages

-  https://devdocs.magento.com/recommendations/release-notes.html
-  https://devdocs.magento.com/recommendations/verify.html
-  https://devdocs.magento.com/release/availability.html

2020-11-03 22:14 UTC, misha-kotov requested changes
Release notes look good. 
Compatibility: 
3.0.8 should be `compatible` across the board - looks like there are still some `supported` currently. same for 3.0.6

2020-11-04 15:12 UTC, misha-kotov approved these changes

2020-11-04 16:24 UTC, keharper approved these changes
One tiny change

2020-11-04 16:24 UTC, keharper commented on src/recommendations/release-notes.md
> +-  {:.new}Added ability to [resync your catalog to SaaS services via command line]({{ page.baseurl }}/config-guide/cli/config-cli-subcommands-catalog-sync.html)
```suggestion
-  {:.new}Added the ability to [resync your catalog to SaaS services via command line]({{ page.baseurl }}/config-guide/cli/config-cli-subcommands-catalog-sync.html)
```

2020-11-04 16:36 UTC, erikmarr commented
running tests

2020-11-04 19:48 UTC, erikmarr commented
running tests

2020-11-04 20:14 UTC, merged