Clarify that the default value for the max_allowed_packets setting applies to cloud and on-premises projects
magento/devdocs pull request #8187
Opened 2020-11-05 15:30 UTC by jeff-matthews

## Purpose of this pull request

This pull request (PR) clarifies that the default value of 16MB for MySQL `max_allowed_packets` applies to both cloud and on-premises projects.

The linked KB article is still in draft and has not yet been published.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/install-gde/prereq/mysql.html

whatsnew
Added clarification that the default value of 16MB for the MySQL [`max_allowed_packets`](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/mysql.html) setting applies to both Magento Commerce Cloud and on-premises projects.

2020-11-05 16:18 UTC, meker12 requested changes

2020-11-05 16:18 UTC, meker12 commented on src/guides/v2.3/install-gde/prereq/mysql.md
> +   The default applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the default. {{site.data.var.ece}} Starter custo
```suggestion
   The default value applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the `max_allowed_packet` value. {{site.data.var.ece}} Starter customers can increase the  value by updating the configuration in the [`/etc/mysql/my.cnf`](https://support.magento.com/hc/en-us/articles/360051598831) file.
```

2020-11-05 16:18 UTC, meker12 commented on src/guides/v2.4/install-gde/prereq/mysql.md
> +The default applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the default. {{site.data.var.ece}} Starter customer
```suggestion
The default value applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the `max_allowed_packet` value. {{site.data.var.ece}} Starter customers can increase the  value by updating the configuration in the [`/etc/mysql/my.cnf`](https://support.magento.com/hc/en-us/articles/360051598831) file.
```

2020-11-05 16:20 UTC, meker12 approved these changes

2020-11-05 16:21 UTC, meker12 commented on src/guides/v2.4/install-gde/prereq/mysql.md
> +The default value applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the `max_allowed_packet` value. {{site.data.v
```suggestion
The default value applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the `max_allowed_packet` value. {{site.data.var.ece}} Starter customers can increase the value by updating the configuration in the [`/etc/mysql/my.cnf`](https://support.magento.com/hc/en-us/articles/360051598831) file.
```

2020-11-05 16:21 UTC, meker12 commented on src/guides/v2.3/install-gde/prereq/mysql.md
> +   The default value applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the `max_allowed_packet` value. {{site.dat
```suggestion
   The default value applies to {{site.data.var.ece}} *and* on-premises projects. {{site.data.var.ece}} Pro customers must open a support ticket to increase the `max_allowed_packet` value. {{site.data.var.ece}} Starter customers can increase the value by updating the configuration in the [`/etc/mysql/my.cnf`](https://support.magento.com/hc/en-us/articles/360051598831) file.
```

2020-11-05 16:22 UTC, meker12 approved these changes

2020-11-05 20:11 UTC, hguthrie commented
So, I wondered if the Cloud guide needed to discuss the `my.cnf` file more, and it seem that it is only mentioned in the older local development set up and in the Docker service containers section. I think we should investigate whether this is worth mentioning where custom configuration of the `my.cnf` file is explained. For example, can this be added to the db:environment section of the Docker override YML? Just curious.

2020-11-06 14:50 UTC, meker12 commented
> So, I wondered if the Cloud guide needed to discuss the `my.cnf` file more, and it seem that it is only mentioned in the older local development set up and in the Docker service containers section. I think we should investigate whether this is worth mentioning where custom configuration of the `my.cnf` file is explained. For example, can this be added to the db:environment section of the Docker override YML? Just curious.

2020-11-06 21:35 UTC, jeff-matthews commented
running tests

2020-11-06 21:55 UTC, merged