Issue 8189 - L2 caching example change
magento/devdocs pull request #8194
Opened 2020-11-06 12:03 UTC by dineshvb

## Purpose of this pull request

This pull request (PR) will cover #8189 

## Affected DevDocs pages

-  guides/v2.4/config-guide/cache/two-level-cache.html

2020-11-08 13:53 UTC, rogyar requested changes

2020-11-08 13:53 UTC, rogyar commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
>      [
We may still have an error here. The cache node should not contain another array. Please, correct me if I'm wrong
```suggestion

```

2020-11-09 06:27 UTC, dineshvb commented
@rogyar Would need some technical assistance so that I could change it.

2020-11-10 12:21 UTC, rogyar commented
Hi @dineshvb. Could you clarify, please, what type of technical assistance do you need? Thanks.

2020-11-10 13:37 UTC, dineshvb commented
@rogyar just that array symbol, shall I delete it?

2020-11-12 14:56 UTC, rogyar commented
Hi @dineshvb. Here is the correct version of your example 

```php
'cache' => [
            'frontend' => [
                'default' => [
                    'backend' => '\\Magento\\Framework\\Cache\\Backend\\RemoteSynchronizedCache',
                    'backend_options' => [
                        'remote_backend' => '\\Magento\\Framework\\Cache\\Backend\\Redis',
                        'remote_backend_options' => [
                            'persistent' => 0,
                            'server' => 'localhost',
                            'database' => '0',
                            'port' => '6370',
                            'password' => '',
                            'compress_data' => '1',
                        ],
                        'local_backend' => 'Cm_Cache_Backend_File',
                        'local_backend_options' => [
                            'cache_dir' => '/dev/shm/'
                        ]
                    ],
                    'frontend_options' => [
                        'write_control' => false,
                    ],
                    'use_stale_cache' => false,
                ]
            ]
        ],
        'type' => [
            'default' => ['frontend' => 'default'],
        ]
```

2020-11-18 06:10 UTC, dineshvb commented
@rogyar @dobooth I have made the requested changes

2020-11-19 13:28 UTC, dobooth commented
Is this another change for `master`?

2020-11-19 13:41 UTC, dineshvb commented
> Is this another change for `master`?

No, these changes are for 2.4.2-develop branch since the issue only addresses the 2.4 version

2020-11-23 12:46 UTC, dobooth commented
Thanks @dineshvb. To be clear, the `master` branch is for currently release docs, v2.3 and v2.4, which includes 2.4.1. If this is a fix to a live doc, then it would go to `master`. The `2.4.2-develop` branch is to document code for features that will be available in the 2.4.2 release, which is early next year. If we keep this as it is, it will not go live until the release next year.

2020-11-24 06:24 UTC, dineshvb commented
@dobooth Rebased to master branch

2020-11-24 14:25 UTC, dobooth commented
running tests

2020-11-24 14:45 UTC, dobooth approved these changes

2020-11-24 14:45 UTC, merged