Cloud docker 1.2.0
magento/devdocs pull request #8199
Opened 2020-11-06 21:34 UTC by meker12

## Purpose of this pull request

Adds release notes and documentation updates for Magento Cloud Docker 1.2.0 release.

## Affected DevDocs pages

## Links to Magento source code

-  ...

2020-11-06 22:02 UTC, meker12 commented on src/cloud/docker/docker-quick-reference.md
> +Docker Compose is a tool for defining and running multi-container Docker applications. The following table lists the Docker Compose commands for building, deploying, and operating {{site.data.var.mcd
```suggestion
Docker Compose is a tool for defining and running multi-container Docker applications. The following table lists the `docker-compose` commands for building, deploying, and operating {{site.data.var.mcd-prod}}. You can also use [Magento Cloud Docker CLI](#magento-cloud-docker-cli) commands to complete Docker Compose tasks.
```

2020-11-07 13:02 UTC, meker12 commented on src/cloud/release-notes/mcd-release-notes.md
> +      -  **Run commands inside Docker PHP containers**–Now you can use the Magento Cloud Docker CLI to run commands inside PHP containers in your Docker environment without having to install PHP on t
```suggestion
      -  **Run commands inside Docker PHP containers**–Now you can use the Magento Cloud Docker CLI to run commands inside PHP containers in your Docker environment without having to install PHP on the host. For example, the following command builds the configuration:  `./bin/magento-docker php 7.3 vendor/bin/ece-docker build:compose`. See [Magento Cloud Docker CLI]({{ site.baseurl }}/cloud/docker/docker-quick-refere.html#magento-cloud-docker-cli). *[Fix submitted by G Arvind from Zilker Technology](https://github.com/magento/magento-cloud-docker/pull/209).*<!--MCLOUD-5982-->
```

2020-11-07 13:25 UTC, meker12 commented on src/cloud/release-notes/mcd-release-notes.md
> +      -  **Run commands inside Docker PHP containers**–Now you can use the Magento Cloud Docker CLI to run commands inside PHP containers in your Docker environment without having to install PHP on t
```suggestion
      -  **Run commands inside Docker PHP containers**–Now you can use the Magento Cloud Docker CLI to run commands inside PHP containers in your Docker environment without having to install PHP on the host. For example, the following command builds the configuration:  `./bin/magento-docker php 7.3 vendor/bin/ece-docker build:compose`. See [Magento Cloud Docker CLI]({{ site.baseurl }}/cloud/docker/docker-quick-reference.html#magento-cloud-docker-cli). *[Fix submitted by G Arvind from Zilker Technology](https://github.com/magento/magento-cloud-docker/pull/209).*<!--MCLOUD-5982-->
```

2020-11-09 14:40 UTC, andriyShevtsov commented
QA approved

2020-11-09 14:41 UTC, meker12 commented on src/cloud/docker/docker-quick-reference.md
> +./vendor/bin/ece-docker build:custom:compose '{"name":"magento","system":{"mode":"production","host":"magento2.test","port":"8080","db":{"increment_increment":3,"increment_offset":2},"mailhog":{"smtp
```suggestion
./vendor/bin/ece-docker build:custom:compose '{"name":"magento","system":{"mode":"production","host":"magento2.test","port":"8080","db":{"increment_increment":3,"increment_offset":2},"mailhog":{"smtp_port":"1026","http_port":"8026"}},"services":{"php":{"version":"7.3","enabled":true,"extensions":{"enabled":["xsl"]}},"mysql":{"version":"10.2","image":"mariadb","enabled":true}, "mailhog": {"enabled":true}}}'
```

2020-11-09 14:41 UTC, meker12 commented on src/cloud/docker/docker-quick-reference.md
> +For {{site.data.var.mcd-prod}} 1.2 and later, you have an additional option to specify custom images and image versions using the `ece-docker build:custom:compose` command.
```suggestion
```

2020-11-09 15:06 UTC, hguthrie requested changes
A few problems I noted. Also not part of your changes, but I noticed Line 180 of containers topic (selenium) looks like it has a broken link. I think it needs a closing paren.

2020-11-09 15:06 UTC, hguthrie commented on src/cloud/release-notes/mcd-release-notes.md
> +   -  {:.new}**Test container**–Added a test container for Magento application testing and added the `--with-test` option to the Docker `build:compose` command to create the container only when testi
```suggestion
   -  {:.new}**Test container**–Added a test container for Magento application testing, and added the `--with-test` option to the Docker `build:compose` command to create the container only when testing Magento in the Docker environment. See [Magento application testing](https://devdocs.magento.com/cloud/docker/docker-test-app-mftf.html).<!--MCLOUD-6394-->
```

2020-11-09 15:06 UTC, hguthrie commented on src/cloud/release-notes/mcd-release-notes.md
> +   -  **Specify custom images and versions in custom Magento Cloud Docker configuration**service configuration  custom environment Updated the `build:custom:compose` command with options to specify c
Something is not finished in this entry. Spacing problems, misspelling of custom, and other issues. May need review, but I'll give it a go.

```suggestion
   -  **Specify custom images and versions in custom Magento Cloud Docker configuration**—Updated the `build:custom:compose` command with options to specify custom images and versions when generating a custom Docker compose configuration file (`docker-compose.yaml`). See [Build a custom Docker Compose configuration]({{ site.baseurl }}/cloud/docker/docker-quick-reference.html#build-a-custom-docker-compose-configuration). <!--MCLOUD-7089-->
```

2020-11-09 16:03 UTC, meker12 commented on src/cloud/docker/docker-quick-reference.md
> +### Build a custom Docker Compose configuration
Leaving for now

2020-11-09 16:28 UTC, meker12 commented on src/cloud/docker/docker-containers-service.md
> +**Docker base image**: [magento/magento-cloud-docker-php][php-cloud], which is based on the [php](https://hub.docker.com/_/php) Docker image<br/>
Handled inconsistently. Moved "based on ... Docker image" to the header info for all containers.

2020-11-09 16:39 UTC, hguthrie approved these changes
Ship it!

2020-11-09 17:01 UTC, merged