Issue-2916- Provide more info about file/classes in code snippets to adding-attributes.html
magento/devdocs pull request #8218
Opened 2020-11-12 09:49 UTC by dineshvb

## Purpose of this pull request

This pull request (PR) fixes #2916 

## Affected DevDocs pages

-  guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html

2020-11-12 15:31 UTC, BarnyShergold requested changes
The issue indicates there are a lot more problems with the concerned page than are covered by this PR - will you be adding more? What's the plan?

2020-11-12 15:31 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
> +Here, the scalar attributes indicate the simple form of attribute representation such as an Integer or a String. The class or interface for which the extension attributes must be added is specified i
(a unique is correct as unique starts with a consonant sound)
```suggestion
Here, the scalar attributes indicate the simple form of attribute representation such as an Integer or a String. The class or interface for which the extension attributes must be added is specified inside the "for" attribute of the `<extension_attributes>` tag. In this case, it is the ProductInterface. The attribute is specified with a unique code and its type.
```

2020-11-12 15:31 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
> +The array extension attributes are just an extension of the scalar attributes where a range of values can be represented as an attribute. `[]` symbol is used to indicate the type of the attribute as
```suggestion
The array extension attributes are just an extension of the scalar attributes where a range of values can be represented as an attribute. The `[]` symbol is used to indicate the type of the attribute as an array.
```

2020-11-13 06:17 UTC, dineshvb commented
Hi @BarnyShergold , I went through the https://devdocs.magento.com/guides/v2.4/extension-dev-guide/extension_attributes/adding-attributes.html page and after I got an understanding of the issue specified, I made these changes. I don't know how to proceed hereafter. I would like to have some suggestions. Can you assist me with this?

2020-11-17 11:24 UTC, BarnyShergold commented
@shrielenee - Some additional information to the section on your issue has been added by @dineshvb - Textually the additions are fine, can you take a look and feedback as to if there is enough new information or what might else be needed to clarify the examples as indicated in you report?

2020-11-17 15:29 UTC, keharper requested changes
Some grammatical changes.

2020-11-17 15:29 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
> +Here, the scalar attributes indicate the simple form of attribute representation such as an Integer or a String. The class or interface for which the extension attributes must be added is specified i
```suggestion
Here, the scalar attributes indicate the simple form of attribute representation, such as an integer or a string. Specify the class or interface of the extension attributes inside the "for" attribute of the `<extension_attributes>` tag. In this case, it is the ProductInterface. The attribute is specified with a unique code and its type.
```

2020-11-17 15:29 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
> +The array extension attributes are just an extension of the scalar attributes where a range of values can be represented as an attribute. The `[]` symbol is used to indicate the type of the attribute
```suggestion
The array extension attributes are just an extension of the scalar attributes where a range of values can be represented as an attribute. The `[]` symbol indicates the attribute type is an array.
```

2020-11-18 07:26 UTC, dineshvb commented
@keharper @BarnyShergold @dobooth Changed the base to master

2020-11-18 14:35 UTC, shrielenee commented
Agree with all @keharper comments. Thanks y'all!

2020-11-20 05:55 UTC, dineshvb commented
@shrielenee As @BarnyShergold said, I would like feedback on my changes so that I could proceed further

2020-11-23 23:54 UTC, BarnyShergold commented
Looks good so far.

2020-11-27 00:52 UTC, BarnyShergold approved these changes

2020-11-27 06:05 UTC, dineshvb commented
@keharper @dobooth Is it good to merge ?

2020-11-27 19:58 UTC, keharper approved these changes

2020-11-27 19:58 UTC, keharper commented
running tests

2020-11-27 20:16 UTC, merged