GraphQL: Document WishlistItemInterface
magento/devdocs pull request #8221
Opened 2020-11-12 21:55 UTC by keharper

## Purpose of this pull request

This pull request (PR) adds documentation for the WishlistItemInterface, which was created long ago and extended in https://github.com/magento/magento2/pull/29148.

It also includes updates from MC-37620

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2020-11-16 10:21 UTC, rogyar approved these changes

2020-12-09 17:05 UTC, prabhuram93 requested changes

2020-12-09 17:05 UTC, prabhuram93 commented on src/guides/v2.4/graphql/mutations/delete-wishlist.md
> +    status
Can also highlight the remaining wishlists which will be returned.

2020-12-15 19:04 UTC, erikmarr approved these changes
Looks good.

2020-12-15 19:08 UTC, prabhuram93 approved these changes
Looks good @keharper!

2020-12-22 16:56 UTC, keharper commented
running tests

2020-12-22 18:02 UTC, keharper commented
running tests

2020-12-22 18:23 UTC, merged