Issue 7580 add details to define graphql schema
magento/devdocs pull request #8232
Opened 2020-11-17 11:48 UTC by sathiyaaa

## Purpose of this pull request

This pull request (PR) covers #7580 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/graphql/develop/create-graphqls-file.html
-  https://devdocs.magento.com/guides/v2.3/graphql/develop/create-graphqls-file.html

2020-11-17 13:06 UTC, BarnyShergold requested changes
Nice piece of work!

2020-11-17 13:06 UTC, BarnyShergold commented on src/guides/v2.4/graphql/develop/create-graphqls-file.md
> +The search returns 45 items, but only the first two items are returned on the current page and all the information regarding the page is returned.
Same question as earlier

2020-11-17 13:06 UTC, BarnyShergold commented on src/guides/v2.4/graphql/develop/create-graphqls-file.md
> +The following example shows the `products` query. The `page_info` attribute contains the `SearchResultPageInfo` data type which is defined in the `schema.graphqls` file under `ModuleGraphQl`. In othe
```suggestion
The following example shows the `products` query. The `page_info` attribute contains the `SearchResultPageInfo` data type which is defined in the `schema.graphqls` file under `ModuleGraphQl`. In other use cases, you would be required to create your own output type in the `<magento_root>/app/code/<vendor_name>/<module_name>/etc/schema.graphqls` file.
```

2020-11-17 13:06 UTC, BarnyShergold commented on src/guides/v2.4/graphql/develop/create-graphqls-file.md
> +`filters` | LayerFilter | Deprecated. Use `aggregations` instead
```suggestion
`filters` | LayerFilter | **Deprecated.** Use `aggregations` instead
```

2020-11-17 13:13 UTC, sathiyaaa commented on src/guides/v2.3/graphql/develop/create-graphqls-file.md
> +The search returns 45 items, but only the first two items are returned on the current page and all the information regarding the page is returned.
No, `total_count` is basically the total number of products that match the particular search criteria. If there is only one product which matches the search criteria then `page_size` would be 1 and the `total_count` would also be 1

2020-11-17 13:36 UTC, sathiyaaa commented on src/guides/v2.3/graphql/develop/create-graphqls-file.md
> +The search returns 45 items, but only the first two items are returned on the current page and all the information regarding the page is returned.
![rsz_page_size](https://user-images.githubusercontent.com/50226394/99396547-e47f7400-2907-11eb-85d3-4b671289521a.png)

2020-11-17 13:38 UTC, BarnyShergold approved these changes
Excellent!

2020-11-30 03:35 UTC, keharper approved these changes

2020-11-30 03:35 UTC, keharper commented
running tests

2020-11-30 03:54 UTC, keharper commented
running tests

2020-11-30 04:22 UTC, keharper commented
running tests

2020-11-30 04:38 UTC, merged