MCLOUD-6073: Review "Update the metapackage" devdocs which is confusing merchants and support agents
magento/devdocs pull request #8236
Opened 2020-11-18 04:12 UTC by NadiyaS

## Purpose of this pull request

https://jira.corp.magento.com/browse/MCLOUD-6073

## Affected DevDocs pages

-  src/cloud/project/ece-tools-upgrade-project.md

## Links to Magento source code

-  ...

2020-11-18 09:55 UTC, swnsma approved these changes

2020-11-18 10:55 UTC, BarnyShergold requested changes

2020-11-18 15:16 UTC, NadiyaS commented on src/cloud/project/ece-tools-upgrade-project.md
> +If you want to install Magento `2.3.5-p2` you still should set `current_version` as `2.3.5` and constraint `">=2.3.5 <2.3.6"` will install the latest available package for 2.3.5
@BarnyShergold Sometimes, we have `-px` releases even in cloud metapackages, that is why we still recommend to use that constraint. Probably, we need to mention this in documentation.

2020-11-23 16:22 UTC, meker12 requested changes

2020-11-23 16:22 UTC, meker12 commented on src/cloud/project/ece-tools-upgrade-project.md
> +and `next_version` is the next patch version after your `current_version`.
```suggestion
-  For `current_version`, specify the Magento version to install.
-  For `next_version`, specify the next patch version after the value specified in `current_version`.
```

2020-11-23 16:22 UTC, meker12 commented on src/cloud/project/ece-tools-upgrade-project.md
> +If you want to install Magento `2.3.5-p2` you still should set `current_version` as `2.3.5` and constraint `">=2.3.5 <2.3.6"` will install the latest available package for 2.3.5
```suggestion
If you want to install Magento `2.3.5-p2`, you still set `current_version` to `2.3.5` and the `next_version` to `2.3.6`. The constraint `">=2.3.5 <2.3.6"` installs the latest available package for 2.3.5.
```

2020-11-23 23:52 UTC, BarnyShergold commented on src/cloud/project/ece-tools-upgrade-project.md
> +If you want to install Magento `2.3.5-p2` you still should set `current_version` as `2.3.5` and constraint `">=2.3.5 <2.3.6"` will install the latest available package for 2.3.5
Yes, but as this is in the Metapackage - ">=2.3.4 <2.3.5" it would pick up the latest -px release and install?

2020-11-30 15:49 UTC, NadiyaS commented on src/cloud/project/ece-tools-upgrade-project.md
> +If you want to install Magento `2.3.5-p2` you still should set `current_version` as `2.3.5` and constraint `">=2.3.5 <2.3.6"` will install the latest available package for 2.3.5
@BarnyShergold 
sorry, did not get your question.
if you set `"magento/magento-cloud-metapackage": "2.3.5"` in composer.json but we released 2.3.5-p1 version - you still will have correct version of EE, but you won't have necessary changes in `magento/magento-cloud-metapackage`. E.g. we may change constraint for other packages like `magento/module-paypal-on-boarding` or add new package. That is why we strongly recommend to use constraint as `"magento/magento-cloud-metapackage": ">=2.3.5 <2.3.6"`

2020-11-30 16:18 UTC, meker12 approved these changes

2020-11-30 16:24 UTC, merged