MC-38903: Add more graphic example how new image resizing works
magento/devdocs pull request #8243
Opened 2020-11-18 19:20 UTC by shiftedreality

## Purpose of this pull request

https://jira.corp.magento.com/browse/MC-38903

2020-11-18 19:34 UTC, BarnyShergold requested changes
Please also add a description of the MC-38903 ticket to this PR as non-Adobe reviewers have no access to this JIRA

2020-11-18 19:34 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/remote-storage/config-remote-storage-caching.md
> +Remote storage provide a cache layer for external API calls. The caching is based on [Flysytem cache] provided adapters.
```suggestion
Remote storage provides a cache layer for external API calls. The caching is based on [Flysystem cache] provided adapters.
```

2020-11-18 19:34 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/remote-storage/config-remote-storage-caching.md
> +Memory cache is enabled by default and provides per-request cache.
```suggestion
Memory cache is enabled by default and provides per request cache.
```

2020-11-18 19:34 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/remote-storage/config-remote-storage-caching.md
> +A persistent cache stored in Redis and requires an active Redis service and additional configuration
```suggestion
A persistent cache stored in Redis that requires an active Redis service and additional configuration
```

2020-11-18 19:34 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/remote-storage/config-remote-storage-caching.md
> +To use Redis cache with [predis/predis] extension, perform next steps:
```suggestion
To use Redis cache with [predis/predis] extension, perform the next steps:
```

2020-11-18 19:34 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/remote-storage/config-remote-storage-caching.md
> +2. Add a configuration to `app/etc/env.php` file:
```suggestion
2. Add a configuration to the `app/etc/env.php` file:
```

2020-11-18 19:34 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/remote-storage/config-remote-storage-caching.md
> +[Flysytem cache]: https://flysystem.thephpleague.com/v1/docs/advanced/caching
```suggestion
[Flysystem cache]: https://flysystem.thephpleague.com/v1/docs/advanced/caching
```

2020-11-19 16:15 UTC, hguthrie commented
I have made some significant edits to the remote storage content, which has already been rebased with 2.4.2-develop. I will take your new content from this PR and roll it into that branch. This PR will be closed when that is complete.

2020-11-19 19:24 UTC, closed without merging