Update directory-currency.md
magento/devdocs pull request #8300
Opened 2020-12-02 05:14 UTC by RakeshJesadiya

Directory Currency GraphQL with Multiple currency as the response. How Base currency and other currency of the store will be response of the query.

## Purpose of this pull request

An Example for the multi currency store such as USD and EURO.

2020-12-02 10:02 UTC, BarnyShergold requested changes
Please update PR description to the required format and information. A good example : https://github.com/magento/devdocs/pull/8296

2020-12-02 10:02 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/directory-currency.md
> +The following query returns the currency for the current instance of Magento with multiple currency such as USD and EURO. Default(Base) Currency for the store is US Dollar(USD). GraphQL query will be
```suggestion
The following query returns the currency for the current instance of Magento with multiple currencies such as USD and EURO. The default(base) currency for the store is US Dollar(USD). The GraphQL query will be same , but the response will be different based on the available currency. A list of arrays of the currency will be displayed in the `available_currency_codes` attribute while the `exchange_rates` attribute contains the array of `currency_to` and rate value for the respective currency.
```

2020-12-02 16:12 UTC, RakeshJesadiya commented
@BarnyShergold I have updated the Comment and PR. Thank you for your suggestion.

2020-12-02 16:14 UTC, BarnyShergold requested changes
Not sure how that crept in... All good after

2020-12-02 16:14 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/directory-currency.md
> +The following query returns the currency for the current instance of Magento with multiple currencies such as USD and EURO. The default(base) currency for the store is US Dollar(USD). The GraphQL que
```suggestion
The following query returns the currency for the current instance of Magento with multiple currencies such as USD and EURO. The default(base) currency for the store is US Dollar(USD). The GraphQL query will be same, but the response will be different based on the available currency. A list of arrays of the currency will be displayed in the `available_currency_codes` attribute while the `exchange_rates` attribute contains the array of `currency_to` and rate value for the respective currency.
```

2020-12-03 04:39 UTC, RakeshJesadiya commented
@BarnyShergold I have update the code based on your suggestion. Thanks.

2020-12-04 18:23 UTC, keharper approved these changes

2020-12-04 18:27 UTC, keharper commented
I deleted the original example, because there's no need to show one query doing the same thing twice, and your example was better.

2020-12-04 18:32 UTC, merged