Update directory-country.md
magento/devdocs pull request #8301
Opened 2020-12-02 05:34 UTC by RakeshJesadiya

Differentiate Country and Countries object with GraphQL Query.

2020-12-02 10:06 UTC, BarnyShergold requested changes
Please update PR description to the required format and information. A good example : https://github.com/magento/devdocs/pull/8296

2020-12-02 10:06 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/directory-country.md
> +Use the `country` query to retrieve information about a specific country. Dont confuse with [countries]({{page.baseurl}}/graphql/queries/directory-countries.html) query that will be used to retrieve
```suggestion
Use the `country` query to retrieve information about a specific country. Do not confuse with [countries]({{page.baseurl}}/graphql/queries/directory-countries.html) query that will be used to retrieve list of all the available countries in the system.
```

2020-12-02 10:06 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/directory-country.md
> +The following query returns information about Australia. You must have to pass `id` as two-letter abbreviation of the country to retrieve country detalis.
```suggestion
The following query returns information about Australia. You must pass `id` as a two-letter abbreviation of the country to retrieve country details.
```

2020-12-02 16:08 UTC, RakeshJesadiya commented
@BarnyShergold Thank you for the suggestion. I have updated the details.

2020-12-02 16:11 UTC, BarnyShergold requested changes
Apologies - I missed 2 small corrections.
All good after these.

2020-12-02 16:11 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/directory-country.md
> +Use the `country` query to retrieve information about a specific country. Do not confuse with [countries]({{page.baseurl}}/graphql/queries/directory-countries.html) query that will be used to retriev
```suggestion
Use the `country` query to retrieve information about a specific country. Do not confuse with the [countries]({{page.baseurl}}/graphql/queries/directory-countries.html) query that will be used to retrieve a list of all the available countries in the system.
```

2020-12-02 16:28 UTC, RakeshJesadiya commented
@BarnyShergold No Problem, I have corrected that also. Thanks.

2020-12-02 17:13 UTC, BarnyShergold approved these changes
Excellent!

2020-12-03 17:40 UTC, hguthrie requested changes
Thanks for the contribution. Here are some grammatical fixes.

2020-12-03 17:40 UTC, hguthrie commented on src/guides/v2.3/graphql/queries/directory-country.md
> +Use the `country` query to retrieve information about a specific country. Do not confuse with the [countries]({{page.baseurl}}/graphql/queries/directory-countries.html) query that will be used to ret
```suggestion
Use the `country` query to retrieve information about a specific country. The [countries]({{page.baseurl}}/graphql/queries/directory-countries.html) query is used to retrieve a list of countries available in the system.
```

2020-12-03 17:40 UTC, hguthrie commented on src/guides/v2.3/graphql/queries/directory-country.md
> +The following query returns information about Australia. You must pass `id` as a two-letter abbreviation of the country to retrieve country details.
```suggestion
The following query uses a two-letter abbreviation for the country ID (id: "AU"), which returns information about Australia.
```

2020-12-04 05:15 UTC, RakeshJesadiya commented
@hguthrie @keharper I have updated the changes based on your suggestion. Thanks.

2020-12-04 18:33 UTC, keharper approved these changes

2020-12-04 20:54 UTC, merged