Update pickup-locations.md
magento/devdocs pull request #8308
Opened 2020-12-03 08:35 UTC by RakeshJesadiya

Modify Response for the pickup location with no result found, Explain Search Term attribute field.

## Purpose of this pull request

This pull request (PR) contains response for the pickup location with no result found. Search term in the pickup location query definition updated.You must have to pass two-letter country code to get actual result otherwise it will throws an error.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/graphql/queries/pickup-locations.html

2020-12-03 10:32 UTC, BarnyShergold requested changes

2020-12-03 10:32 UTC, BarnyShergold commented on src/guides/v2.4/graphql/queries/pickup-locations.md
> +For the available Pick Up location, The Response would be looks like.
```suggestion
For the available Pickup location, the response would look like:
```

2020-12-03 10:32 UTC, BarnyShergold commented on src/guides/v2.4/graphql/queries/pickup-locations.md
> +If Pickup location will not available for the given search term, The Response will be emtpy,
```suggestion
If the Pickup location is not available for the given search term, the response will be empty:
```

2020-12-03 10:32 UTC, BarnyShergold commented on src/guides/v2.4/graphql/queries/pickup-locations.md
> +`search_term` | String! | A combination of either the region, city, or postcode, a colon, and the country code. This value determines the location to use as the center of the search radius.  Valid Se
```suggestion
`search_term` | String! | A combination of either the region, city, or postcode, a colon, and the country code. This value determines the location to use as the center of the search radius.  Valid search term - `Texas:US`|`Austin:US`|`78740:US`. After the colon, the two-letter Country code is required to be passed in uppercase.
```

2020-12-03 12:25 UTC, RakeshJesadiya commented
@BarnyShergold I have made update based on your suggestion. Thanks.

2020-12-03 13:39 UTC, BarnyShergold approved these changes
Excellent!

2020-12-03 17:47 UTC, keharper requested changes

2020-12-03 17:47 UTC, keharper commented on src/guides/v2.4/graphql/queries/pickup-locations.md
> +```
We don't need to show an empty response. Remove all of your additions up to here.

2020-12-03 17:47 UTC, keharper commented on src/guides/v2.4/graphql/queries/pickup-locations.md
> +`search_term` | String! | A combination of either the region, city, or postcode, a colon, and the country code. This value determines the location to use as the center of the search radius.  Valid se
I'm not sure what you're trying to say here. Those | symbols can't be in a markdown table. 

Perhaps reword to 

Valid search terms include `Texas:US`, `Austin:US`, and `78740:US`. The two-letter country code must be uppercase

2020-12-04 05:07 UTC, RakeshJesadiya commented
@keharper I have updated the docs based on your suggestion. Thank you.

2020-12-04 18:51 UTC, keharper approved these changes

2020-12-04 18:52 UTC, merged