Update category.md
magento/devdocs pull request #8312
Opened 2020-12-03 13:02 UTC by RakeshJesadiya

Added Breadcrumb object Output attribute list.

## Purpose of this pull request

This pull request (PR) contains the additional Breadcrumb object Output attribute list. Page has given breadcrumb example but not defined breadcrumb attribute list.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/graphql/queries/category.html#Categories
https://devdocs.magento.com/guides/v2.4/graphql/queries/category.html#Categories

2020-12-03 13:37 UTC, BarnyShergold requested changes
Nice addition - just formatting issue

2020-12-03 13:37 UTC, BarnyShergold commented on src/guides/v2.4/graphql/queries/category.md
> +`category_id` | `Int` | Category ID
On these types of tables, Data Types are not enclosed in quotes.

2020-12-03 13:55 UTC, RakeshJesadiya commented
@BarnyShergold I have updated the suggested changes.

2020-12-04 19:50 UTC, keharper commented
The `category` query has been deprecated and replaced twice, so I don't want to spend much time maintaining it. The docs are correct in that the output is a `CategoryTree` object, which is an implementation of `CategoryInterface`. The docs link to `CategoryInterface`.  I do the exact same thing for the newer `categoryList` query, and this is intentional. So, I'm closing this PR.

2020-12-04 19:50 UTC, closed without merging