Update category-list.md
magento/devdocs pull request #8313
Opened 2020-12-03 13:21 UTC by RakeshJesadiya

Devdocs improvement with example of url_key and url_path attribute with categoryList query.

## Purpose of this pull request

This pull request (PR) describe the more live example of the url_key and url_path attribute with categoryList query. Example for the ids and name attribute available. This will be helpful for the user to get all the available example demo to learn categoryList query.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/graphql/queries/category-list.html
https://devdocs.magento.com/guides/v2.4/graphql/queries/category-list.html

2020-12-03 13:44 UTC, BarnyShergold requested changes
Nice additions.- just some grammar corrections.

2020-12-03 13:44 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/category-list.md
> +The following query returns information about category by url_key filters. You have to pass url_key value without suffix with `eq` or `in` keyword. Get the categoryList response from the `Gear` categ
```suggestion
The following query returns information about categories by `url_key` filters. You have to pass the `url_key` value without a suffix and with either the `eq` or `in` keywords. Get the categoryList response from the `Gear` category.
```

2020-12-03 13:44 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/category-list.md
> +The following query returns information about category by url_path filters. You have to pass url_path value without suffix with `eq` or `in` keyword. Get the categoryList response from the `Gear -> B
```suggestion
The following query returns information about categories by `url_path` filters. You have to pass the `url_path` value without a suffix and with either the `eq` or `in` keywords. Get the categoryList response from the `Gear -> Bags` category.
```

2020-12-03 13:58 UTC, RakeshJesadiya commented
@BarnyShergold I have updated the suggested changes. Thank you.

2020-12-04 20:27 UTC, keharper requested changes

2020-12-04 20:27 UTC, keharper commented on src/guides/v2.3/graphql/queries/category-list.md
> +The following query returns information about categories by `url_key` filters. You have to pass the `url_key` value without a suffix and with either the `eq` or `in` keywords. Get the categoryList re
```suggestion
The following query returns information about the Gear category using a `url_key` filter. You must pass the `url_key` value without a suffix and specify either the `eq` or `in` keyword.
```

2020-12-04 20:27 UTC, keharper commented on src/guides/v2.3/graphql/queries/category-list.md
> +The following query returns information about categories by `url_path` filters. You have to pass the `url_path` value without a suffix and with either the `eq` or `in` keywords. Get the categoryList
```suggestion
The following query returns information about the Gear > Bags` category using the `url_path` filter. Do not specify a suffix in the `url_path` value. The `url_path` filter accepts either the `eq` or `in` keyword.
```

2020-12-07 05:17 UTC, RakeshJesadiya commented
@keharper I have update the docs as per your suggestion. Thank you.

2020-12-08 13:37 UTC, keharper approved these changes

2020-12-08 13:38 UTC, merged