Update customizable-option-interface.md
magento/devdocs pull request #8328
Opened 2020-12-04 13:21 UTC by RakeshJesadiya

Added Example of the Custom option type text field.

## Purpose of this pull request

This pull request (PR) contains the exact demo of the custom option with text field type. In the article one of the example is given but its basic example but not configured with the customizable option type case. I have added demo for the Custom option type Text field.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/graphql/interfaces/customizable-option-interface.html

2020-12-04 16:29 UTC, BarnyShergold requested changes
Just some formatting suggestions to make values stand out

2020-12-04 16:29 UTC, BarnyShergold commented on src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
> +The following query returns information about the customizable options configured for the product with a `sku` of `xyz` with Custom Option type Text Field.
Need a blank line after this one and before the list to correct Linting error

2020-12-04 16:29 UTC, BarnyShergold commented on src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
> +- Option Title is Favorite Color.
```suggestion
- Option Title is `Favorite Color`.
```

2020-12-04 16:29 UTC, BarnyShergold commented on src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
> +- Price is $5, Price Type is Fixed, Option SKU favoriteColorSku and Max. Characters is 20.
```suggestion
- Price is `$5`, Price Type is `Fixed`, Option SKU is `favoriteColorSku` and Max. Characters is `20`.
```

2020-12-05 14:13 UTC, rogyar requested changes

2020-12-05 14:13 UTC, rogyar commented on src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
> +            textField: value {
I believe that the "textField" definition here might not be passed by the Webonyx validator (the example #2 is still correct). Also, please not that the response does not correspond the request after extending of this example.

Thanks

2020-12-07 05:29 UTC, RakeshJesadiya commented
@rogyar @BarnyShergold I have updated changes as per your suggestion respectively. Thank you.

2020-12-07 09:41 UTC, BarnyShergold requested changes
Need to correct linting error

2020-12-07 09:41 UTC, BarnyShergold commented on src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
> +- Custom option Option Type is text field with required field.
I saw that you were still getting Linting errors and I checked the rest of the file. The problem is that there is a list earlier in the file with style -
*  Text area
*  Checkbox
*  Date picker

You can only have one list style per file, so you need to change your list to use asterisks

2020-12-07 09:51 UTC, RakeshJesadiya commented
@BarnyShergold I have updated the changes as per your suggestions. Thanks.

2020-12-10 03:10 UTC, keharper approved these changes

2020-12-12 04:18 UTC, merged