product-interface-dynamic-links-mapping
magento/devdocs pull request #8342
Opened 2020-12-07 06:12 UTC by RakeshJesadiya

Mapping Dynamic links to the all the product interface, Customizable product interface and physical product interface.

## Purpose of this pull request

This pull request (PR) update the bulk of product related pages to update dynamic links on the all types of pages where static interface declared for the product, Customizable product and physical product interface.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/graphql/interfaces/bundle-product.html
https://devdocs.magento.com/guides/v2.4/graphql/interfaces/bundle-product.html

2020-12-07 06:56 UTC, aleron75 approved these changes

2020-12-08 06:39 UTC, keharper requested changes
I don't know if you're doing this already, but be sure to run `rake` in the devdocs root directory to make sure that all links resolve.

2020-12-08 06:39 UTC, keharper commented on src/guides/v2.3/graphql/interfaces/downloadable-product.md
> +### DownloadableProductSamples object {#downloadableProductSamples}
Capitalize the "D" and update all references to the anchor.

2020-12-08 06:39 UTC, keharper commented on src/guides/v2.3/graphql/interfaces/downloadable-product.md
> +### DownloadableProductLinks object {#downloadableProductLinks}
Same here.

2020-12-08 06:39 UTC, keharper commented on src/guides/v2.3/graphql/interfaces/product-interface-implementations.md
> +[GiftCardProduct]({{ page.baseurl }}/graphql/interfaces/gift-card-product.html) | [ProductInterface]({{ page.baseurl }}/graphql/interfaces/product-interface.html),  [PhysicalProductInterface]({{ page
Alphabetize this row

2020-12-08 06:39 UTC, keharper commented on src/guides/v2.3/graphql/interfaces/product-interface.md
> +   -  [GiftCardProduct]({{ page.baseurl }}/graphql/interfaces/gift-card-product.html)
Alphabetize

2020-12-08 06:39 UTC, keharper commented on src/guides/v2.4/graphql/interfaces/downloadable-product.md
> +### DownloadableProductSamples object {#downloadableProductSamples}
Capitalize the D

2020-12-08 06:39 UTC, keharper commented on src/guides/v2.4/graphql/interfaces/downloadable-product.md
> +### DownloadableProductLinks object {#downloadableProductLinks}
Capitalize

2020-12-08 06:39 UTC, keharper commented on src/guides/v2.4/graphql/interfaces/product-interface-implementations.md
> +[GiftCardProduct]({{ page.baseurl }}/graphql/interfaces/gift-card-product.html) | [ProductInterface]({{ page.baseurl }}/graphql/interfaces/product-interface.html),  [PhysicalProductInterface]({{ page
Alphabetize

2020-12-08 06:48 UTC, RakeshJesadiya commented
@keharper I have updated the changes as per your suggestion. thanks.

2020-12-08 13:29 UTC, keharper requested changes

2020-12-08 13:29 UTC, keharper commented on src/guides/v2.3/graphql/interfaces/downloadable-product.md
> +### DownloadableProductSamples object {#downloadableProductSamples}
You missed this one. Also, you introduced an error in line 18 by linking to the wrong location.

2020-12-08 13:29 UTC, keharper commented on src/guides/v2.4/graphql/interfaces/downloadable-product.md
> +### DownloadableProductSamples object {#downloadableProductSamples}
Same problem as the 2.3 version of the file

2020-12-09 05:03 UTC, RakeshJesadiya commented
@keharper I have updated the PR based on your suggestion. Thanks.

2020-12-09 05:22 UTC, keharper approved these changes

2020-12-09 05:25 UTC, keharper commented
running tests

2020-12-09 05:45 UTC, merged