Product Recommendations release notes for 3.2.0
magento/devdocs pull request #8350
Opened 2020-12-07 20:21 UTC by erikmarr

## Purpose of this pull request

This pull request (PR) updates the release notes for product recommendations 3.2.0.

## Affected DevDocs pages

-  https://devdocs.magento.com/recommendations/release-notes.html

2020-12-08 23:07 UTC, misha-kotov requested changes

2020-12-08 23:07 UTC, misha-kotov commented on src/_data/mde.yml
> +        name: 3.2.0
```suggestion
        name: 3.2.1
```

2020-12-08 23:07 UTC, misha-kotov commented on src/recommendations/release-notes.md
> +-  {:.new}Added the ability to [resync your catalog to SaaS services from the Admin](https://docs.magento.com/user-guide/system/catalog-sync.html)
```suggestion
-  {:.new}Added the ability to [monitor and manage](https://docs.magento.com/user-guide/system/catalog-sync.html) the catalog sync process from the Admin Panel. 
```

2020-12-08 23:07 UTC, misha-kotov commented on src/recommendations/release-notes.md
> +-  {:.new}Added the ability to specify [inclusion and exclusion filters](https://docs.magento.com/user-guide/marketing/recommendation-incl-excl.html) for your recommendations.
```suggestion
-  {:.new}Added [inclusion and exclusion filters](https://docs.magento.com/user-guide/marketing/recommendation-incl-excl.html) to control what products can and cannot show up in recommendations.
```

2020-12-08 23:08 UTC, misha-kotov commented on src/recommendations/release-notes.md
> +## 1.2.0 of magento/module-page-builder-product-recommendations for Page Builder for Magento Commerce 2.4.0 and later
```suggestion
## 1.2.1 of magento/module-page-builder-product-recommendations for Page Builder for Magento Commerce 2.4.0 and later
```

2020-12-09 15:12 UTC, keharper approved these changes

2020-12-09 15:21 UTC, erikmarr commented
running tests

2020-12-09 15:37 UTC, merged