Wishlist error message
magento/devdocs pull request #8362
Opened 2020-12-09 12:10 UTC by RakeshJesadiya

## Purpose of this pull request

This pull request (PR) indicated the Error Message for the invalid Request payload on Add Product, Update Product and Remove Product to the wishlist.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-wishlist.html
https://devdocs.magento.com/guides/v2.4/graphql/mutations/update-products-in-wishlist.html
https://devdocs.magento.com/guides/v2.4/graphql/mutations/remove-products-from-wishlist.html

2020-12-10 17:07 UTC, BarnyShergold requested changes
just a few grammatical issues

2020-12-10 17:07 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/add-products-to-wishlist.md
> +`The current user cannot perform operations on wishlist` | An unauthorized user (guest) tried to add a item to wishlist, or an authorized user (customer) tried to add a item to wishlist of another cu
```suggestion
`The current user cannot perform operations on wishlist` | An unauthorized user (guest) tried to add an item to a wishlist, or an authorized user (customer) tried to add an item to a wishlist belonging to another customer.
```

2020-12-10 17:07 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/add-products-to-wishlist.md
> +`The wishlist was not found.` | Provided field `wishlistId` is invalid or not exists for the customer.
```suggestion
`The wishlist was not found.` | Provided field `wishlistId` is invalid or does not exist for the customer.
```

2020-12-10 17:07 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/remove-products-from-wishlist.md
> +`The current user cannot perform operations on wishlist` | An unauthorized user (guest) tried to add a item to wishlist, or an authorized user (customer) tried to add a item to wishlist of another cu
```suggestion
`The current user cannot perform operations on wishlist` | An unauthorized user (guest) tried to add an item to a wishlist, or an authorized user (customer) tried to add an item to a wishlist of another customer.
```

2020-12-10 17:07 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/remove-products-from-wishlist.md
> +`The wishlist was not found.` | Provided field `wishlistId` is invalid or not exists for the customer.
```suggestion
`The wishlist was not found.` | Provided field `wishlistId` is invalid or does not exist for the customer.
```

2020-12-10 17:07 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/update-products-in-wishlist.md
> +`The current user cannot perform operations on wishlist` | An unauthorized user (guest) tried to add a item to wishlist, or an authorized user (customer) tried to add a item to wishlist of another cu
```suggestion
`The current user cannot perform operations on wishlist` | An unauthorized user (guest) tried to add an item to a wishlist, or an authorized user (customer) tried to add an item to a wishlist of another customer.
```

2020-12-10 17:07 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/update-products-in-wishlist.md
> +`The wishlist was not found.` | Provided field `wishlistId` is invalid or not exists for the customer.
```suggestion
`The wishlist was not found.` | Provided field `wishlistId` is invalid or does not exist for the customer.
```

2020-12-11 05:19 UTC, RakeshJesadiya commented
@BarnyShergold Fixed the suggested changes. Thank you.

2020-12-11 09:21 UTC, BarnyShergold approved these changes
Excellent - thank you

2020-12-11 20:48 UTC, keharper approved these changes

2020-12-11 20:49 UTC, keharper commented
running tests

2020-12-11 21:16 UTC, merged