Update web-api-functional-testing.md
magento/devdocs pull request #8368
Opened 2020-12-10 13:02 UTC by RakeshJesadiya

Added phpunit_rest.xml Web API functional test.

## Purpose of this pull request

This pull request (PR) added command for the phpunit_rest.xml.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/get-started/web-api-functional-testing.html
https://devdocs.magento.com/guides/v2.4/get-started/web-api-functional-testing.html

2020-12-10 16:58 UTC, BarnyShergold requested changes
You have some linting errors - trailing spaces.

2020-12-10 16:58 UTC, BarnyShergold commented on src/guides/v2.3/get-started/web-api-functional-testing.md
> +    ```bash
```suggestion
   ```bash
```

2020-12-11 05:12 UTC, RakeshJesadiya commented
@BarnyShergold Fixed the linting errors. Please check again. Thanks.

2020-12-11 09:23 UTC, BarnyShergold commented
You are still getting linting errors -
src/guides/v2.3/get-started/web-api-functional-testing.md:114: MD009 Trailing spaces
src/guides/v2.3/get-started/web-api-functional-testing.md:116: MD009 Trailing spaces
src/guides/v2.3/get-started/web-api-functional-testing.md:118: MD009 Trailing spaces
src/guides/v2.4/get-started/web-api-functional-testing.md:114: MD009 Trailing spaces
src/guides/v2.4/get-started/web-api-functional-testing.md:116: MD009 Trailing spaces
src/guides/v2.4/get-started/web-api-functional-testing.md:118: MD009 Trailing spaces

2020-12-11 20:10 UTC, keharper approved these changes

2020-12-11 20:11 UTC, keharper commented
running tests

2020-12-11 20:40 UTC, merged