Issue-8347 - added new product attribute documentation
magento/devdocs pull request #8395
Opened 2020-12-16 11:20 UTC by dineshvb

## Purpose of this pull request

This pull request (PR) covers #8347 

## Affected DevDocs pages

-  /videos/fundamentals/add-new-product-attribute.html

2021-01-14 13:25 UTC, BarnyShergold requested changes
Great addition! Just a few formatting & punctuation suggestions

2021-01-14 13:25 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +A product attribute of type multiselect or select will present selectable options to the user. These options may be added manually through the admin panel, or by upgrade script. The script process is
```suggestion
A product attribute of type multiselect or select will present selectable options to the user. These options may be added manually through the admin panel or by upgrade script. The script process is slightly different depending on whether the options are being added at the moment of attribute creation or whether the options are being added at a later time to an existing attribute.
```

2021-01-14 13:25 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +*  You want a set of options which can be modified, added, or deleted through the admin panel.
```suggestion
1.  You want a set of options which can be modified, added or deleted through the admin panel.
```

2021-01-14 13:25 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +*  You want a set of options which cannot be modified by a user through the admin panel, and which can only be changed through a future code push.
Change to numbered as each are referred to this way further down
```suggestion
1.  You want a set of options which cannot be modified by a user through the admin panel and which can only be changed through a future code push.
```

2021-01-14 13:25 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +In the case of use case 1 (an 'immutable' set of options), follow the above instructions ["Add a source model"](#AddSourceModel). You will create a model that contains and dynamically returns the att
```suggestion
For use case `1` (an 'immutable' set of options), follow the above instructions ["Add a source model"](#AddSourceModel). You will create a model that contains and dynamically returns the attribute's selectable options to the client.
```

2021-01-14 13:25 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +In use case 2 (a 'mutable' set of options), see ["EAV and extension attributes"]({{ site.baseurl }}/guides/v2.4/extension-dev-guide/attributes.html). Make sure to declare 'Magento\Eav\Model\Entity\At
```suggestion
For use case `2` (a 'mutable' set of options), see ["EAV and extension attributes"]({{ site.baseurl }}/guides/v2.4/extension-dev-guide/attributes.html). Make sure to declare 'Magento\Eav\Model\Entity\Attribute\Source\Table' as the value for the 'source' attribute option. This ensures that Magento will store options in the appropriate database table.
```

2021-01-14 13:25 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +
Would suggest enclosing the two array segments in ```php for formatting clarity

2021-01-14 13:25 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +   `$options = ['attribute_id' => null, 'values' => 'Option 1', 'Option 2', etc]];`
Would suggest enclosing the three code segments in ```php for formatting clarity

2021-01-15 10:09 UTC, BarnyShergold commented
@magento run all tests

2021-01-15 10:14 UTC, BarnyShergold requested changes
Please also check linting - it failed last time for some reason (not clear)

2021-01-15 10:14 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +```
```suggestion
```php
```

2021-01-15 10:14 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +```
```suggestion
```php
```

2021-01-15 10:14 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +```
```suggestion
```php
```

2021-01-15 10:14 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +```
```suggestion
```php
```

2021-01-15 10:14 UTC, BarnyShergold commented on src/_videos/fundamentals/add-new-product-attribute.md
> +```
```suggestion
```php
```

2021-01-20 10:05 UTC, dineshvb commented
Hi @BarnyShergold , is this good to be approved?

2021-01-20 10:18 UTC, BarnyShergold approved these changes

2021-01-20 10:48 UTC, dineshvb commented
Hi @rogyar , is this good to be approved?

2021-01-20 14:46 UTC, dobooth approved these changes

2021-01-20 14:47 UTC, dobooth commented
running tests

2021-01-20 15:09 UTC, merged