Update performing-searches.md
magento/devdocs pull request #8400
Opened 2020-12-17 10:29 UTC by RakeshJesadiya

Added Example of `in` and `nin` operator.

## Purpose of this pull request

This pull request (PR) demonstrate the example of `in` and `nin` operator for the search field query.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/rest/performing-searches.html
https://devdocs.magento.com/guides/v2.4/rest/performing-searches.html

2020-12-17 12:29 UTC, BarnyShergold requested changes
Just a few grammar and clarity suggestions - nice addition to the page

2020-12-17 12:29 UTC, BarnyShergold commented on src/guides/v2.3/rest/performing-searches.md
> +## Simple search using a in conditions type
```suggestion
## Simple search using an `in` conditions type
```

2020-12-17 12:29 UTC, BarnyShergold commented on src/guides/v2.3/rest/performing-searches.md
> +The following search finds all the products that are provided in the value field. Using `in` conditions type, you have to pass comma separated values to get in to the response.
```suggestion
The following search finds all the products that are provided in the value field. To use the `in` conditions type, you have to pass comma separated values to get in to the response.
```

2020-12-17 12:29 UTC, BarnyShergold commented on src/guides/v2.3/rest/performing-searches.md
> +The following search finds all the products that are provided in the value field. Using `in` conditions type, you have to pass comma separated values to get in to the response.
I'm not sure for "to get in to the response" if the in refers to the operator or just the word in? Can you reword "you have to pass comma separated values to get in to the response." - as the second half does not make clear sense in English grammar.

2020-12-17 12:29 UTC, BarnyShergold commented on src/guides/v2.3/rest/performing-searches.md
> +## Simple search using a nin conditions type
```suggestion
## Simple search using a `nin` conditions type
```

2020-12-17 12:29 UTC, BarnyShergold commented on src/guides/v2.3/rest/performing-searches.md
> +The following search finds all the products that are not in the value field. Using `nin` conditions type, you have to pass comma separated value to get in the response.
```suggestion
The following search finds all the products that are not in the value field. To use the `nin` conditions type, you have to pass comma separated value to get in the response.
```

2020-12-17 12:29 UTC, BarnyShergold commented on src/guides/v2.3/rest/performing-searches.md
> +The following search finds all the products that are not in the value field. Using `nin` conditions type, you have to pass comma separated value to get in the response.
Second half of sentence has same grammar issue as above - please can this be reworded?

2020-12-17 12:39 UTC, RakeshJesadiya commented
@BarnyShergold I have updated changes. Thank you.

2020-12-18 01:17 UTC, keharper commented
@RakeshJesadiya The topic provides a variety of examples, and I don't think we need more. I accepted the `in` example, but deleted the `nin` example.

2020-12-18 01:19 UTC, keharper approved these changes

2020-12-18 01:22 UTC, keharper commented
running tests

2020-12-18 01:49 UTC, merged