Update catalog.md
magento/devdocs pull request #8401
Opened 2020-12-17 10:41 UTC by RakeshJesadiya

Added Response of the Category creation.

## Purpose of this pull request

This pull request (PR) add the Response of the Category creation. After Hit Request payload, Response data will be displayed in the post.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/rest/modules/catalog.html
https://devdocs.magento.com/guides/v2.4/rest/modules/catalog.html

2020-12-17 12:39 UTC, BarnyShergold requested changes
Just a few small suggestions

2020-12-17 12:39 UTC, BarnyShergold commented on src/guides/v2.3/rest/modules/catalog.md
> +## Response
Needs blank line after title

2020-12-17 12:39 UTC, BarnyShergold commented on src/guides/v2.3/rest/modules/catalog.md
> +            "value": "Women category description"
```suggestion
            "value": "Women's category description"
```

2020-12-17 12:39 UTC, BarnyShergold commented on src/guides/v2.3/rest/modules/catalog.md
> +            "value": "Women meta title"
```suggestion
            "value": "Women's meta title"
```

2020-12-17 12:39 UTC, BarnyShergold commented on src/guides/v2.3/rest/modules/catalog.md
> +            "value": "Women meta keywords"
```suggestion
            "value": "Women's meta keywords"
```

2020-12-17 12:39 UTC, BarnyShergold commented on src/guides/v2.3/rest/modules/catalog.md
> +            "value": "Women meta description"
```suggestion
            "value": "Women's meta description"
```

2020-12-17 12:47 UTC, RakeshJesadiya commented
@BarnyShergold I have updated the changes.

2020-12-18 04:38 UTC, keharper commented
@RakeshJesadiya I think the example is poor, and changing "Women" to "Women's" isn't going to fix it.

Let's look at the example is trying to demonstrate. It's trying to create a new top-level category that looks suspiciously similar to the Women category in Luma. Luma doesn't need another "Women" or "Women's" category. But perhaps Luma could use a category called "Kids".

Here's the output of  `GET /V1/categories/20`, where 20 is the ID of the "Women" category.

```
{
  "id": 20,
  "parent_id": 2,
  "name": "Women",
  "is_active": true,
  "position": 2,
  "level": 2,
  "children": "21,22",
  "created_at": "2020-12-14 19:11:33",
  "updated_at": "2020-12-14 19:11:33",
  "path": "1/2/20",
  "available_sort_by": [],
  "include_in_menu": true,
  "custom_attributes": [
    {
      "attribute_code": "display_mode",
      "value": "PAGE"
    },
    {
      "attribute_code": "is_anchor",
      "value": "0"
    },
    {
      "attribute_code": "path",
      "value": "1/2/20"
    },
    {
      "attribute_code": "children_count",
      "value": "8"
    },
    {
      "attribute_code": "url_key",
      "value": "women"
    },
    {
      "attribute_code": "url_path",
      "value": "women"
    }
  ]
}
```

Create a new example that defines a new category. Use the output above a source of inspiration. You probably want to include the `url_key` and `url_path` attribute codes. Maybe you can think of a few more that would be interesting. Make the example look real.

2020-12-18 08:54 UTC, RakeshJesadiya commented
@keharper I have updated the changes and add new category called Kids.

2020-12-18 22:14 UTC, keharper approved these changes

2020-12-18 23:03 UTC, keharper commented
running tests

2020-12-18 23:24 UTC, merged