Update proxies.md
magento/devdocs pull request #8402
Opened 2020-12-17 13:00 UTC by RakeshJesadiya

Example of the declare proxy class from the core code.

## Purpose of this pull request

This pull request (PR) adds the live example of how to add proxy class using di.xml file in Magento 2.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/proxies.html
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/proxies.html

2020-12-17 20:10 UTC, hguthrie requested changes

2020-12-17 20:10 UTC, hguthrie commented on src/guides/v2.3/extension-dev-guide/proxies.md
> +```xml
Your proposed addition requires some formatting fixes, including inserting a line before the XML snippet. I suggest the following to help with clarification, but will still need verification.

```suggestion
The following excerpt from the Magento code passes the `storeManager` argument as a proxy to the `Magento\Store\Model\Resolver\Store` class. The `StoreManagerInterface` model is defined as a proxy class by adding `Proxy` at the end of original class in the `di.xml` file.

```xml
```

2020-12-18 06:17 UTC, RakeshJesadiya commented
@hguthrie I have updated the changes as per your request. Thank you.

2020-12-21 18:50 UTC, hguthrie approved these changes
As far as I can tell, it looks good. I will find someone to double-check. Thanks for the contribution.

2020-12-21 19:08 UTC, hguthrie approved these changes
After asking someone internal, looks like it needs a little tweak.
@BarnyShergold  Would you like to review this updated example?

2020-12-21 19:08 UTC, hguthrie commented on src/guides/v2.3/extension-dev-guide/proxies.md
> +The following excerpt from the Magento code passes the `storeManager` argument as a proxy to the `Magento\Store\Model\Resolver\Store` class. The `StoreManagerInterface` model is defined as a proxy cl
```suggestion
The following excerpt from the Magento code passes the `storeManager` argument as a proxy to the `Magento\Store\Model\Resolver\Store` class. The `StoreManagerInterface` model is defined as a proxy class by the added `Proxy` at the end of the original class in the `di.xml` file.
```

2020-12-22 06:47 UTC, RakeshJesadiya commented
@hguthrie I have updated the changes. Thank you.

2020-12-22 20:19 UTC, hguthrie commented
running tests

2020-12-22 20:41 UTC, merged