giftcard errors coverage
magento/devdocs pull request #8413
Opened 2020-12-18 06:15 UTC by sathiyaaa

## Purpose of this pull request

This pull request (PR) covers the error messages in the remove-giftcard mutation

## Affected DevDocs pages

-  src/guides/v2.3/graphql/mutations/remove-giftcard.html
- src/guides/v2.4/graphql/mutations/remove-giftcard.md

2020-12-18 10:45 UTC, BarnyShergold requested changes
Just two small changes

2020-12-18 10:45 UTC, BarnyShergold commented on src/guides/v2.3/graphql/mutations/remove-giftcard.md
> +`The gift card couldn't be deleted from the quote.` | The value provided in the `gift_card_code` field is invalid or the giftCard with that specific ID does not exist in the cart.
```suggestion
`The gift card couldn't be deleted from the quote.` | The value provided in the `gift_card_code` field is invalid or the gift card with that specific ID does not exist in the cart.
```

2020-12-18 10:45 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/remove-giftcard.md
> +`The gift card couldn't be deleted from the quote.` | The value provided in the `gift_card_code` field is invalid or the giftCard with that specific ID does not exist in the cart.
```suggestion
`The gift card couldn't be deleted from the quote.` | The value provided in the `gift_card_code` field is invalid or the gift card with that specific ID does not exist in the cart.
```

2020-12-18 11:55 UTC, BarnyShergold approved these changes
Thanks!

2020-12-21 03:29 UTC, keharper approved these changes

2020-12-21 03:30 UTC, merged