Updates to ssh key enablement for Cloud projects
magento/devdocs pull request #8416
Opened 2020-12-18 18:17 UTC by meker12

* Added an additional method regarding adding a SSH key

* Apply suggestions from code review

Co-authored-by: Barny Shergold <barny.shergold@vaimo.com>

## Purpose of this pull request

Add additional method to add and update SSH keys. Merges changes introduced in  #8379.

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/before/before-workspace-ssh.html

2020-12-18 20:28 UTC, hguthrie requested changes
Are you still updating this? Too much use of the word "will" and needs work to be consistent with Cloud guide tone and formatting.

2020-12-21 16:29 UTC, meker12 commented
> Are you still updating this? Too much use of the word "will" and needs work to be consistent with Cloud guide tone and formatting.

Yes-- I merged the other PR to the SSH enablement topic. Just working on merging this into integration branch to fix it up.

2020-12-23 19:36 UTC, hguthrie approved these changes

2020-12-23 19:36 UTC, hguthrie commented on src/_includes/cloud/enable-ssh.md
> +-  [Add an SSH key to your GitHub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) and [test the SSH connection](https://docs.github.com/en/free-pro-team@latest
😄

2021-01-04 20:55 UTC, merged