Magento 2.4.2 Beta Release Note minor update December 21
magento/devdocs pull request #8426
Opened 2020-12-21 19:27 UTC by jfrontain

## Purpose of this pull request

This pull request (PR) updates the Magento 2.4.2 Beta Release Notes with notes about Composer 2.x compatibility and split db deprecation.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/release-notes/commerce-2-4-2.html
https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-2.html

whatsnew
Updated Magento 2.4.2 Beta release notes.

2020-12-21 19:32 UTC, jeff-matthews approved these changes

2020-12-21 19:34 UTC, jeff-matthews requested changes
I've been asked to remove the split DB instructions, so you'll need to remove the link.

2020-12-21 21:28 UTC, jeff-matthews approved these changes
We're not removing the instructions, so the link is still good.

2020-12-21 22:23 UTC, keharper commented on src/guides/v2.4/release-notes/commerce-2-4-2.md
> +The ability to configure a Magento installation to use a split database has been deprecated in this release. Merchants who currently use split database should start planning to revert to or migrate t
```suggestion
*  The ability to configure a Magento installation to use a split database has been deprecated in this release. Merchants who currently use split database should start planning to revert to or migrate to a single database or use an alternative approach. See the [Deprecation of split database functionality in Magento Commerce](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-split-database-functionality-in-Magento-Commerce/ba-p/465187) DevBlog post for an overview of this issue.  See [Revert from a split database to a single database]({{ page.baseurl }}/config-guide/revert-split-database.html) for migration instructions.
```

2020-12-21 22:23 UTC, keharper commented on src/guides/v2.4/release-notes/open-source-2-4-2.md
> +The ability to configure a Magento installation to use a split database has been deprecated in this release. Merchants who currently use split database should start planning to revert to or migrate t
```suggestion
*  The ability to configure a Magento installation to use a split database has been deprecated in this release. Merchants who currently use split database should start planning to revert to or migrate to a single database or use an alternative approach. See the [Deprecation of split database functionality in Magento Commerce](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-split-database-functionality-in-Magento-Commerce/ba-p/465187) DevBlog post for an overview of this issue.  See [Revert from a split database to a single database]({{ page.baseurl }}/config-guide/revert-split-database.html) for migration instructions.
```

2020-12-22 15:12 UTC, jeff-matthews commented
running tests

2020-12-22 15:31 UTC, merged