Update array-manager.md
magento/devdocs pull request #8438
Opened 2020-12-23 12:36 UTC by RakeshJesadiya

Added Missing methods from the ArrayManager class and added one more example of the newly added functions.

## Purpose of this pull request

This pull request (PR) adds the missing functions on the ArrayManager class.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/framework/array-manager.html
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/framework/array-manager.html

2020-12-23 21:21 UTC, keharper requested changes
@RakeshJesadiya This PR will require technical review. Adobe/Magento will be shut down from Dec 24 to Jan 4, so it'll be a while until the PR can be processed further.

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
> +| `find` | Finds node in nested array and saves its index and parent node reference |
```suggestion
| `find` | Finds a node in a nested array and saves its index and parent node reference |
```

Add a period to the end of each line in this table.

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
> +| `get` | Returns the value of the key (or node) at the end of the path, `null` is returned if the node hasn't been found |
```suggestion
| `get` | Returns the value of the key (or node) at the end of the path. `null` is returned if the node could not be found. |
```

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
> +| `merge` | Merge value with node and return modified data |
```suggestion
| `merge` | Merges a value with a node and return the modified data. |
```

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
> +| `populate` | Populate nested array if possible and needed |
```suggestion
| `populate` | Populates a nested array, if possible and necessary. |
```

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
> +| `findPaths` | Get matching paths for elements with specified indexes |
```suggestion
| `findPaths` | Gets matching paths for elements with specified indexes. |
```

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
> +| `slicePath` | Retrieve slice of specified path |
```suggestion
| `slicePath` | Retrieves a slice of the specified path. |
```

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
>  | `set` | Set value into node and returns modified data |
```suggestion
| `set` | Sets the value into a node and returns modified data. |
```

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
>  | `remove` | Removes node and returns modified array |
```suggestion
| `remove` | Removes a node and returns the modified array. |
```

2020-12-23 21:21 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/framework/array-manager.md
> +You can use the  `Magento\Framework\Stdlib\ArrayManager` library to populate array from the given path:
```suggestion
You can use the  `Magento\Framework\Stdlib\ArrayManager` library to populate an array from the given path:
```

2020-12-24 05:36 UTC, RakeshJesadiya commented
@keharper  I have updated changes as per your suggestion.

2021-01-04 15:18 UTC, dobooth approved these changes

2021-01-14 13:27 UTC, BarnyShergold approved these changes

2021-01-14 13:33 UTC, dobooth commented
running tests

2021-01-14 13:57 UTC, merged