[WIP] GraphQL: Mutation for adding wishlist items to the cart
magento/devdocs pull request #8519
Opened 2021-01-14 19:40 UTC by keharper

## Purpose of this pull request

This pull request (PR) adds documentation for the addWishlistItemsToCart mutation.

Related PRs: 
https://github.com/magento/magento2/pull/31584
https://github.com/magento/partners-magento2ee/pull/449

Issue:
https://github.com/magento/magento2/issues/31331

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-02-03 22:46 UTC, dobooth approved these changes

2021-02-09 22:14 UTC, BarnyShergold requested changes

2021-02-09 22:14 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/add-wishlist-items-to-cart.md
> +`INSUFFICIENT_STOCK` | The requested quanity of a product is greater than the quantity available
```suggestion
`INSUFFICIENT_STOCK` | The requested quantity of a product is greater than the quantity available
```

2021-02-12 09:55 UTC, BarnyShergold commented
@keharper - There's a small spelling mistake to correct on this PR

2021-02-22 17:36 UTC, dthampy commented on src/guides/v2.4/graphql/mutations/add-wishlist-items-to-cart.md
> +`wishlist` | [Wishlist!](#Wishlist) | Contains the wish list with all items that were successfully added
I wonder if the description should be something like " Contains items in the wishlist after adding to cart" . But it is up to you @keharper if we need to align the description with other mutations where "wishlist" is being returned in the response or if we need to update description depending on the context

2021-02-22 18:58 UTC, keharper commented
running tests

2021-02-22 22:06 UTC, keharper commented
running tests

2021-02-22 22:56 UTC, keharper commented
running tests

2021-02-22 23:04 UTC, dthampy approved these changes

2021-02-22 23:44 UTC, keharper commented
running tests

2021-02-23 00:43 UTC, keharper commented
running tests

2021-02-23 01:03 UTC, merged