Update project-webint-snap.md
magento/devdocs pull request #8524
Opened 2021-01-15 18:46 UTC by barnato-v

Added ``` to command bash
php vendor/bin/ece-tools -- main sales to format correctly in the section titled Dump your database {#db-dump}

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-01-15 18:46 UTC, magento-engcom-team commented
@barnato-v thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2021-01-15 18:52 UTC, dobooth commented
Thanks @barnato-v for the contribution. Please sign the Adobe CLA so we can proceed with this PR.

2021-01-15 19:26 UTC, hguthrie requested changes

2021-01-15 19:26 UTC, hguthrie commented on src/cloud/project/project-webint-snap.md
> +php vendor/bin/ece-tools -- main sales ```
Thanks for catching that. Just need to place in on the next line and it's good.

2021-01-19 18:21 UTC, barnato-v commented
> @barnato-v thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

@hguthrie I tried clicking on the link you suggested but I didn't see an invitation? It redirected to https://github.com/orgs/magento

Can you resend?

2021-01-19 19:21 UTC, hguthrie approved these changes
Thanks for fixing!
I went ahead and removed the extra space and added the carriage return.
I'm not sure about that link you mentioned. I think that was an automated email. But if you want to fully participate, you can certainly ask in our Slack channel. 🙂 In any case, I will pass the word along.

2021-01-19 19:47 UTC, hguthrie commented
running tests

2021-01-19 19:49 UTC, hguthrie commented
running tests

2021-01-19 20:09 UTC, merged