GraphQL: Add configured_variant attribute
magento/devdocs pull request #8539
Opened 2021-01-20 17:43 UTC by keharper

## Purpose of this pull request

This pull request (PR) adds the `configured_variant` to the `CartItemInterface`, per https://github.com/magento/magento2/pull/30817

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-01-21 14:39 UTC, dobooth approved these changes

2021-01-27 23:07 UTC, cpartica requested changes

2021-01-27 23:07 UTC, cpartica commented on src/guides/v2.4/graphql/interfaces/cart-item-interface.md
> +`configured_variant` | [ProductInterface]({{page.baseurl}}/graphql/interfaces/product-interface.html) | Product details of the cart item
there could be more to this:
 - regardless of the storeConfig value `configurable_thumbnail_source` which points to the child or parent while rendering cart the `configured_variant` will always show the child. It is up to the UI to query configured_variant when configurable_thumbnail_source is set to child. 
 There might other use cases when we want to know details about the `configured_variant` than just the thumbnail

2021-01-27 23:12 UTC, cpartica commented on src/guides/v2.4/graphql/interfaces/cart-item-interface.md
> +`configured_variant` | [ProductInterface]({{page.baseurl}}/graphql/interfaces/product-interface.html) | Product details of the cart item
also FYI this PR that you're linking to is obsolete, there's a new PR https://github.com/magento/magento2/pull/31380

2021-01-28 20:09 UTC, keharper commented
running tests

2021-01-28 21:33 UTC, keharper commented
running tests

2021-01-29 16:56 UTC, cpartica approved these changes

2021-01-29 16:59 UTC, keharper commented
running tests

2021-01-29 17:19 UTC, merged