Update content less standards
magento/devdocs pull request #8555
Opened 2021-01-25 12:58 UTC by mrtuvn

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-less.html
https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-less.html
## Links to Magento source code

-  ...

2021-01-25 18:36 UTC, BarnyShergold requested changes

2021-01-25 18:36 UTC, BarnyShergold commented on src/guides/v2.3/coding-standards/code-standard-less.md
> +[Css Theme]: {{ site.baseurl }}/guides/v{{ site.version }}/frontend-dev-guide/css-topics/css-themes.html
```suggestion
[Css Theme]: {{ page.baseurl }}/frontend-dev-guide/css-topics/css-themes.html
```

2021-01-25 18:36 UTC, BarnyShergold commented on src/guides/v2.3/coding-standards/code-standard-less.md
> +[Theme](https://glossary.magento.com/theme) mixins (except extends) should be located in the `web/css/source` directory. For more details, refer to our [Css Theme][].
```suggestion
[Theme](https://glossary.magento.com/theme) mixins (except extends) should be located in the `web/css/source` directory. For more details, refer to [Css Theme][].
```

2021-02-01 13:19 UTC, dobooth approved these changes

2021-02-01 13:20 UTC, dobooth commented
Good to go, @BarnyShergold ?

2021-02-01 13:38 UTC, BarnyShergold approved these changes
Good to go!

2021-02-01 18:48 UTC, dobooth commented
running tests

2021-02-01 19:23 UTC, merged