ui-columncontrols-clarification-7730
magento/devdocs pull request #8601
Opened 2021-02-01 05:03 UTC by Santoshziffity

## Purpose of this pull request

This pull request adds some example to this topic 
Topic name : ui-columncontrols-clarification-7730

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-columnscontrols.html

## Links issues : 
#7730

2021-02-01 09:52 UTC, BarnyShergold requested changes
Just a few small changes

2021-02-01 09:52 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/components/ui-columnscontrols.md
> +### You can simply change "minVisible" and "maxVisible" values in the JS file.
Headings should be short and non-conversational
```suggestion
### Change "minVisible" and "maxVisible" values in the JS file.
```

2021-02-01 09:52 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/components/ui-columnscontrols.md
> +#### For override JS file follow step Below:
```suggestion
#### To override the JS file follow the step below:
```

2021-02-10 17:01 UTC, BarnyShergold approved these changes

2021-02-11 12:25 UTC, dobooth approved these changes

2021-02-11 12:27 UTC, dobooth commented
running tests

2021-02-11 13:03 UTC, dobooth commented
running tests

2021-02-11 14:23 UTC, merged