#8106 Clarify JS init component key
magento/devdocs pull request #8609
Opened 2021-02-02 12:21 UTC by DenisSaltanahmedov

## Purpose of this pull request
This pull request adds additional examples of the "component key" related to JS data-mage-init to this topic.

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_init.html

## Links to Magento source code
-  src/guides/v2.4/javascript-dev-guide/javascript/js_init.md

2021-02-02 13:08 UTC, BarnyShergold requested changes
Just one small correction

2021-02-02 13:08 UTC, BarnyShergold commented on src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
> +Or a custom JS component, can be component path `Vendor_Module/js/component` or alias declareted in `requirejs-config.js`.
```suggestion
Or a custom JS component, can be component path `Vendor_Module/js/component` or alias declared in `requirejs-config.js`.
```

2021-02-02 16:51 UTC, dobooth requested changes

2021-02-02 16:51 UTC, dobooth commented on src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
> +Where `<component_name>` native Magento JS component, for example: `menu`, `collapsible`, `tooltip` ...
```suggestion
Where `<component_name>` is a native Magento JS component, for example: `menu`, `collapsible`, `tooltip` ...
```

2021-02-02 16:51 UTC, dobooth commented on src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
> +Or a custom JS component, can be component path `Vendor_Module/js/component` or alias declareted in `requirejs-config.js`.
```suggestion
Or a custom JS component, implemented with a component path: `Vendor_Module/js/component`, or as an alias declared in `requirejs-config.js`.
```
If this suggestion is not accurate, than some kind of grammar fix is needed here.

2021-02-02 16:51 UTC, dobooth commented on src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
> +More about [locate JS components](https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_debug.html).
```suggestion
Read more about [locate JS components](https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_debug.html).
```

2021-02-03 08:25 UTC, DenisSaltanahmedov commented
@BarnyShergold, @dobooth thanks for your help. I have fixed the review.

2021-02-03 08:57 UTC, BarnyShergold approved these changes

2021-02-03 18:27 UTC, dobooth approved these changes

2021-02-03 18:28 UTC, dobooth commented
running tests

2021-02-03 18:40 UTC, merged