Update indexer-batch.md regarding last code changes
magento/devdocs pull request #8618
Opened 2021-02-03 01:40 UTC by vzabaznov

## Purpose of this pull request

This pull request (PR) updates batch sizes options regarding last code changes

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexer-batch.html#eav-indexer-optimization

## Links to Magento source code

-  ...

2021-02-03 12:11 UTC, BarnyShergold requested changes
Not sure why linting is failing. Please check after next commit.

2021-02-03 12:11 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/indexer-batch.md
> +Batch size for `catalogsearch_fulltext` can be set different parameters.
```suggestion
Batch size for `catalogsearch_fulltext` can be set using different parameters.
```

2021-02-03 12:11 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/indexer-batch.md
> +* `partial_reindex` - represent how many product will be proceeded in partial reindex.
```suggestion
* `partial_reindex` - represents how many products will be processed in a partial reindex.
```

2021-02-03 12:11 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/indexer-batch.md
> +* `elastic_save` - represent how many product will be saved as batch into Elastic.
```suggestion
* `elastic_save` - represents how many products will be saved as a batch into Elasticsearch.
```

2021-02-03 12:11 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/indexer-batch.md
> +* `mysql_get` - represent how many searchable product will be retrived from Mysql.
Is this needed as MySQL search was removed in 2.4?
```suggestion
* `mysql_get` - represents how many searchable products will be retrieved from Mysql.
```

2021-02-09 15:52 UTC, dobooth approved these changes

2021-02-12 09:53 UTC, BarnyShergold approved these changes
Thanks!

2021-02-17 13:04 UTC, dobooth commented
running tests

2021-02-17 13:17 UTC, merged