Issue-8581- Changed the Code Snippet as requested
magento/devdocs pull request #8623
Opened 2021-02-03 15:54 UTC by dineshvb

## Purpose of this pull request

This pull request (PR) covers #8581

## Affected DevDocs pages

-  /guides/v2.3/howdoi/checkout/checkout_new_field.html
-  /guides/v2.4/howdoi/checkout/checkout_new_field.html

2021-02-03 22:40 UTC, BarnyShergold requested changes

2021-02-03 22:40 UTC, BarnyShergold commented on src/guides/v2.3/howdoi/checkout/checkout_new_field.md
> +                    function (element) {
Indenting is not standard format. Lines 106/108 are indented 8 spaces - should be 4. Line 107 should be indented 4 from 106

2021-02-05 10:41 UTC, BarnyShergold approved these changes
Excellent!

2021-02-05 12:00 UTC, dobooth approved these changes

2021-02-05 12:00 UTC, dobooth commented
running tests

2021-02-05 12:19 UTC, merged