#6970 Add more examples for utilizing custom cache type
magento/devdocs pull request #8628
Opened 2021-02-04 10:25 UTC by DenisSaltanahmedov

## Purpose of this pull request

This pull request (PR) adds more examples for utilizing custom cache type

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/cache/partial-caching/create-cache-type.md

## Links to Magento source code
-  src/guides/v2.4/extension-dev-guide/cache/partial-caching/create-cache-type.md

## Links to issue
- https://github.com/magento/devdocs/issues/6970

2021-02-04 13:24 UTC, BarnyShergold requested changes
Nice additions - just some grammar corrections

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +## Store data into custom cache type {#m2devgde-store-data-cache-type}
```suggestion
## Store data in a custom cache type {#m2devgde-store-data-cache-type}
```

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +To store data in a serialized form into a custom cache should be made the steps:
```suggestion
To store data in a serialized form in a custom cache, follow these steps:
```

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +*  Pass the argument to the constructor `Magento\Framework\App\CacheInterface` $cache of a necessary class (Repository, Model, Block, etc)
```suggestion
*  Pass the argument to the constructor `Magento\Framework\App\CacheInterface` `$cache` of a required class (Repository, Model, Block, etc)
```

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +## Retrieve data from custom cache type {#m2devgde-retrieve-data-cache-type}
Add a blank line before the header

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +Retrieve data in the cache
```suggestion
Retrieve data from the cache
```

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +To invalidate custom cache type should be made the steps:
```suggestion
To invalidate a custom cache type, follow these steps:
```

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +*  Pass the argument to the constructor `Magento\Framework\App\Cache\TypeListInterface` $typeList of a necessary class (Repository, Model, Block, etc)
```suggestion
*  Pass the argument to the constructor `Magento\Framework\App\Cache\TypeListInterface` `$typeList` of a required class (Repository, Model, Block, etc)
```

2021-02-04 13:24 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
> +*  Programatically, using the TypeList.
```suggestion
*  Programmatically, using the TypeList.
```

2021-02-05 08:00 UTC, DenisSaltanahmedov commented
@BarnyShergold thanks for your help. I have fixed the review.

2021-02-05 10:22 UTC, BarnyShergold approved these changes
Nice work!

2021-02-05 16:20 UTC, dobooth approved these changes

2021-02-05 16:22 UTC, dobooth commented
running tests

2021-02-05 16:36 UTC, merged