Added the error coverage for customerAttributeMetadata query
magento/devdocs pull request #8629
Opened 2021-02-04 11:24 UTC by dineshvb

## Purpose of this pull request

This pull request (PR) adds the error coverage for customerAttributeMetadata query.

## Affected DevDocs pages

-   /guides/v2.3/graphql/queries/custom-attribute-metadata.html
-   /guides/v2.4/graphql/queries/custom-attribute-metadata.html

2021-02-04 13:26 UTC, BarnyShergold requested changes
Just a few grammar corrections

2021-02-04 13:26 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
> +`The attribute with a "xxxx" attributeCode doesn't exist. Verify the attribute and try again` | The given `attribue_code` parameter is invalid.
```suggestion
`The attribute with a "xxxx" attributeCode doesn't exist. Verify the attribute and try again` | The given `attribute_code` parameter is invalid.
```

2021-02-04 13:26 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
> +`Missing attribute_code for the input entity_type: "xxxx"`| There is no value mentioned for the `attribute_code` parameter for the given `entity_type` parameter.
```suggestion
`Missing attribute_code for the input entity_type: "xxxx"`| There is no value passed for the `attribute_code` parameter for the given `entity_type` parameter.
```

2021-02-04 13:26 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
> +`Missing entity_type for the input attribute_code: "xxxx"` | There is no value mentioned for the `entity_type` parameter for the given `attribute_code` parameter.
```suggestion
`Missing entity_type for the input attribute_code: "xxxx"` | There is no value passed for the `entity_type` parameter for the given `attribute_code` parameter.
```

2021-02-04 13:26 UTC, BarnyShergold commented on src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
> +`Missing attribute_code/entity_type for the input Empty AttributeInput` | There are no values mentioned for both `attribute_code` and `entity_type` parameters.
```suggestion
`Missing attribute_code/entity_type for the input Empty AttributeInput` | There are no values passed for both `attribute_code` and `entity_type` parameters.
```

2021-02-05 02:44 UTC, keharper approved these changes

2021-02-05 02:45 UTC, keharper commented
running tests

2021-02-05 02:48 UTC, keharper commented
running tests

2021-02-05 03:03 UTC, merged