MCLOUD-7604: 'use_stale_cache' option use
magento/devdocs pull request #8672
Opened 2021-02-10 19:54 UTC by dhorytskyi

## Purpose of this pull request

Provide more information on how to use the "use_stale_cache" option.
Fix code samples.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/config-guide/cache/two-level-cache.html
- https://devdocs.magento.com/cloud/env/variables-deploy.html

2021-02-11 12:20 UTC, dobooth commented
Hi @dhorytskyi Please sign the Adobe CLA so we can process this PR.

2021-02-11 15:49 UTC, dhorytskyi commented
Hi @dobooth I've signed it.

2021-02-11 17:07 UTC, BarnyShergold requested changes
Nice update - just some grammatical corrections

2021-02-11 17:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
> +Put this into the `app/etc/env.php` file or replace existed cache section.
```suggestion
Put this into the `app/etc/env.php` file or replace the existing cache section.
```

2021-02-11 17:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
> +      -  `cache_dir` __a file cache specific option.__ Is a directory where the local cache will be stored.
```suggestion
      -  `cache_dir` __a file cache specific option.__ Is the directory where the local cache will be stored.
```

2021-02-11 17:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
> +   -  `remote_backend_options` are the remote cache configuration.
```suggestion
   -  `remote_backend_options` is the remote cache configuration.
```

2021-02-11 17:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
> +-  `backend_options` are the L2 cache configuration.
```suggestion
-  `backend_options` is the L2 cache configuration.
```

2021-02-11 17:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
> +   -  `local_backend_options` are the local cache configuration.
```suggestion
   -  `local_backend_options` is the local cache configuration.
```

2021-02-11 17:07 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
> +We recommend the use of Redis for remote caching - `\Magento\Framework\Cache\Backend\Redis`, and the File cache implementation - `Cm_Cache_Backend_File` as the local cache storing data in shared memo
```suggestion
We recommend the use of Redis for remote caching - `\Magento\Framework\Cache\Backend\Redis`, and the File cache implementation - `Cm_Cache_Backend_File` as the local cache for storing data in shared memory - `'local_backend_options' => ['cache_dir' => '/dev/shm/']`.
```

2021-02-11 20:18 UTC, dhorytskyi commented
@BarnyShergold Thank you!

2021-02-12 09:21 UTC, BarnyShergold approved these changes

2021-02-25 16:16 UTC, oshmyheliuk approved these changes

2021-02-25 17:03 UTC, bdenham requested changes
Just a few wording changes. Thanks @dhorytskyi.

2021-02-25 17:03 UTC, bdenham commented on src/guides/v2.4/config-guide/cache/two-level-cache.md
> +We recommend the use of Redis for remote caching - `\Magento\Framework\Cache\Backend\Redis`, and the File cache implementation - `Cm_Cache_Backend_File` as the local cache for storing data in shared
```suggestion
We recommend using Redis for remote caching (`\Magento\Framework\Cache\Backend\Redis`) and the `Cm_Cache_Backend_File` implementation for local caching of data in shared memory, using `'local_backend_options' => ['cache_dir' => '/dev/shm/']`.
```

2021-03-02 19:02 UTC, bdenham commented
Hey @dhorytskyi, just following up with you on this PR. Its ready to merge after you make the wording changes suggested above.

2021-03-03 06:10 UTC, dhorytskyi commented
@bdenham Thank you, I've applied your suggestions.

2021-03-04 00:09 UTC, bdenham commented
running tests

2021-03-04 02:47 UTC, bdenham commented
@magento import code to magento-devdocs/devdocs

2021-03-04 02:49 UTC, magento-engcom-team commented
@bdenham the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8672`.

2021-03-04 02:59 UTC, bdenham approved these changes

2021-03-04 03:20 UTC, merged