Static files fall back docs clarification 2609
magento/devdocs pull request #8687
Opened 2021-02-12 13:46 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) for Remove the wrong path of the static file 

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-inherit.html

2021-02-12 15:01 UTC, BarnyShergold approved these changes

2021-02-17 11:47 UTC, dobooth commented
Hi @Santoshziffity. Thanks for contributing.  Can you please fix this merge conflict?

2021-02-17 13:10 UTC, Santoshziffity commented
> Hi @Santoshziffity. Thanks for contributing. Can you please fix this merge conflict?

2021-02-18 13:12 UTC, dobooth commented
@BarnyShergold Here's another OrangeCo instance. What are you using instead?

2021-02-19 11:23 UTC, BarnyShergold requested changes

2021-02-19 11:23 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
> +1. Current theme module static files `<theme_dir>/<Namespace>_<Module>/web/`.Example: `app/design/frontend/OrangeCorp/orange/Magento_Catalog/web/`
```suggestion
1. Current theme module static files `<theme_dir>/<Namespace>_<Module>/web/`.Example: `app/design/frontend/ExampleCorp/orange/Magento_Catalog/web/`
```

2021-02-19 11:24 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
> +1. Current theme module static files `<theme_dir>/<Namespace>_<Module>/web/`.Example: `app/design/frontend/OrangeCorp/orange/Magento_Catalog/web/`
We just need to clean this one file up to remove OrangeCorp

2021-02-19 11:51 UTC, BarnyShergold approved these changes
Thanks for being so quick!

2021-02-19 16:33 UTC, dobooth approved these changes

2021-02-19 16:34 UTC, dobooth commented
running tests

2021-02-19 16:54 UTC, merged