change layout file order
magento/devdocs pull request #8694
Opened 2021-02-16 12:49 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) for change layout files order

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-inherit.html#theme-inherit-layout

2021-02-16 14:20 UTC, BarnyShergold requested changes
Few small grammar corrections

2021-02-16 14:20 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
> +1. Ancestor themes layouts, starting from the most distant ancestor, recursively until a theme with no parent is reached: `<parent_theme_dir>/<Vendor>_<Module>/layout/`
```suggestion
1. Ancestor theme layouts, starting from the most distant ancestor, recursively until a theme with no parent is reached: `<parent_theme_dir>/<Vendor>_<Module>/layout/`
```

2021-02-16 14:20 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
> +1. All modules layout files in sequence defined in app/etc/config.php respecting the component load order. For each module:
```suggestion
1. All module layout files in sequence, defined in `app/etc/config.php` respecting the component load order. For each module:
```

2021-02-17 15:26 UTC, dobooth approved these changes

2021-02-17 15:26 UTC, dobooth commented
running tests

2021-02-17 15:27 UTC, keharper commented
@Santoshziffity This topic was changed two weeks ago in https://github.com/magento/devdocs/pull/8599 to remove the references to OrangeCompany. It looks like they might have missed an item. Please revert the examples to "SampleCompany" and update other references in this top to OrangeCompany or OrangeCo

I don't understand why you changed the example so that the copyright page is removed from the footer instead of a report bugs page. The original example seems much more likely.

2021-02-17 16:32 UTC, BarnyShergold commented
@Santoshziffity - I am about to change all occurrences of OrangeCo to ExampleCorp (as this is used elsewhere) . So for consistency, please can you change all occurrences of OrangeCo AND SampleCompany in this file to ExampleCorp and we'll review. This will avoid any conflicts with the PR I am about to make. Thanks

2021-02-17 17:46 UTC, dobooth approved these changes

2021-02-17 17:46 UTC, dobooth commented
running tests

2021-02-17 18:05 UTC, merged