Clarify attributes on Message config topic
magento/devdocs pull request #8726
Opened 2021-02-23 12:12 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) for Clarify attributes on Message config topic like schema, request, publishers, consumers.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/message-queues/config-mq.html

2021-02-23 14:19 UTC, BarnyShergold requested changes
I've corrected some of the language used. Please check that you are happy the meaning is still intact.

Good clarifications

2021-02-23 14:19 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +request | Specifies the data structure that’s used to define a message and is needed when publishing any messages through Magento.
Please avoid contractions
```suggestion
request | Specifies the data structure that is used to define a message and is needed when publishing any messages through Magento.
```

2021-02-23 14:19 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +schema | Schema describes the message structure. Use the Data Interface format from the Service Contracts. Besides, there is another way to specify a service method signature:`<module>\Api\<ServiceNa
Avoid conversational language
```suggestion
schema | Schema describes the message structure. Use the Data Interface format from the Service Contracts. There is an alternative way to specify a service method signature:`<module>\Api\<ServiceName>::<methodName>` (E.g. Magento\Customer\Api\CustomerRepositoryInterface::save).
```

2021-02-23 14:19 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +As for consumer elements, they map the message receiver to a specific queue. Such parameters as class and method indicate what elements of the Magento 2 Message Queue Framework receive and process th
```suggestion
With consumer elements, they map the message receiver to a specific queue. Such parameters as class and method indicate what elements of the Magento 2 Message Queue Framework receive and process the message.
```

2021-02-23 14:19 UTC, BarnyShergold commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +The publisher element performs two vital actions: iit configures the type of connection and the same time sets up the exchange to publish to. Magento 2 uses only one exchange out of the box, but mult
```suggestion
The publisher element performs two vital actions, it configures the type of connection and at the same time, sets up the exchange to publish to. Magento uses only one exchange out of the box, but multiple exchanges are possible. The name for every exchange is contained in the publisher configuration.
```

2021-02-23 14:38 UTC, keharper requested changes

2021-02-23 14:38 UTC, keharper commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +request | Specifies the data structure that’s used to define a message and is needed when publishing any messages through Magento.
```suggestion
request | Specifies the data structure that’s used to define a message. It is needed when publishing any messages through Magento.
```

2021-02-23 14:38 UTC, keharper commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +As for consumer elements, they map the message receiver to a specific queue. Such parameters as class and method indicate what elements of the Magento 2 Message Queue Framework receive and process th
```suggestion
Consumer elements map the message receiver to a specific queue. Parameters such as class and method indicate which elements of the Message Queue Framework receive and process the message.
```

2021-02-23 14:38 UTC, keharper commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +{:.no_toc}
Delete the added spaces at the end of this line

2021-02-23 14:38 UTC, keharper commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +The publisher element performs two vital actions: iit configures the type of connection and the same time sets up the exchange to publish to. Magento 2 uses only one exchange out of the box, but mult
```suggestion
The publisher element performs two vital actions: 

*  It configures the type of connection.
*  It sets up the exchange to publish to. 

Magento uses only one exchange out of the box, but multiple exchanges are possible. The name of every exchange is a part of the publisher configuration.
```

2021-02-23 14:38 UTC, keharper commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +schema | Schema describes the message structure. Use the Data Interface format from the Service Contracts. Besides, there is another way to specify a service method signature:`<module>\Api\<ServiceNa
```suggestion
schema | Describes the message structure. Use the Data Interface format from the Service Contracts. Besides, there is another way to specify a service method signature:`<module>\Api\<ServiceName>::<methodName>` (Magento\Customer\Api\CustomerRepositoryInterface::save).
```

2021-02-23 14:38 UTC, keharper commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +schema | Schema describes the message structure. Use the Data Interface format from the Service Contracts. Besides, there is another way to specify a service method signature:`<module>\Api\<ServiceNa
I don't understand "Use the Data Interface format from the Service Contracts. Besides, there is another way to specify a service method signature:"  Is `<module>\Api\<ServiceName>::<methodName>` not the preferred way to specify a schema name? You don't list the data interface format.

2021-02-24 21:15 UTC, keharper commented on src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
> +schema | Describes the message structure. Use the Data Interface format from the Service Contracts. Besides, there is another way to specify a service method signature:`<module>\Api\<ServiceName>::<m
My comment on this line wasn't addressed. You don't mention what the Data Interface format is or differentiate it from `<module>\Api\<ServiceName>::<methodName>`.

2021-03-02 17:03 UTC, keharper commented
Closing this PR because it contains content plagiarized from [Firebear Studio](https://firebearstudio.com/blog/magento-2-message-queue-framework.html).

2021-03-02 17:03 UTC, closed without merging