Final Page Builder TOC and removal of
magento/devdocs pull request #8732
Opened 2021-02-23 23:37 UTC by bdenham

## Purpose of this pull request

This pull request (PR) finishes the last directory and file name changes made to the Page Builder repo. It also removes the entry for `magento/magento2-page-builder-data-migration` from the Docfile.yml. I moved the handful of files we were pulling from the page builder migration repo, into the main page builder docs repo. This should help simplify our pipeline a little. 

## Affected DevDocs pages

Several Page Builder topics.

I've covered the Page Builder docs reorg in a previous PR.

2021-02-23 23:45 UTC, dshevtsov commented on src/_data/toc/rest-api.yml
> +              url: https://magento.redoc.ly/2.4.1-admin/
This looks like an unintended change

2021-02-23 23:46 UTC, bdenham commented on src/_data/toc/rest-api.yml
> +              url: https://magento.redoc.ly/2.4.1-admin/
Oops. Yeah that snuck in...Got it.

2021-02-23 23:50 UTC, dshevtsov requested changes

2021-02-23 23:50 UTC, dshevtsov commented on src/_data/toc/rest-api.yml
> +              url: https://magento.redoc.ly/2.4.1-customer/
```suggestion
              url: https://magento.redoc.ly/2.4.2-customer/
```

2021-02-23 23:50 UTC, dshevtsov commented on src/_data/toc/rest-api.yml
> +              url: https://magento.redoc.ly/2.4.1-guest/
```suggestion
              url: https://magento.redoc.ly/2.4.2-guest/
```

2021-02-23 23:53 UTC, dshevtsov approved these changes

2021-02-23 23:56 UTC, bdenham commented
running tests

2021-02-24 00:14 UTC, merged

2021-03-05 17:17 UTC, Leland commented
Hi @bdenham, a heads up that this change didn't add any kind of redirects, so folks looking for this on search engines are currently getting served 404s. Try Googling for "How to upgrade content types" for, instance:  https://www.google.com/search?q=%22How+to+upgrade+content+types%22

I speak as one such individual who had to really dig to find what he was looking for :)