EQPS-908: Devdocs for EQP MFTF Tests - Editable branch
magento/devdocs pull request #8738
Opened 2021-02-24 20:51 UTC by dobooth

## Purpose of this pull request

This pull request (PR) adds pages for new EQP test types to Marketplace EQP Sellers pages. These Types are MFTF Vendor Supplied tests and MFTF Magento Tests

## Affected DevDocs pages

- Adds new pages here: https://devdocs.magento.com/marketplace/sellers/

Replaces #8663

2021-02-24 21:18 UTC, BarnyShergold requested changes
Very minor changes

2021-02-24 21:18 UTC, BarnyShergold commented on src/marketplace/sellers/mftf-magento.md
> +-  OpenSource and Commerce editions
```suggestion
-  Open Source and Commerce editions
```

2021-02-24 21:18 UTC, BarnyShergold commented on src/marketplace/sellers/mftf-magento.md
> +-  MFTF returns two types of results
```suggestion
-  MFTF returns two types of results:
```

2021-02-24 21:18 UTC, BarnyShergold commented on src/marketplace/sellers/mftf-magento.md
> +-  Ensure that any necessary credentials, user authorization (e.g. to communicate via API key to your backend) is explained and supported via Credential management in Tests
```suggestion
-  Ensure that any necessary credentials, user authorization (e.g. to communicate via API key to your backend) is explained and supported via credential management in Tests
```

2021-02-25 16:02 UTC, vkublytskyi commented
@dobooth, what are the next steps for this PR? What should be done to have these pages published?

2021-02-25 17:03 UTC, vkublytskyi commented
@dobooth I would ask you to revert your latest structural changes as it breaks semantic and inconsistent with other EQP tools documentation.

We have predefined sections for each tool:

1. Overview - general description of check
2. What testing is for - describes why we have this check in place
3. When testing is done - describes what conditions should be satisfied for check execution or skip
4. What is being checked - describes the scope of check
5. Tools and environments used - describes how we build our testing environment
6. Reading the error report - explain how to interpret information returned by the tool
7. Troubleshooting - describes how to avoid failures, and what to do if a reported error has no clear root cause

2021-02-25 19:32 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-02-25 19:33 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8738`.

2021-02-25 22:01 UTC, keharper approved these changes

2021-02-25 22:15 UTC, dobooth commented
running tests

2021-02-25 22:37 UTC, merged

2021-02-26 01:59 UTC, vkublytskyi commented
@dobooth, @keharper During technical review were made following  errors which I consider as critical:

---

Section of "When testing is done" for both new pages are:

> The MFTF tests are run as a regular part of the installation and Varnish testing process.

This is technically not correct and misleading users as these checks run in parallel with Installation and Varnish tests and fully isolated from each other

Original text was

> MFTF vendor supplied Tests are run only where:
>
> -  There are MFTF tests included in the submission in the correct directory (`Tests/Mftf`)
> -  Only for MFTF v3.0 or greater
> -  Only for Magento v2.4.0 or greater

> MFTF Magento supplied Tests will be run for all Marketplace extension submissions for:
>
> -  Magento in 2.3 and 2.4 release lines
> -  OpenSource and Commerce editions

---

Page https://devdocs.magento.com/marketplace/sellers/mftf-vendor.html has duplicated section `What is being checked`

---

Therefore we will create tomorrow new PR with the necessary fixes. Hope we will be able to process it quickly so users will have the best experience with reading our docs.

CC @magterskine