add component example
magento/devdocs pull request #8742
Opened 2021-02-25 13:16 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) added component example 

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-jquery-widgets.html

2021-02-25 18:01 UTC, BarnyShergold requested changes

2021-02-25 18:01 UTC, BarnyShergold commented on src/guides/v2.3/coding-standards/code-standard-jquery-widgets.md
> +  }}'></div>
It would be clearer if this was all on one line.

2021-02-25 18:01 UTC, BarnyShergold commented on src/guides/v2.3/coding-standards/code-standard-jquery-widgets.md
> +*  Using a script type "text/x-magento-init" attribute. For example:
```suggestion
*  Using a script type `text/x-magento-init` attribute. For example:
```

2021-02-25 18:01 UTC, BarnyShergold commented on src/guides/v2.3/coding-standards/code-standard-jquery-widgets.md
> +*  data-mage-init
```suggestion
*  `data-mage-init`
```

2021-03-08 23:26 UTC, BarnyShergold approved these changes

2021-03-09 16:31 UTC, dobooth approved these changes

2021-03-09 16:32 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-09 16:33 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8742`.

2021-03-11 17:20 UTC, merged