remove database connection line
magento/devdocs pull request #8745
Opened 2021-02-26 12:16 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) remove the database connection line from "The build system does not need any of the following:" section

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/build-system.html

2021-02-26 13:52 UTC, BarnyShergold approved these changes
Agreed - some build systems DO use a clean database to test against but it's not essential.
BTW can you put a link to the 2.3 page in the description of the PR for completeness

Also I thought I remember seeing an issue raised along this clarification? If this is correct please add the issue to the description.

2021-03-01 13:04 UTC, dobooth requested changes
If there is only one item in the list, let's just make it a sentence. 
The build system does not need Magento to be installed, but the code must be available to it.

2021-03-02 14:08 UTC, dobooth approved these changes

2021-03-02 14:08 UTC, dobooth commented
running tests

2021-03-02 14:22 UTC, merged