Kh registrants mutations
magento/devdocs pull request #8749
Opened 2021-02-26 21:11 UTC by keharper

## Purpose of this pull request

This pull request (PR) adds the three mutations that manage gift registry registrants. It fixes #8603 

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-02-26 22:02 UTC, keharper commented
running tests

2021-03-01 09:40 UTC, BarnyShergold requested changes
Nice new topic - few corrections and suggestions made.

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/add-gift-registry-registrants.md
> +The `addGiftRegistryRegistrants` mutation add a registrant to the specified gift registry.
```suggestion
The `addGiftRegistryRegistrants` mutation adds a registrant to the specified gift registry.
```

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/add-gift-registry-registrants.md
> +        firstname: "Monica"
Would suggest using a name like "Jane Doe" as "Monica Resendez" is a real person.

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/add-gift-registry-registrants.md
> +            "firstname": "Stacey",
Would suggest using a name like "Jane Doe" & "John Doe" as "Monica Resendez" is a real person.

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/create-gift-registry.md
> -          lastname: "Mao"
Would advise more generic names

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/remove-gift-registry-registrants.md
> +The `removeGiftRegistryRegistrants` mutation .
You also haven't described what this mutation does - like you have on others.
```suggestion
The `removeGiftRegistryRegistrants` mutation.
```

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/remove-gift-registry-registrants.md
> +```json
Would advise more generic names

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/update-gift-registry-registrants.md
> +```json
Would advise more generic names

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/update-gift-registry-registrants.md
> +`gift_registry` | [GiftRegistry](#GiftRegistry) | The gift registry after adding registrants
Should this not say "after updating registrants" ?

2021-03-01 09:40 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/remove-gift-registry-registrants.md
> +`gift_registry` | [GiftRegistry](#GiftRegistry) | The gift registry after adding registrants
Should this not say "after removing registrants" ?

2021-03-01 22:42 UTC, keharper commented
running tests

2021-03-02 04:35 UTC, merged