usecase of the command bin/magento dev:source-theme:deploy
magento/devdocs pull request #8751
Opened 2021-03-01 12:21 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) of the use case of the command bin/Magento dev:source-theme: deploy

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-less-sass.html

2021-03-01 13:08 UTC, BarnyShergold requested changes

2021-03-01 13:08 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/cli/config-cli-subcommands-less-sass.md
> +## Common issue faced by Developer when working
```suggestion
## Common issues faced by developers when working
```

2021-03-01 13:08 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/cli/config-cli-subcommands-less-sass.md
> +In the development stage, when you are working with css, Js, knockout js and knockout template, the developer faces below issues
```suggestion
In the development stage, when you are working with CSS, JS, Knockout JS and Knockout template, the developer may face the following issues:
```

2021-03-01 13:08 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/cli/config-cli-subcommands-less-sass.md
> +-  The changes in css , knockout js and knockout templates are not affecting on frontend when page load.
```suggestion
-  The changes in CSS , Knockout JS and Knockout templates are not reflected on frontend when page loads.
```

2021-03-01 13:08 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/cli/config-cli-subcommands-less-sass.md
> +-  The developer has to delete the pub static folder or run static content deploy command every time when changes in js and knockout template file.
```suggestion
-  The developer has to delete the `pub/static` folder or run static content deploy command every time when there are changes in JS and Knockout template files.
```

2021-03-01 13:08 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/cli/config-cli-subcommands-less-sass.md
> +If you are facing this kind of issue in development then create symlinks
This is not a very helpful statement. Please expand on how this should be done specifically when the above issues are encountered.

2021-03-09 16:38 UTC, dobooth commented
Hmm...I am not sure about this addition. Are these tips related to creating symlinks to LESS files? This seems more like general implementation tips.

2021-03-09 16:46 UTC, BarnyShergold requested changes

2021-03-15 18:48 UTC, dobooth commented
@Santoshziffity ?

2021-03-23 14:18 UTC, dobooth commented
Closing as abandoned.

2021-03-23 14:18 UTC, closed without merging