Screenshot of registered theme in admin
magento/devdocs pull request #8760
Opened 2021-03-02 07:16 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) add the screenshot of the registered theme in Magento Admin (Content > Design > Themes)

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-install.html

2021-03-02 09:36 UTC, BarnyShergold approved these changes
Nice addition

2021-03-05 17:47 UTC, BarnyShergold requested changes
I've just noticed - image file names should be in lowercase.
Please correct.

2021-03-09 16:49 UTC, dobooth approved these changes

2021-03-09 16:49 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-11 14:50 UTC, merged