Reference Links and some code examples added
magento/devdocs pull request #8761
Opened 2021-03-02 09:20 UTC by ajithkumar-maragathavel

## Purpose of this pull request

This pull request (PR) updates reference links to Plugins and adds some examples to the existing topics.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-manage.html

2021-03-02 09:41 UTC, BarnyShergold requested changes
Just some small changes

2021-03-02 09:41 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
> +-  Fonts related files are stored under `<theme_dir>/<Namespace>_<Module>/web/fonts/`
```suggestion
-  Font related files are stored in the `<theme_dir>/<Namespace>_<Module>/web/fonts/` directory
```

2021-03-02 09:41 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
> +-  Static assets like images are stored under `<theme_dir>/<Namespace>_<Module>/web/images/`
```suggestion
-  Static assets, like images, are stored in the `<theme_dir>/<Namespace>_<Module>/web/images/` directory
```

2021-03-02 09:41 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
> +-  CSS and LESS files are stored under `<theme_dir>/web/css/`
```suggestion
-  CSS and LESS files are stored in the  `<theme_dir>/web/css/` directory.
```

2021-03-02 09:41 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
> +-  JS files are stored under `<theme_dir>/<Namespace>_<Module>/web/js/`
```suggestion
-  JS files are stored in the `<theme_dir>/<Namespace>_<Module>/web/js/` directory
```

2021-03-02 09:41 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
> +For more information about the Plugins refer to the [Plugins in Magento]({{ page.baseurl }}/extension-dev-guide/plugins.html)
```suggestion
For more information about Plugins refer to [Plugins in Magento]({{ page.baseurl }}/extension-dev-guide/plugins.html)
```

2021-03-02 16:55 UTC, BarnyShergold requested changes
Two missed corrections - PR will be approved after these - apologies

2021-03-02 16:55 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
> +-  CSS and LESS files are stored in the  `<theme_dir>/web/css/` directory.
```suggestion
-  CSS and LESS files are stored in the `<theme_dir>/web/css/` directory.
```

2021-03-02 16:55 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
> +For more information about Plugins refer to [Plugins in Magento]({{ page.baseurl }}/extension-dev-guide/plugins.html)
```suggestion
For more information about Plugins, refer to [Plugins in Magento]({{ page.baseurl }}/extension-dev-guide/plugins.html)
```

2021-03-02 17:03 UTC, ajithkumar-maragathavel commented
@BarnyShergold Thanks for the review. I have updated the PR.

2021-03-02 17:24 UTC, BarnyShergold approved these changes
Cheers!

2021-03-09 18:27 UTC, dobooth approved these changes

2021-03-09 18:28 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-09 18:29 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8761`.

2021-03-11 15:00 UTC, merged