Localization and specify template info added
magento/devdocs pull request #8768
Opened 2021-03-03 15:42 UTC by ajithkumar-maragathavel

## Purpose of this pull request

This pull request (PR) updates information on localization and also added another way of specifying templates for the blocks.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-override.html
-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-override.html

2021-03-03 16:26 UTC, BarnyShergold requested changes

2021-03-03 16:26 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/templates/template-override.md
> +<span><?= $block->escapeHtml(__('Back to Product Reviews')) ?></span>
Block version is deprecated.
```suggestion
<span><?= $escaper->escapeHtml(__('Back to Product Reviews')) ?></span>
```

2021-03-03 16:26 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/templates/template-override.md
> +Template for the `review_view` block is not specified using the `template` attribute of the `<block>` layout instruction. Instead It is specified in the `app/code/Magento/Review/Block/View.php` block
```suggestion
Template for the `review_view` block is not specified using the `template` attribute of the `<block>` layout instruction. Instead it is specified in the `app/code/Magento/Review/Block/View.php` block class.
```

2021-03-03 16:44 UTC, ajithkumar-maragathavel commented
@BarnyShergold Thanks for the review. Updated the PR with the required changes.

2021-03-08 23:18 UTC, BarnyShergold commented
@magento run all tests

2021-03-08 23:27 UTC, BarnyShergold commented
You need to correct linting errors

2021-03-09 07:53 UTC, ajithkumar-maragathavel commented
> You need to correct linting errors

@BarnyShergold Can you please let me how to see the error logs for lint? Because Right now I can only able to see the below information on the test result.

![lint-error](https://user-images.githubusercontent.com/47966038/110436707-8ce55e00-80da-11eb-84e2-9c90186ed142.png)

2021-03-09 15:43 UTC, BarnyShergold approved these changes
Oddly when I came back, all the Linting Tests were working - so I'll approve

2021-03-11 18:34 UTC, dobooth approved these changes

2021-03-12 16:28 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-12 16:29 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8768`.

2021-03-15 17:10 UTC, merged