privatelink updates needed - Clarifications
magento/devdocs pull request #8771
Opened 2021-03-03 22:20 UTC by jpanke

Needed to clarify what https is (its 443) as well as ensuring that I added what the principle needs to be filled out with for easier access.   arn:aws:iam::402592597372:root

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-03-03 23:23 UTC, bdenham approved these changes
Check and commit changes.

2021-03-03 23:23 UTC, bdenham commented on src/cloud/project/privatelink-service.md
> +   -  **Service endopoint access granted**-Ensure that your service endpoint has the principle set to allow access to= `arn:aws:iam::402592597372:root`.  If this is not set the bi-direction connectio
```suggestion
   -  **Service endpoint access granted**-Provide the Magento account principal with access to your service endpoint: `arn:aws:iam::402592597372:root`. If this access is not provided, the bidirectional PrivateLink connection to the service in your VPC will not be added, which will delay the setup.
```

2021-03-03 23:23 UTC, bdenham commented on src/cloud/project/privatelink-service.md
> +   -  **Customer** enables Magento access to the endpoint service in customer VPC.  There is prereq of ensuring principle access= `arn:aws:iam::402592597372:root`
```suggestion
   -  **Customer** enables Magento access to the endpoint service in the customer VPC. This assumes that the Magento account principal has access to `arn:aws:iam::402592597372:root`, as previously described in the **Service endpoint access granted** prerequisite.
```

2021-03-03 23:34 UTC, bdenham requested changes

2021-03-03 23:34 UTC, bdenham commented on src/cloud/project/privatelink-service.md
> +-  You cannot use the HTTPS (443) protocol to connect to Magento Commerce over PrivateLink.
```suggestion
-  You cannot use the HTTPS protocol (port 443) to connect to Magento Commerce over PrivateLink.
```

2021-03-04 17:14 UTC, bdenham approved these changes

2021-03-04 17:38 UTC, jpanke commented
this is good changes.

2021-03-04 18:18 UTC, bdenham commented
@magento import code to magento-devdocs/devdocs

2021-03-04 18:19 UTC, magento-engcom-team commented
@bdenham the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8771`.

2021-03-10 00:50 UTC, merged