magento/devdocs#2957 Adding an example of the "fieldset" node configuration in the definition.xml
magento/devdocs pull request #8773
Opened 2021-03-04 10:04 UTC by DenisSaltanahmedov

## Purpose of this pull request
This pull request (PR) adds an example of the "fieldset" node configuration in the definition.xml

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.4/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.html

## Links to Magento source code
-  src/guides/v2.4/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md

## Links to issue
https://github.com/magento/devdocs/issues/2957

2021-03-04 13:56 UTC, BarnyShergold requested changes
2 small suggestions

2021-03-04 13:56 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
> +### Example of the "fieldset" node configuration in the definition.xml
```suggestion
### Example of the `fieldset` node configuration in the `definition.xml`
```

2021-03-05 09:07 UTC, DenisSaltanahmedov commented
@BarnyShergold thanks for your review. I have added the fix.

2021-03-05 09:59 UTC, BarnyShergold approved these changes

2021-03-18 13:01 UTC, dobooth approved these changes

2021-03-18 13:01 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-18 13:02 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8773`.

2021-03-18 18:20 UTC, merged