Update devdocs.css
magento/devdocs pull request #8783
Opened 2021-03-05 12:53 UTC by aryandesssigner

## Fixed Space between button on page survey section  #8782 

## Purpose of this pull request

This pull request for fixing space issue between button of page-survey-questions

## Affected DevDocs pages

All devdoc page where survey button is present

2021-03-05 12:53 UTC, magento-engcom-team commented
@aryandesssigner thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2021-03-05 17:39 UTC, BarnyShergold requested changes
There are some issues causing linting errors in other areas of the file that will need fixing -
Line 11 - insert space between dt and {
Line 12 - insert space after : 
Line 19 - wants a leading zero but not sure why!

You need to sign the Adobe CLA and ensure the Linting checks pass.

2021-03-05 17:39 UTC, BarnyShergold commented on src/common/css/devdocs.css
> +    margin-right: 10px;
```suggestion
  margin-right: 10px;
```

2021-03-08 23:28 UTC, BarnyShergold commented
You still need to correct the linting errors

2021-03-16 20:57 UTC, BarnyShergold commented
There seems to be a whitespace the end of EVERY new line in devdocs.css

2021-03-23 17:24 UTC, bdenham commented
We really don't want to be adding overriding styles outside of the https://github.com/magento-devdocs/devdocs-theme repo. I will soon move or remove all stylesheets that are currently a part of `devdocs/common/css` to the devdocs theme repo. Spreading styles between the theme and the devdocs project results in a maintenance nightmare.

Does this make sense to everyone? @belbiy?

2021-03-24 23:07 UTC, dobooth commented
just running a test here....

2021-03-24 23:07 UTC, dobooth commented
@magento import pr to magento-commerce/devdocs

2021-03-24 23:08 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-03-25 12:33 UTC, closed without merging