Set the store email from Magento Admin
magento/devdocs pull request #8784
Opened 2021-03-05 13:09 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR) for Set the store email from Magento Admin

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email.html

2021-03-05 17:46 UTC, BarnyShergold requested changes
Image file name should be in lowercase.
Please correct.

2021-03-08 23:15 UTC, BarnyShergold approved these changes

2021-03-10 13:26 UTC, dobooth approved these changes

2021-03-10 13:27 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-10 13:28 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8784`.

2021-03-11 17:20 UTC, merged