Add UCT "Troubleshooting" section
magento/devdocs pull request #8804
Opened 2021-03-15 17:46 UTC by Dnd-Mafer

## Purpose of this pull request

This pull request (PR) add a troubleshooting on UCT usage if nothing appears in terminal.

## Affected DevDocs pages

https://devdocs.magento.com/upgrade-compatibility-tool/run.html

## What's new ?

Troubleshooting section => https://devdocs.magento.com/upgrade-compatibility-tool/run.html#troubleshooting

2021-03-15 20:10 UTC, dobooth commented
Thanks for the PR, @Dnd-Mafer. Looks like you have a trailing space on around line 150.

2021-03-16 09:01 UTC, BarnyShergold requested changes
Just a few suggestions

2021-03-16 09:01 UTC, BarnyShergold commented on src/upgrade-compatibility-tool/run.md
> +if the only output is `Upgrade compatibility tool`
Should this not say "run this command:" at end of this sentence?
```suggestion
If the only output is `Upgrade compatibility tool`
```

2021-03-16 09:01 UTC, BarnyShergold commented on src/upgrade-compatibility-tool/run.md
> +$ bin/uct upgrade:check /var/www/project/magento/ -c 2.4.1
```suggestion
bin/uct upgrade:check /var/www/project/magento/ -c 2.4.1
```

2021-03-16 09:01 UTC, BarnyShergold commented on src/upgrade-compatibility-tool/run.md
> +$
Remove this line

2021-03-16 09:07 UTC, Dnd-Mafer commented on src/upgrade-compatibility-tool/run.md
> +$
Done

2021-03-16 20:59 UTC, BarnyShergold approved these changes

2021-03-17 12:46 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-17 12:47 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8804`.

2021-03-17 14:44 UTC, dshevtsov commented
@Dnd-Mafer, we cannot process pull requests open from the master branch. Please follow [contribution guidelines](https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md#create-a-branch) and create a new pull request with your changes. Link this pull request in the description, so that an assignee and reviewers would consider the work they've done already.

2021-03-17 14:44 UTC, closed without merging