EQPS-1001: EQP MFTF Update Devdocs
magento/devdocs pull request #8829
Opened 2021-03-23 19:15 UTC by magterskine

## Purpose of this pull request

- Update to explain that tests do not affect Technical Review status
- Includes list of test executed for MFTF Magento Supplied test

## Affected DevDocs pages

https://devdocs.magento.com/marketplace/sellers/mftf-magento.html

https://devdocs.magento.com/marketplace/sellers/mftf-vendor.html

2021-03-24 09:03 UTC, BarnyShergold requested changes
Nice clarification - just a few corrections

2021-03-24 09:03 UTC, BarnyShergold commented on src/marketplace/sellers/mftf-magento.md
> +Magento-Supplied MFTF tests are not required to pass for technical review. The outcome of this testing is used to inform QA efforts and provide feedback on functional quality.
```suggestion
Magento supplied MFTF tests are not required to pass for technical review. The outcome of this testing is used to assist with QA efforts and provide feedback on functional quality.
```

2021-03-24 14:36 UTC, magterskine commented
@BarnyShergold Thanks for the review and suggestion - made the changes requested

2021-03-24 15:05 UTC, BarnyShergold requested changes
Very strange -  I made this correction the first time round but it has disappeared!

2021-03-24 15:05 UTC, BarnyShergold commented on src/marketplace/sellers/mftf-vendor.md
> +Vendor-Supplied MFTF tests are not required to pass for technical review. The outcome of this testing is used to inform QA efforts and provide feedback on functional quality.
```suggestion
Vendor supplied MFTF tests are not required to pass for technical review. The outcome of this testing is used to assist with QA efforts and provide feedback on functional quality.
```

2021-03-24 15:15 UTC, BarnyShergold approved these changes
👍

2021-03-25 12:41 UTC, dobooth approved these changes

2021-03-25 12:42 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-03-25 12:43 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8829`.

2021-03-25 14:20 UTC, merged