New topic - show or hide password checkbox implementation
magento/devdocs pull request #8837
Opened 2021-03-25 18:58 UTC by ajithkumar-maragathavel

## Purpose of this pull request

This pull request (PR) adds a new topic that describes the implementation of the show or the hide password checkbox functionality.

## Affected DevDocs pages

-  New Topic

## Links to Magento source code

-  https://github.com/magento/magento2/pull/31482

Fixes #8808

2021-03-26 11:04 UTC, BarnyShergold requested changes
Great new topic explanation!

2021-03-26 11:04 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/howto/show_or_hide_password_checkbox.md
> +        <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
Block Escaper is deprecated.
```suggestion
        <fieldset class="fieldset login" data-hasrequired="<?= $escaper->escapeHtml(__('* Required Fields')) ?>">
```

2021-03-26 11:04 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/howto/show_or_hide_password_checkbox.md
> +    <form class="form form-company-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="company-login-form">
```suggestion
    <form class="form form-company-login" action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="company-login-form">
```

2021-03-26 11:04 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/howto/show_or_hide_password_checkbox.md
> +                <label class="label" for="email"><span><?= $block->escapeHtml(__('Company Email')) ?></span></label>
```suggestion
                <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Company Email')) ?></span></label>
```

2021-03-26 11:04 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/howto/show_or_hide_password_checkbox.md
> +                <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
```suggestion
                <label for="pass" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
```

2021-03-26 11:04 UTC, BarnyShergold commented on src/guides/v2.3/ui_comp_guide/howto/show_or_hide_password_checkbox.md
> +                    <button type="submit" class="action login primary" id="company-submit"><span><?= $block->escapeHtml(__('Company Sign In')) ?></span></button>
```suggestion
                    <button type="submit" class="action login primary" id="company-submit"><span><?= $escaper->escapeHtml(__('Company Sign In')) ?></span></button>
```

2021-03-26 12:27 UTC, ajithkumar-maragathavel commented
@BarnyShergold Thanks for the review. I have updated the PR based on your comments. Please have a look at it.

2021-03-26 14:28 UTC, BarnyShergold approved these changes
Nice!

2021-03-30 17:42 UTC, dobooth commented
Nice work, @ajithkumar-maragathavel. Rather than symlink the image, you can put it in `src/common/images` and call it from there in both versions.

2021-03-31 05:20 UTC, ajithkumar-maragathavel commented
> Nice work, @ajithkumar-maragathavel. Rather than symlink the image, you can put it in `src/common/images` and call it from there in both versions.

@dobooth  Thanks for the suggestion. I have updated the PR by moving the image to the common directory and removed symlinks as well. Please review it.

2021-04-01 16:54 UTC, dobooth approved these changes

2021-04-01 16:55 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-04-01 16:56 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-04-06 10:54 UTC, ajithkumar-maragathavel commented
@dobooth I have updated the new topic only for v2.4. Please review it.

2021-04-06 14:56 UTC, dobooth approved these changes

2021-04-06 14:58 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-04-08 14:30 UTC, merged

2021-04-09 07:44 UTC, atwixfirster commented
Hi,  ajithkumar-maragathavel !

Thank you for your work here. Sorry for being a bit late on the party but as a reader I would like to know what is a `Magento_Customer/js/show-password` component and where is I can find it in Magento codebase?

Thank you!

2021-04-09 10:53 UTC, ajithkumar-maragathavel commented
> Hi, @ajithkumar-maragathavel !
> 
> Thank you for your work here. Sorry for being a bit late on the party but as a reader I would like to know what is a `Magento_Customer/js/show-password` component and where is I can find it in Magento codebase?
> 
> Thank you!

@atwixfirster  Thanks for the suggestion. I will update the document in a separate PR explaining the `Magento_Customer/js/show-password` component and I will also add the Magento codebase link.

2021-04-09 11:14 UTC, atwixfirster commented
> > Hi, @ajithkumar-maragathavel !
> > Thank you for your work here. Sorry for being a bit late on the party but as a reader I would like to know what is a `Magento_Customer/js/show-password` component and where is I can find it in Magento codebase?
> > Thank you!
> 
> @atwixfirster Thanks for the suggestion. I will update the document in a separate PR explaining the `Magento_Customer/js/show-password` component and I will also add the Magento codebase link.

Cool. Thank you, @ajithkumar-maragathavel