Update callout about Pro routing
magento/devdocs pull request #8841
Opened 2021-03-29 14:12 UTC by BarnyShergold

## Purpose of this pull request

This pull request (PR) fixes issue #8832 

## Affected DevDocs pages

https://devdocs.magento.com/cloud/project/project-multi-sites.html

2021-03-29 19:45 UTC, hguthrie requested changes

2021-03-29 19:45 UTC, hguthrie commented on src/cloud/project/project-multi-sites.md
> +For Pro, if your routes are not getting configured, you must create a [Support ticket]({{ site.baseurl }}/cloud/trouble/trouble.html) - please include "enable self-service routes" in your request.
Please is nice, but we don't use it.

```suggestion
For Pro, if your route configurations are not setting properly, you can create a [Support ticket]({{ site.baseurl }}/cloud/trouble/trouble.html) and include "enable self-service routes" in your request.
```

2021-03-30 15:02 UTC, hguthrie approved these changes

2021-03-30 15:55 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-03-30 18:50 UTC, merged