Update link in Cloud Docs
magento/devdocs pull request #8842
Opened 2021-03-29 14:22 UTC by BarnyShergold

## Purpose of this pull request

This pull request (PR) fixes issue #8810

## Affected DevDocs pages

https://devdocs.magento.com/cloud/live/stage-prod-migrate.html#troubleshooting-the-database-migration

2021-03-29 19:46 UTC, hguthrie requested changes

2021-03-30 08:09 UTC, BarnyShergold commented on src/cloud/live/stage-prod-migrate.md
> +`zcat /tmp/database.sql.gz | sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' | mysql -h <database_host> -u <username> -p<password> <database name>`
Updates done!

2021-03-30 14:56 UTC, hguthrie approved these changes

2021-03-30 15:54 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-03-30 15:55 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-03-30 18:50 UTC, merged