Improve build and deploy env definitions
magento/devdocs pull request #8843
Opened 2021-03-29 15:03 UTC by BarnyShergold

## Purpose of this pull request

This pull request (PR) fixes #8815

## Affected DevDocs pages

https://devdocs.magento.com/cloud/project/magento-env-yaml.html
https://devdocs.magento.com/cloud/live/sens-data-over.html

2021-03-29 20:58 UTC, hguthrie requested changes
Looks good in the SCD Performance section.
Not so keen on the addition to the File structure section.

If you duplicate the content and one set changes, then it stands to reason they both might require the same change. If there must be two instances of this information, then I recommend creating an `_include` file, that way if you change one, you change them all.

2021-03-30 08:23 UTC, BarnyShergold commented on src/cloud/project/magento-env-yaml.md
> +If you have enabled Configuration Management after dumping the configurations, you should move the SCD_* variables from the deploy to the build stage.
I'm a  bit confused then as to your comment on the issue - you said "Good suggestions for improving the build and deploy definitions".

However, I've moved it to a new section and moved the content to an include.

2021-03-30 14:38 UTC, hguthrie commented on src/cloud/project/magento-env-yaml.md
> +If you have enabled Configuration Management after dumping the configurations, you should move the SCD_* variables from the deploy to the build stage.
Yes, they are good suggestions...in the SCD Performance section of the Configuration management for store settings topic.
The problem is that it seemed out of the context or spirit of the **File structure** paragraph in the Build and deploy topic. That paragraph was defining the sections that make up the .magento.env.yaml file.

The new section looks great and is more focused. This way, if there is any further Config Management things to discuss in relation to the EnV config yaml, there is a clear place for it.

2021-03-30 15:52 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-03-30 15:53 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-03-30 18:50 UTC, merged