magento/devdocs#8873: Add clarification about required parameter for date validation
magento/devdocs pull request #8874
Opened 2021-04-14 12:45 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

Fix pull request fixes https://github.com/magento/devdocs/issues/8873

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_calendar.html

## Links to Magento source code

-  https://github.com/magento/magento2/blob/2.4/lib/web/mage/validation.js#L1046

2021-04-14 13:14 UTC, atwixfirster commented on src/guides/v2.3/javascript-dev-guide/widgets/widget_calendar.md
> +To validate the calendar widget, required **dateFormat** parameter should be specified, as can be seen from the validate-date rule initialisation:
@EvheniiaKolkhiieva  could you please highlight a validate-date - `validate-date`.

Thank you!

2021-04-14 13:34 UTC, atwixfirster commented
@EvheniiaKolkhiieva , thank you for your contribution. 

A small notice here: your PR totally makes sense for Magento 2.4.0 and newest versions. 

Please add your notices to `2.4` version of this document.

Thank you!

2021-04-14 13:41 UTC, rogyar requested changes
Hi @EvheniiaKolkhiieva. Great job! Please, check my suggestions below

2021-04-14 13:41 UTC, rogyar commented on src/guides/v2.3/javascript-dev-guide/widgets/widget_calendar.md
> +            function (value, params, additionalParams) {
Please, make sure we use the correct indentation (number of spaces before each line of code) here. 
Let me provide a correct version: 

```javascript
'validate-date': [
    function (value, params, additionalParams) {
        var test = moment(value, utils.convertToMomentFormat(additionalParams.dateFormat));

        return $.mage.isEmptyNoTrim(value) || test.isValid();
    },
    $.mage.__('Please enter a valid date.')
]
```

2021-04-14 13:41 UTC, rogyar commented on src/guides/v2.3/javascript-dev-guide/widgets/widget_calendar.md
> +
Also, please, remove this extra empty line here.

2021-04-14 14:20 UTC, EvheniiaKolkhiieva commented
Thank you @atwixfirster and @rogyar for your attention!

I have implemented the fixes you suggested, please check!

Thank you!

2021-04-14 15:19 UTC, atwixfirster approved these changes
Approve from my side!

Thank you, @EvheniiaKolkhiieva

2021-04-14 17:17 UTC, rogyar approved these changes

2021-04-15 15:01 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2021-04-15 15:01 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8874`.

2021-04-21 15:20 UTC, merged