New tutorial for sending custom emails
magento/devdocs pull request #8884
Opened 2021-04-17 13:31 UTC by chandru-199

## Purpose of this pull request

This pull request (PR) - Creating new tutorial for sending custom emails

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/send-custom-email.html

2021-04-19 10:48 UTC, BarnyShergold requested changes
Please add explanation and guide

2021-04-19 10:48 UTC, BarnyShergold commented on src/guides/v2.3/ext-best-practices/tutorials/send-custom-email.md
> +This topic describes how you can send custom emails in Magento. The below example shows how to send custom emails in Magento.
Whilst this is a great code fragment for sending emails there is no explanation to the code block, therefore it is not strictly a tutorial. The block and its requirements should be explained. What is this code and why is it there?

2021-04-22 13:26 UTC, dobooth commented
Thanks, @chandru-199. This topic could use some more explanation. I don't think we want to make a new topic that is mostly a code sample. Let us know if you have questions.

2021-04-27 07:58 UTC, BarnyShergold commented
@chandru-199 - It's been over a week since further explanation was required for this PR. Can you please let us know if you are still working on this and a likely time to completion? If we don't hear from you within the next few days, we will have to close this PR.

2021-04-28 06:45 UTC, chandru-199 commented
Hi @BarnyShergold @dobooth.
Sorry I was not available for past few days. I will make those changes.

2021-05-10 11:24 UTC, dobooth commented
Hi @chandru-199 Please reopen this when you are ready to proceed.

2021-05-10 11:24 UTC, closed without merging