Add instruction for changing Composer version
magento/devdocs pull request #8893
Opened 2021-04-22 18:07 UTC by shiftedreality

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-04-23 08:21 UTC, BarnyShergold requested changes
Small grammar suggestion

2021-04-23 08:21 UTC, BarnyShergold commented on src/cloud/docker/docker-config.md
> +You can change Composer version by adding next line in `.docker/config.env` configuration file:
```suggestion
You can change Composer version by adding the following line to the `.docker/config.env` configuration file:
```

2021-04-26 16:28 UTC, bdenham approved these changes

2021-04-26 16:29 UTC, bdenham commented
@magento import code to magento-devdocs/devdocs

2021-04-26 16:30 UTC, magento-engcom-team commented
@bdenham the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8893`.

2021-04-26 16:50 UTC, bdenham commented
@shiftedreality, this PR was imported to our devdocs team repo for merging and publishing: https://github.com/magento-commerce/devdocs/pull/2244.

2021-04-26 16:50 UTC, closed without merging