Magento/devdocs. Issue #8897.Set docroot - remove mention of setup wizard in 2.37
magento/devdocs pull request #8905
Opened 2021-04-29 07:48 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) fixes an issue https://github.com/magento/devdocs/issues/8897
## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/before/before-setup-env-install.html#set-the-docroot

2021-04-29 08:42 UTC, BarnyShergold requested changes

2021-04-29 08:42 UTC, BarnyShergold commented on src/cloud/before/before-setup-env-install.md
> +Set the `docroot` to the `/magento` directory until you complete all setup.
```suggestion
Set the `docroot` to the `/magento` directory until you complete the setup.
```
First sentence doesn't scan 😄

2021-04-29 14:51 UTC, hguthrie approved these changes

2021-04-29 16:37 UTC, BarnyShergold approved these changes
Thanks

2021-04-29 21:44 UTC, bdenham approved these changes

2021-04-30 13:15 UTC, hguthrie commented
@magento import code to magento-devdocs/devdocs

2021-04-30 13:16 UTC, magento-engcom-team commented
@hguthrie the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8905`.

2021-04-30 16:10 UTC, merged