magento/devdocs#8666 Adding instruction - how to stop queue workers.
magento/devdocs pull request #8919
Opened 2021-05-05 10:59 UTC by DenisSaltanahmedov

## Purpose of this pull request
This pull request (PR) adds the example to instruction about how to stop queue consumers.

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/example/shared-configuration.html

## Links to Magento source code
-  guides/v2.4/config-guide/deployment/pipeline/example/shared-configuration.md

2021-05-05 12:45 UTC, BarnyShergold requested changes
Few clarity suggestions

2021-05-05 12:45 UTC, BarnyShergold commented on src/_includes/config/split-deploy/example_update-prod.md
> +   Add changes to the app/etc/env.php:
```suggestion
   Set `cron_run` to `false` in `app/etc/env.php`, e.g.:
```
Explains what is happening.

2021-05-05 12:45 UTC, BarnyShergold commented on src/_includes/config/split-deploy/example_update-prod.md
> +   And `kill` active consumer processes.
```suggestion
Finally, `kill` active consumer processes.
```

2021-05-14 08:31 UTC, BarnyShergold commented
@DenisSaltanahmedov we are still waiting for you to make the changes on this PR - are you still working on it?
If it's not done in the next 5 days we will have to consider closing this PR and doing the changes on another.

2021-05-14 15:10 UTC, dobooth commented
This include is used in 3 separate files. Let's ensure that these changes are appropriate for all the affect topics.

2021-05-17 07:27 UTC, DenisSaltanahmedov commented
@BarnyShergold Sorry I miss the PR
Thanks for your review. I have fixed the PR

2021-05-19 14:57 UTC, dobooth requested changes
Sorry...hit the wrong button.

2021-05-25 06:19 UTC, DenisSaltanahmedov commented
@dobooth Thanks for your review, I have fixed the recommendation.

2021-05-25 11:44 UTC, dobooth approved these changes

2021-05-25 11:45 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-05-25 11:46 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-05-25 11:50 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-05-25 11:52 UTC, magento-engcom-team commented
@dobooth, an error occurred during the Pull Request import.

2021-05-28 14:38 UTC, keharper commented
To give an update on this PR. I asked for internal confirmation of these changes, but maybe @DenisSaltanahmedov and @BarnyShergold can provide assistance. Here's what I know:

* The topic at https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/example/shared-configuration.html was written in 2.2 and probably hasn't been updated much since then
* In 2.3.0 or thereabouts, support for messages was moved from Commerce to Open Source.
* I don't see the string `cron_consumers_runner` in Commerce. I do see it in Open Source: `app/code/Magento/MessageQueue/Model/Cron/ConsumersRunner.php`.

My hunch is that the updates in this PR would have been correct for 2.2, but now the line 

"1. If you use {{site.data.var.ee}}, stop queue workers." 

can be changed to something like

"1. Stop any running queue workers."

I'm not 100% sure. I can only see some details, and not the big picture.

2021-05-28 15:46 UTC, hostep commented
@keharper: that's correct, you need to stop queue consumers both in Commerce and Open Source since Magento 2.3.x

I'm however not sure if we should recommend `kill -9 {PID}` (signal: `KILL`) since that's a very dangerous command and might cause data los in the queues (not sure though), we have been using `kill {PID}` (`TERM` is the default signal I believe) for a while now and that works perfectly fine.

Also, be aware that a new command is coming, provided by: https://github.com/magento/magento2/pull/31495: `bin/magento queue:consumers:restart` (which will also run by default with `bin/magento setup:upgrade` by that same PR)
Be aware: this command will only update the poison pill version in the database and that will only cause consumers to restart when a new message is about to be processed. So if no new messages are in the queue, the consumer will still be running without being killed even after that new command gets executed.

Hope this helps a bit.

2021-05-28 17:06 UTC, keharper commented
Thanks for the update, @hostep. We'll update the docs with your suggestions. I've also asked the author of 31495 to open a docs PR when the new command features have been merged.

2021-05-28 18:41 UTC, keharper commented
@magento import code to magento-devdocs/devdocs

2021-05-28 19:01 UTC, keharper approved these changes

2021-06-01 13:30 UTC, merged