Change incorrect path
magento/devdocs pull request #8925
Opened 2021-05-07 13:00 UTC by ayman-betersport

I was trying to set up Varnish and was instructed to change the probe url from /pub/health_check.php to health_check.php. Unfortunately this did not work, I tried prepending a '/' which worked. So I think this should be changed in the docs before others waste time on this small thing. So it should be '/health_check.php' instead of 'health_check.php'

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-05-07 13:00 UTC, magento-engcom-team commented
@ayman-betersport thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2021-05-07 13:02 UTC, joostm020 approved these changes
I ran into the same issue, the proposed change is correct.

2021-05-07 15:09 UTC, BarnyShergold requested changes
Please can you complete the PR description as required for DEVDOCS? INformation is on the Repo wiki or you can check other PRs.

Also you will need to sign the Adobe CLA before this PR can be progressed. You only need to do this once, so future PRs will be okay.

2021-05-14 08:33 UTC, BarnyShergold commented
@ayman-betersport we are still waiting for you to make the changes on this PR - are you still working on it?
If it's not done in the next 7 days we will have to consider closing this PR and doing the changes on another.

2021-05-24 10:48 UTC, dobooth commented
Closed as abandoned.

2021-05-24 10:48 UTC, closed without merging