Add upgrade CLI command
magento/devdocs pull request #8926
Opened 2021-05-07 13:05 UTC by Santoshziffity

## Purpose of this pull request

This pull request (PR)  for Add upgrade CLI command 

## Affected DevDocs pages
-  https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/example/shared-configuration.html
-  https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/example/environment-variables.html
-  https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/example/cli.html

2021-05-07 13:45 UTC, dobooth requested changes

2021-05-07 13:45 UTC, dobooth commented on src/_includes/config/split-deploy/example_build-sync.md
> +   php bin/magento setup:upgrade
We don't do `php` at the start of commands anymore, correct?

2021-05-11 19:36 UTC, dobooth requested changes

2021-05-11 19:36 UTC, dobooth commented on src/_includes/config/split-deploy/example_build-sync.md
> +   php bin/magento setup:upgrade
Ok....so you can remove the `php`.

2021-05-12 19:34 UTC, hguthrie approved these changes

2021-05-12 21:07 UTC, dobooth commented
Hey @Santoshziffity Just want to make sure: This is a big command to run...and it's in an include file. Are we sure this is appropriate for all instances where the include is used? Does any backup need to happen before running it?

2021-05-13 05:24 UTC, ajithkumar-maragathavel commented
> Hey @Santoshziffity Just want to make sure: This is a big command to run...and it's in an include file. Are we sure this is appropriate for all instances where the include is used? Does any backup need to happen before running it?

@dobooth  Santoshziffity will not be available for quite some time. we might need to check this with someone else.

2021-05-13 13:43 UTC, hguthrie commented on src/_includes/config/split-deploy/example_build-sync.md
> +1. Run the upgrade command:
If possible, please clearly state what is going on here. I used Upgrade Magento as a suggestion, but that's maybe not the most apt description. I have seen `Update the database schema and data.` used before. Please confirm what this does in this particular step.

2021-05-13 15:53 UTC, BarnyShergold requested changes
Running this command at this stage requires a lot more information and explanation to be added as firstly it REQUIRES not only Magento to be installed on the system that the command is run on but also access to a Magento database. 

Even though the intention is to allow code files to be committed to the repository.

It also depends on the CI/CD workflow used.

EG if this were being run on a local machine, then Magento would need to be fully working - what happens if the database is not available?

I feel more work needs to be done to cover all eventualities.

2021-05-13 17:39 UTC, dobooth commented
I think I would more comfortable closing this PR for now. Once @Santoshziffity is back in action, we can discuss the optimal solution for this issue. Thanks all for the conversation. This is what makes open source a good idea.

2021-05-13 17:39 UTC, closed without merging