32574 GraphQL: move items from cart to gift registry
magento/devdocs pull request #8929
Opened 2021-05-10 16:54 UTC by khrystynastolbova

## Purpose of this pull request

This pull request (PR) adds the moveCartItemsToGiftRegistry mutation.

## Affected DevDocs pages

-  ...

## Links to Magento source code

/magento/partners-magento2ee/pull/540

Issue /magento/magento2#32574: Move items from cart to gift registry

2021-05-11 08:36 UTC, BarnyShergold requested changes
Great addition!

2021-05-11 08:36 UTC, BarnyShergold commented on src/_includes/graphql/gift-registry-items-user-error.md
> +`code`  | GiftRegistryItemsUserErrorType! | A gift registry-specific error code. Possible values include `OUT_OF_STOCK`, `NOT_FOUND` and `UNDEFINED`
```suggestion
`code`  | GiftRegistryItemsUserErrorType! | A gift registry specific error code. Possible values include `OUT_OF_STOCK`, `NOT_FOUND` and `UNDEFINED`
```

2021-05-11 08:36 UTC, BarnyShergold commented on src/_includes/graphql/gift-registry-items-user-error.md
> +`gift_registry_uid` | ID | The unique ID of the `Gift registry` object containing an error
Consistent with page below
```suggestion
`gift_registry_uid` | ID | The unique ID of the `GiftRegistry` object containing an error
```

2021-05-11 08:36 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/move-cart-items-to-gift-registry.md
> +The `MoveCartItemsToGiftRegistryOutput` object can contain the following attributes.
```suggestion
The `MoveCartItemsToGiftRegistryOutput` object can contain the following attributes:
```

2021-05-11 08:36 UTC, BarnyShergold commented on src/guides/v2.4/graphql/mutations/move-cart-items-to-gift-registry.md
> +The `moveCartItemsToGiftRegistry` mutation requires the following input.
```suggestion
The `moveCartItemsToGiftRegistry` mutation requires the following input:
```

2021-05-11 10:24 UTC, khrystynastolbova commented
Hi @BarnyShergold,
Thanks for your review and suggestions. The mentioned changes are done.

2021-05-13 03:07 UTC, keharper commented
@khrystynastolbova We need to account for the new interfaces somehow, but I'm not sure how to do it while just looking at the schema. They're too small to warrant their own topics. I'll get back to you in a few days, after I've had a chance to test the new mutation.

2021-05-19 07:11 UTC, khrystynastolbova commented
> @khrystynastolbova We need to account for the new interfaces somehow, but I'm not sure how to do it while just looking at the schema. They're too small to warrant their own topics. I'll get back to you in a few days, after I've had a chance to test the new mutation.

Hi @keharper! I see I missed the new interfaces. They are too small but other mutations will probably implement these interfaces. So maybe it would be better to move them to separate files?

2021-05-19 07:13 UTC, khrystynastolbova commented on src/guides/v2.4/graphql/mutations/move-cart-items-to-gift-registry.md
> +The `MoveCartItemsToGiftRegistryOutput` object can contain the following attributes:
```suggestion
The `MoveCartItemsToGiftRegistryOutput` object can contain the following attributes:

```

2021-05-19 07:18 UTC, khrystynastolbova commented on src/guides/v2.4/graphql/mutations/move-cart-items-to-gift-registry.md
> +`user_errors` | [[GiftRegistryItemsUserError!](#GiftRegistryItemsUserError)] | An array of errors encountered while moving items from the cart to the gift registry
### MoveCartItemsToGiftRegistryOutput attributes {#MoveCartItemsToGiftRegistryOutput}

The `MoveCartItemsToGiftRegistryOutput` object implements [`GiftRegistryOutputInterface`](#GiftRegistryOutputInterface) and [`GiftRegistryItemUserErrorInterface`](#GiftRegistryItemUserErrorInterface).

### GiftRegistryOutputInterface attributes {#GiftRegistryOutputInterface}

{% include graphql/gift-registry-output-interface.md %}

### GiftRegistryItemUserErrorInterface attributes {#GiftRegistryItemUserErrorInterface}

{% include graphql/gift-registry-item-user-error-interface.md %}
```

2021-05-24 16:45 UTC, keharper commented
@khrystynastolbova This PR looks like it's complete technically. Please add the following lines to the header section of `move-cart-items-to-gift-registry.md`.

contributor_name: Atwix
contributor_link: https://www.atwix.com/

2021-05-25 06:49 UTC, khrystynastolbova commented
> @khrystynastolbova This PR looks like it's complete technically. Please add the following lines to the header section of `move-cart-items-to-gift-registry.md`.
> 
> ```
> contributor_name: Atwix
> contributor_link: https://www.atwix.com/
> ```

Done

2021-05-25 13:28 UTC, keharper approved these changes

2021-05-25 13:29 UTC, keharper commented
@magento import code to magento-devdocs/devdocs

2021-05-25 13:31 UTC, magento-engcom-team commented
@keharper the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8929`.

2021-05-25 18:10 UTC, merged