FrontName example link added on Routing topic
magento/devdocs pull request #8934
Opened 2021-05-12 06:47 UTC by rajesh-mage

## Purpose of this pull request

This pull request (PR) FrontName example link added on the Routing topic

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/routing.html

2021-05-12 08:23 UTC, BarnyShergold requested changes
This is good but please can you add this to the 2.3 version of the file. This can be done on this PR.

2021-05-12 08:52 UTC, rajesh-mage commented
> This is good but please can you add this to the 2.3 version of the file. This can be done on this PR.

@BarnyShergold PR changes added on the 2.3 version. Kindly review and let me know If any changes.

Thanks.

2021-05-12 21:07 UTC, atwixfirster commented
Hi, @rajesh-mage !

Honestly, I do not understand where did you get `routesxml` and what is a purpose of this PR?

Example for the `frontName` is provided on [line 229](https://github.com/magento/devdocs/pull/8934/files#diff-48752f91dd12ac1bfae8e6f7413e77590d303cf07ca1ad6b549ddcd31e9e3a2cR229).

CC: @BarnyShergold

2021-05-14 07:37 UTC, rajesh-mage commented
Hi @atwixfirster 
> Hi, @rajesh-mage !
> 
> Honestly, I do not understand where did you get `routesxml` and what is a purpose of this PR?
> 
> Example for the `frontName` is provided on [line 229](https://github.com/magento/devdocs/pull/8934/files#diff-48752f91dd12ac1bfae8e6f7413e77590d303cf07ca1ad6b549ddcd31e9e3a2cR229).

In this PR I have added an example hyperlink to the routes.xml heading on the line of 97. So the user easily knows about the FrontName from the routes.xml heading section.

CC: @BarnyShergold

Thanks.

2021-05-14 07:53 UTC, atwixfirster requested changes

2021-05-14 07:53 UTC, atwixfirster commented on src/guides/v2.4/extension-dev-guide/routing.md
> +## `routes.xml`
Please remove a redundant SPACE

2021-05-14 08:00 UTC, rajesh-mage commented on src/guides/v2.4/extension-dev-guide/routing.md
> +## `routes.xml`
@atwixfirster 
Space removed.

Thanks.

2021-05-14 08:29 UTC, BarnyShergold approved these changes

2021-05-17 20:58 UTC, dobooth approved these changes

2021-05-17 20:59 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-05-17 21:01 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-05-20 13:50 UTC, merged