Extension name format not showing
magento/devdocs pull request #8936
Opened 2021-05-12 11:31 UTC by rajesh-mage

## Purpose of this pull request

This pull request (PR) Extension name format not showing on the Frontend view

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/enable-module.html

2021-05-12 16:02 UTC, BarnyShergold approved these changes
Good fix but you seem to have a conflict on the PR

2021-05-13 12:52 UTC, dobooth commented
@rajesh-mage Yeah, 568 changed files in this PR. Your branch needs updating for sure.

2021-05-13 16:49 UTC, dshevtsov requested changes
Make sure you created your branch from the `master` branch. You can try to rebase your branch onto the latest `master` branch, and force push.

2021-05-14 06:13 UTC, rajesh-mage commented
Hi @dshevtsov @BarnyShergold @dobooth 
Conflict issue resolved.

Thanks.

2021-05-14 08:39 UTC, BarnyShergold approved these changes

2021-05-14 15:00 UTC, dshevtsov requested changes

2021-05-14 15:00 UTC, dshevtsov commented on src/guides/v2.3/extension-dev-guide/build/enable-module.md
> +   An extension name uses the format: VendorName_ComponentName.
We typically use less-than and greater-than signs to indicate placeholders. To make them appear, they should be formatted as code or escaped.

2021-05-15 05:33 UTC, rajesh-mage commented on src/guides/v2.3/extension-dev-guide/build/enable-module.md
> +   An extension name uses the format: VendorName_ComponentName.
Hi @dshevtsov,
Thanks for your review. The requested change is done.

Thanks.

2021-05-15 08:52 UTC, ajithkumar-maragathavel approved these changes
Approved. Looks good for me.

2021-05-17 14:55 UTC, dshevtsov approved these changes

2021-05-17 14:57 UTC, dshevtsov commented
@magento import code to magento-devdocs/devdocs

2021-05-17 14:58 UTC, magento-engcom-team commented
@dshevtsov the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8936`.

2021-05-17 15:30 UTC, merged