magento/devdocs #8928 : Add description about data  import from configuration files
magento/devdocs pull request #8943
Opened 2021-05-17 15:32 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/devdocs/issues/8928

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-deployment.html

## Links to Magento source code

-  https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-config-mgmt-set.html
- https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-config-mgmt-import.html

2021-05-18 13:22 UTC, rogyar requested changes

2021-05-18 13:22 UTC, rogyar commented on src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-deployment.md
> +Use the optional `[-n, --no-interaction]` flag to import data without any interaction.
I would suggest simplifying this statement as follows 

```suggestion
Use the optional `[-n, --no-interaction]` flag to import data without additional confirmations.
```

... and removing the next "If you enter..." sentence

2021-05-18 13:22 UTC, rogyar commented on src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-deployment.md
> +Use the optional `[-n, --no-interaction]` flag to import data without any interaction.
Also, we may put something like 

> For additional information, please, check the [Import data from configuration files](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-config-mgmt-import.html)

2021-05-18 13:22 UTC, rogyar commented
Hi @EvheniiaKolkhiieva. Thank you for your contribution. Please, check my minor suggestions above

2021-05-18 19:44 UTC, EvheniiaKolkhiieva commented
Hi @rogyar, thank you for reviewing.
I have implemented your suggestions, could you please approve?

2021-05-20 09:09 UTC, rogyar approved these changes

2021-05-25 11:55 UTC, dobooth approved these changes

2021-05-25 11:57 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-05-25 11:58 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-06-01 13:30 UTC, merged