Improvements on event observer topic
magento/devdocs pull request #8950
Opened 2021-05-19 08:11 UTC by ajithkumar-maragathavel

## Purpose of this pull request

This pull request (PR) includes the below improvements:

- Added example of subscribing to the custom event.
- Added information on the list of valid areas for observers.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html
-  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/events-and-observers.html

## Links to Magento source code

-  https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/etc/events.xml

2021-05-19 14:57 UTC, BarnyShergold requested changes
Good addition

2021-05-19 14:57 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +Custom event `my_module_event_after` can be subscribed by declaring the `MyCompany/MyModule/etc/events.xml` file like below:
```suggestion
The custom event `my_module_event_after` can be subscribed to by declaring the `MyCompany/MyModule/etc/events.xml` file as below:
```

2021-05-19 14:57 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +Make your observer as specific as it needs to be. Declare your observer in the appropriate area:
The first sentence doesn't add any value to the document.
```suggestion
Declare the observer in the appropriate area:
```

2021-05-19 17:01 UTC, ajithkumar-maragathavel commented
@BarnyShergold Updated the PR with the suggested changes. Thanks

2021-05-24 21:55 UTC, keharper reviewed
@ajithkumar-maragathavel A few editorial comments. The 3rd column of the table isn't necessary since 6 out 7 descriptions vary by one word.

2021-05-24 21:55 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +The custom event `my_module_event_after` can be subscribed to by declaring the `MyCompany/MyModule/etc/events.xml` file as below:
```suggestion
You can make the custom event `my_module_event_after` subscribable by declaring the `MyCompany/MyModule/etc/events.xml` file as below:
```

2021-05-24 21:55 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +| Area | File location | Description |
Delete the Description column.

2021-05-24 21:55 UTC, keharper commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +Declare the observer in the appropriate area:
```suggestion
Declare the observer in the appropriate area. The `global` area allows the observer to run in all areas (`adminhtml`, `crontab`, `frontend`, `graphql`, `webapi_rest`, `webapi_soap`). 
```

2021-05-25 07:06 UTC, ajithkumar-maragathavel commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +The custom event `my_module_event_after` can be subscribed to by declaring the `MyCompany/MyModule/etc/events.xml` file as below:
Updated the PR.

2021-05-25 07:06 UTC, ajithkumar-maragathavel commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +Declare the observer in the appropriate area:
Modifed.

2021-05-25 07:06 UTC, ajithkumar-maragathavel commented on src/guides/v2.3/extension-dev-guide/events-and-observers.md
> +| Area | File location | Description |
Removed the 3rd column.

2021-05-25 07:07 UTC, ajithkumar-maragathavel commented
@keharper Thanks for the suggestions. PR updated.

2021-05-25 22:58 UTC, keharper approved these changes

2021-05-25 22:58 UTC, keharper commented
@magento import code to magento-devdocs/devdocs

2021-05-25 23:01 UTC, magento-engcom-team commented
@keharper the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8950`.

2021-05-25 23:40 UTC, merged