Add information on extension footprint analyzer
magento/devdocs pull request #8962
Opened 2021-05-24 15:21 UTC by ishakhsuvarov

## Purpose of this pull request

This pull request adds information about Extension Footprint analyzer feature of Magento Marketplace. 

## Affected DevDocs pages
-  https://devdocs.magento.com/marketplace/sellers/code-sniffer.html

2021-05-24 15:51 UTC, BarnyShergold requested changes
Nice new addition

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/code-sniffer.md
> +Limited information, like number of errors, warnings and coding standards version used are displayed in the Quality Report section of product lising page on the Magento Marketplace.
```suggestion
Limited information, like the number of errors, warnings and the coding standards version used are displayed in the Quality Report section of product listing page on the Magento Marketplace.
```

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/extension-footprint.md
> +title: Extension Footprint analysys
```suggestion
title: Extension Footprint Analysis
```

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/extension-footprint.md
> +{: .bs-callout .bs-callout-info}Footprint analyzer is currently released as a beta feature meaning that some of the information may not be copletely accurate or present at all. Beta status of the fea
Put text on next line. It should not be on the same line as content in braces.

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/extension-footprint.md
> +{: .bs-callout .bs-callout-info}Footprint analyzer is currently released as a beta feature meaning that some of the information may not be copletely accurate or present at all. Beta status of the fea
```suggestion
{: .bs-callout .bs-callout-info}The footprint analyzer is currently released as a beta feature, meaning that some of the information may not be completely accurate or present at all. Beta status of the feature is also indicated on the product listing page.
```

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/extension-footprint.md
> +Foorptint analysis is an automated check that generates report based on static analysis of the extension code. After processing, reports are visible on the product listing page and include informatio
```suggestion
Footprint analysis is an automated check that generates a report based on the static analysis of the extension code. After processing, reports are visible on the product listing page and include information on certain specific features which provide Magento Marketplace customers insights on extension capabilities from the code perspective.
```

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/extension-footprint.md
> +All extension packages have their footprint analyzed at the time of submissions. This check is not a test and therefore cannot be passed or failed.
```suggestion
All extension packages have their footprint analyzed at the time of submission. This check is not a test and therefore cannot be passed or failed.
```

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/extension-footprint.md
> +At the moment Footptint Analyzer check is performing static package code testing to identify APIs exposed by the module. Report usually consists of the following sections:
```suggestion
At the moment the footprint analyzer check is performed on the static package code to identify APIs exposed by the module. The report usually consists of the following sections:
```

2021-05-24 15:51 UTC, BarnyShergold commented on src/marketplace/sellers/extension-footprint.md
> +*  GraphQL – verifies if extension exposes any GraphQL entities.
```suggestion
*  GraphQL – verifies if the extension exposes any GraphQL entities.
```

2021-05-27 14:12 UTC, jeff-matthews requested changes
Thanks for the new topic @ishakhsuvarov!

I've requested additional changes to get this ready for publication. 

Please also add a new entry for this new topic in the table of contents (TOC) file. It probably makes sense to add it near the existing "Code Sniffer" entry: https://github.com/magento/devdocs/blob/master/src/_data/toc/marketplace-sellers.yml#L110 

Or maybe it makes more sense to add it further down near the "checks" since this footprint analyzer isn't technically a test. What do you think?

2021-05-27 14:12 UTC, jeff-matthews commented on src/marketplace/sellers/code-sniffer.md
> +Limited information, like the number of errors, warnings and the coding standards version used are displayed in the Quality Report section of product listing page on the Magento Marketplace.
```suggestion
Limited information is displayed in the Quality Report section of the product listing page on the Magento Marketplace, including the number of errors, warnings, and the coding standards version that was used.
```

2021-05-27 14:12 UTC, jeff-matthews commented on src/marketplace/sellers/extension-footprint.md
> +{: .bs-callout .bs-callout-info} The footprint analyzer is currently released as a beta feature, meaning that some of the information may not be completely accurate or present at all. Beta status of
```suggestion
{:.bs-callout-info}
The footprint analyzer is a beta feature, meaning that some of the information may not be completely accurate or present at all. The beta status of the feature is also indicated on the product listing page.
```

2021-05-27 14:12 UTC, jeff-matthews commented on src/marketplace/sellers/extension-footprint.md
> +Footprint analysis is an automated check that generates a report based on the static analysis of the extension code. After processing, reports are visible on the product listing page and include info
```suggestion
Footprint analysis is an automated check that generates a report based on the static analysis of the extension code. After processing, reports are visible on the product listing page and include information on certain specific features, which provide Magento Marketplace customers insights on extension capabilities from the code perspective.
```

2021-05-27 14:12 UTC, jeff-matthews commented on src/marketplace/sellers/extension-footprint.md
> +At the moment the footprint analyzer check is performed on the static package code to identify APIs exposed by the module. The report usually consists of the following sections:
```suggestion
At the moment, the footprint analyzer check is performed on the static package code to identify APIs exposed by the module. The report usually consists of the following sections:
```

2021-05-27 14:12 UTC, jeff-matthews commented on src/marketplace/sellers/extension-footprint.md
> +*  Programmatic API and Data interfaces – provides information on the number of programmatic APIs found in the extension code package.
```suggestion
*  Programmatic API and data interfaces—Provides information on the number of programmatic APIs found in the extension code package.
```

2021-05-27 14:12 UTC, jeff-matthews commented on src/marketplace/sellers/extension-footprint.md
> +*  Web API – provides insights on the number of REST and SOAP APIs exposed by the extension package.
```suggestion
*  Web API—Provides insights on the number of REST and SOAP APIs exposed by the extension package.
```

2021-05-27 14:12 UTC, jeff-matthews commented on src/marketplace/sellers/extension-footprint.md
> +*  GraphQL – verifies if the extension exposes any GraphQL entities.
```suggestion
*  GraphQL—Verifies if the extension exposes any GraphQL entities.
```

2021-05-27 14:43 UTC, ishakhsuvarov commented
Thank you for your review and fixes @jeff-matthews 

I've added it TOC as the next entry after semantic version check. I think it's a good place for it since it's still a part of technical review even though it's not a test in traditional meaning.

2021-05-27 14:44 UTC, jeff-matthews approved these changes
Looks good. Thanks @ishakhsuvarov!

2021-05-27 14:44 UTC, jeff-matthews commented
@magento import code to magento-devdocs/devdocs

2021-05-27 14:45 UTC, magento-engcom-team commented
@jeff-matthews the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8962`.

2021-05-27 15:10 UTC, merged