Deployment command change
magento/devdocs pull request #8967
Opened 2021-05-26 10:09 UTC by Renu05

setup:static:deploy to setup:static-content:deploy

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-05-26 10:19 UTC, BarnyShergold requested changes
whilst this is a correct correction, documentation should no longer use "php magento"

As this file in PR, please can you change all instances of "php magento" to "bin/magento"

eg the line changed should read : bin/magento setup:static-content:deploy

Please also complete the PR description full - see WIKI

2021-05-27 04:04 UTC, keharper approved these changes

2021-05-27 04:07 UTC, keharper requested changes
Approved too early. Requesting changes

2021-05-29 10:28 UTC, Renu05 commented
Hi @keharper ,
I have made the changes magento to bin/magento

2021-06-01 13:01 UTC, dobooth requested changes

2021-06-01 13:01 UTC, dobooth commented on src/cloud/before/before-setup-env-install.md
> +   php bin/magento setup:install \
```suggestion
   bin/magento setup:install \
```

We not longer need `php` at the beginning of commands. Please remove the other two as well.

2021-06-25 10:58 UTC, dobooth commented
Closing as abandoned.

2021-06-25 10:58 UTC, closed without merging