Add info about the log rotation on Magento Cloud environment
magento/devdocs pull request #8970
Opened 2021-05-27 13:19 UTC by dmytro-ch

## Purpose of this pull request

This pull request introduces the documentation for log rotation flow on the Cloud environment, including the information about achieved logs files location and other minor improvements.

## Affected DevDocs pages

- https://devdocs.magento.com/cloud/project/log-locations.html

## Links to Magento source code

N/A

2021-05-27 14:25 UTC, BarnyShergold requested changes
Very nice addition!
Just a few grammar corrections

2021-05-27 14:25 UTC, BarnyShergold commented on src/cloud/project/log-locations.md
> +Automatic logs rotation, compression and removal are enabled in the cloud environment. Every type of log file has its own rotating pattern and lifetime.
```suggestion
Automatic log rotation, compression and removal are enabled in the Cloud environment. Every type of log file has its own rotating pattern and lifetime.
```

2021-05-27 14:25 UTC, BarnyShergold commented on src/cloud/project/log-locations.md
> +The application logs are being archived once per day and kept for one year. In order to access the archived logs for the particular day, it is possible to find this file by a unique ID that equals `N
```suggestion
The application logs are archived once per day and kept for one year. In order to access the archived logs for a particular day, it is possible to find the file by a unique ID that equals `Number of Days Ago + 1`.
```

2021-05-27 14:25 UTC, BarnyShergold commented on src/cloud/project/log-locations.md
> +For example, the PHP access log for 21 days back on the Pro production environment can found by the following path:
```suggestion
For example, the PHP access log for 21 days in the past, on the Pro production environment can found by the following path:
```

2021-05-27 14:25 UTC, BarnyShergold commented on src/cloud/project/log-locations.md
> +The archived log files are always stored in the same directory where the original was file before compression.
```suggestion
The archived log files are always stored in the same directory where the original file was located, before compression.
```

2021-05-27 14:25 UTC, BarnyShergold commented on src/cloud/project/log-locations.md
> +**Deploy** and **Post-deploy** log files are not being rotated and archived. The entire deployment history can be found in the same file.
```suggestion
**Deploy** and **Post-deploy** log files are not rotated and archived. The entire deployment history can be found in the same file.
```

2021-05-27 14:25 UTC, BarnyShergold commented on src/cloud/project/log-locations.md
> +Service logs are being archived and saved for different periods of time depending on the log type. The MySQL logs, having the shortest lifetime period, are removed after 7 days.
```suggestion
Service logs are archived and saved for different periods of time depending on the log type. The MySQL logs, having the shortest lifetime period, are removed after 7 days.
```

2021-05-28 06:09 UTC, dmytro-ch commented
Hello @BarnyShergold,
Thank you for the review!
I've applied the requested changes.

2021-06-04 15:48 UTC, bdenham requested changes
Just need a few wording changes. Great additions!

2021-06-04 15:48 UTC, bdenham commented on src/cloud/project/log-locations.md
> +Automatic log rotation, compression and removal are enabled in the Cloud environment. Every type of log file has its own rotating pattern and lifetime.
```suggestion
Automatic log rotation, compression, and removal are enabled in the Cloud environment. Every type of log file has its own rotating pattern and lifetime.
```

2021-06-04 15:48 UTC, bdenham commented on src/cloud/project/log-locations.md
> +For example, the PHP access log for 21 days in the past, on the Pro production environment can found by the following path:
```suggestion
For example, the PHP access log for 21 days in the past, on the Pro production environments, is stored and named as follows:
```

2021-06-04 15:48 UTC, bdenham commented on src/cloud/project/log-locations.md
> +The archived log files are always stored in the same directory where the original file was located, before compression.
```suggestion
The archived log files are always stored in the directory where the original file was located before compression.
```

2021-06-04 15:48 UTC, bdenham commented on src/cloud/project/log-locations.md
> +The application logs are archived once per day and kept for one year. In order to access the archived logs for a particular day, it is possible to find the file by a unique ID that equals `Number of
```suggestion
The application logs are compressed and archived once per day and kept for one year. The compressed logs are named using a unique ID that corresponds to the `Number of Days Ago + 1`.
```

2021-06-04 15:48 UTC, bdenham commented on src/cloud/project/log-locations.md
> +**Deploy** and **Post-deploy** log files are not rotated and archived. The entire deployment history can be found in the same file.
```suggestion
**Deploy** and **Post-deploy** log files are not rotated and archived. The entire deployment history is written within those log files.
```

2021-06-04 15:48 UTC, bdenham commented on src/cloud/project/log-locations.md
> +Service logs are archived and saved for different periods of time depending on the log type. The MySQL logs, having the shortest lifetime period, are removed after 7 days.
```suggestion
Service logs are archived and saved for different periods of time, depending on the log type. For example, MySQL logs have the shortest lifetime—removed after 7 days.
```

2021-06-10 11:15 UTC, dmytro-ch commented
Hello @bdenham,
Thank you for your review!
I've applied the requested changes.

2021-06-10 19:43 UTC, bdenham approved these changes
Looks good! Thanks for the update!

2021-06-10 22:41 UTC, bdenham commented
@magento import code to magento-devdocs/devdocs

2021-06-10 22:42 UTC, magento-engcom-team commented
@bdenham the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-8970`.

2021-06-11 17:00 UTC, merged