Correct inconsistent example of creating a foreign key constraint
magento/devdocs pull request #9001
Opened 2021-06-12 13:05 UTC by markshust

2021-06-13 23:21 UTC, BarnyShergold requested changes
This does not look right. There is no link from the Company Credit Table to the the Directory Country table. I think you have tried to fix this constraint based on the reference ID.

I think the correct correction is to change the reference ID.

If you check the db_schema doc for the company credit table you will see -
```
        <constraint xsi:type="foreign" referenceId="COMPANY_CREDIT_COMPANY_ID_COMPANY_ENTITY_ID"
                    table="company_credit" column="company_id" referenceTable="company" referenceColumn="entity_id"
                    onDelete="CASCADE"/>
```
Please update your PR as needed. You will also need to apply this to the 2.3 version of the file as they are no longer symlinked. Please change the 2.3 file on THIS PR.

Also please fill in the description to the PR as required by the WIKI - you can check other approved PRs to see how this is done.

Thanks!

2021-06-14 13:53 UTC, markshust commented
@BarnyShergold thanks, I found the issue on my mobile device and was too lazy to write a description. I apologize for that, it's all updated. Thanks for your thorough finding of this, I just knew the reference id was incorrect. All updated in both 2.3 and 2.4 versions.

2021-06-14 14:03 UTC, BarnyShergold approved these changes
Thanks!

2021-06-15 19:35 UTC, dobooth approved these changes

2021-06-15 19:36 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-06-15 19:37 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-06-16 14:50 UTC, merged