Incorrect instructions for "reloading ssh config"
magento/devdocs pull request #9019
Opened 2021-06-25 14:23 UTC by marcneubauer

You can't source an ssh config file, it's not for the environment.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-06-25 15:29 UTC, BarnyShergold requested changes
Please correct linting and also properly fill in the PR description as per the requirements - see WIKI

2021-06-25 15:29 UTC, BarnyShergold commented on src/cloud/before/before-workspace-ssh.md
Remove this empty line as well. The double blank line causes linting errors

2021-06-28 08:21 UTC, BarnyShergold approved these changes
Nice!

2021-06-29 11:37 UTC, dobooth approved these changes

2021-06-29 11:38 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-06-29 11:39 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-06-29 13:40 UTC, merged