map directive replaced and configuration step added
magento/devdocs pull request #9022
Opened 2021-06-27 20:04 UTC by ajithkumar-maragathavel

## Purpose of this pull request

This pull request (PR) updates the following changes to the Set up multiple websites with the Nginx page.

- Map directive example is replaced with the $MAGE_RUN_CODE variable.
- Additional steps added to modify the Base URLs for the newly created stores on the Magento admin.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_nginx.html
- https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_nginx.html

## Notes

I have verified the updated Nginx virtual hosts configuration file in my local development environment and I can confirm that the multi-stores are working as expected.

Fixes #6317

2021-06-28 08:24 UTC, BarnyShergold requested changes
Just a few corrections

2021-06-28 08:24 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/multi-site/ms_nginx.md
> +1. Click **Save Config** and save the configuraiton changes.
```suggestion
1. Click **Save Config** and save the configuration changes.
```

2021-06-28 08:24 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/multi-site/ms_nginx.md
> +1. Click **Save Config** and save the configuraiton changes.
```suggestion
1. Click **Save Config** and save the configuration changes.
```

2021-06-28 08:24 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/multi-site/ms_nginx.md
> +You need to update the Base URL for the `french` and the `german` websites on the Magento admin.
```suggestion
It is necessary to update the Base URL for the `french` and the `german` websites in the Magento admin.
```

2021-06-28 08:24 UTC, BarnyShergold commented on src/guides/v2.3/config-guide/multi-site/ms_nginx.md
> +Run the below command to clean the `config` and `full_page` cache.
```suggestion
Run the command below to clean the `config` and `full_page` caches.
```

2021-06-28 09:19 UTC, ajithkumar-maragathavel commented
@BarnyShergold Thanks for the review and suggestions. Updated the PR with the requested changes.

2021-06-28 09:41 UTC, BarnyShergold approved these changes

2021-07-02 14:34 UTC, keharper commented
@ajithkumar-maragathavel I don't understand why you added a step to configure the URLs to `http://german.magento24.com/` and `http://french.magento24.com/`. The instructions already mention `german.mysite.mg` and `french.mysite.mg` many times, but there's no explanation why you'd want to change the addresses to something new in the Admin. Please either correct the addresses or add an explanation of the address mapping.

Also, change all instances of "the Magento admin" to "the Admin"

2021-07-03 06:47 UTC, ajithkumar-maragathavel commented
> @ajithkumar-maragathavel I don't understand why you added a step to configure the URLs to `http://german.magento24.com/` and `http://french.magento24.com/`. The instructions already mention `german.mysite.mg` and `french.mysite.mg` many times, but there's no explanation why you'd want to change the addresses to something new in the Admin. Please either correct the addresses or add an explanation of the address mapping.
> 
> Also, change all instances of "the Magento admin" to "the Admin"

@keharper I tried to set up the multi-website in my local development environment by following the steps mentioned. But I faced a redirection issue while accessing the `german` and `french` websites.

When I try to access the `http://french.magento24.com/` website, Magento redirects to the default store instead of the french store. Then I did some debugging and found that the base URL for the french and german stores is not updated properly.

I thought adding one more step to update the base url would be a good improvement on this topic. That's the reason, I have added one more step.

Please let me know your thoughts on this.

2021-07-22 17:31 UTC, dobooth commented
@keharper

2021-07-28 18:46 UTC, keharper approved these changes

2021-07-28 18:48 UTC, keharper commented
@magento import code to magento-devdocs/devdocs

2021-07-28 18:49 UTC, magento-engcom-team commented
@keharper the branch with code successfully imported into`magento-devdocs/devdocs` repository. Branch name: `imported-magento-devdocs-9022`.

2021-07-28 19:55 UTC, merged