Correct description of Pro integration branch architecture
magento/devdocs pull request #9063
Opened 2021-07-27 13:03 UTC by meker12

Fixes #9062 

## Purpose of this pull request

This pull request corrects information about the number of integration branches for Cloud Pro environments.

## Affected DevDocs pages

-  [Pro develop and deploy workflow](https://devdocs.magento.com/cloud/architecture/pro-develop-deploy-workflow.html#develop)

2021-07-27 13:34 UTC, closed without merging

2021-07-27 13:35 UTC, BarnyShergold requested changes

2021-07-27 13:35 UTC, BarnyShergold commented on src/cloud/architecture/pro-develop-deploy-workflow.md
> +The Integration environment provides a single, base `integration` branch containing your {{site.data.var.ece}} code. You can create one additional, environment branch. This allows for up to two activ
```suggestion
The Integration environment provides a single, base `integration` branch containing your {{site.data.var.ece}} code. You can create one additional environment branch. This allows for up to two active branches deployed to Platform-as-a-Service (PaaS) containers.(PaaS) containers.
```

2021-07-27 13:35 UTC, BarnyShergold commented on src/cloud/architecture/pro-develop-deploy-workflow.md
> +The Integration environment provides a single, base `integration` branch containing your {{site.data.var.ece}} code. You can create one additional, environment branch. This allows for up to two activ
Should this not mention that its one additional active environment? You can have as many inactive environments as you want. Or is this just complicating the docs?

2021-07-30 14:08 UTC, hguthrie commented
@meker12 Just for future reference, can you provide a comment about the reason for closing?

2022-08-01 15:31 UTC, meker12 commented
Clean up branches in public repo. Small updates in this PR incorporated in internal PR.