Don't recommend overriding _isAllowed
magento/devdocs pull request #9079
Opened 2021-08-05 15:58 UTC by mpchadwick

## Purpose of this pull request

Recommend the better way for binding a controller action to an admin resource

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/create-access-control-list-rule.html

## Links to Magento source code

Declaring `ADMIN_RESOURCE` is the better way and is how it's done in core.

https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Tax/Controller/Adminhtml/Tax.php#L23
https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Rss/Controller/Adminhtml/Feed.php#L17
https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Cms/Controller/Adminhtml/Block.php#L15

There's no need to override `_isAllowed` as it will check that const

https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Backend/App/AbstractAction.php#L213

2021-08-06 08:44 UTC, BarnyShergold requested changes
Nice update - just one small change

2021-08-06 08:44 UTC, BarnyShergold commented on src/guides/v2.3/ext-best-practices/tutorials/create-access-control-list-rule.md
> +We can restrict the access to admin controllers by setting the `ADMIN_RESOURCE` const.
Please don't use contractions in text.
```suggestion
We can restrict the access to admin controllers by setting the `ADMIN_RESOURCE` constant.
```

2021-08-09 21:58 UTC, mpchadwick commented
@BarnyShergold Change applied

2021-08-10 08:14 UTC, BarnyShergold approved these changes

2021-08-11 15:43 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-08-11 15:44 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-08-11 16:32 UTC, merged