Add description for issue 28239 fix
magento/devdocs pull request #9084
Opened 2021-08-11 06:44 UTC by mozok

In General fixes add description for https://github.com/magento/magento2/issues/28239
PR https://github.com/magento/magento2/pull/33452

## Purpose of this pull request

Update M2.4.3 release notes.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html

## Links to Magento source code

-  linked PR https://github.com/magento/magento2/pull/33452

2021-08-11 10:33 UTC, BarnyShergold requested changes
Small grammar correction.

2021-08-11 10:33 UTC, BarnyShergold commented on src/guides/v2.4/release-notes/open-source-2-4-3.md
> +*  The image resizing process now process images marked as hidden in admin. Also added `--skip_hidden_images` option to skip hidden images during `catalog:images:resize` command processing. [GitHub-2
```suggestion
*  The image resizing process now processes images marked as hidden in admin. Also added `--skip_hidden_images` option to skip hidden images during `catalog:images:resize` command processing. [GitHub-28239](https://github.com/magento/magento2/issues/28239)
```

2021-08-11 11:03 UTC, mozok commented on src/guides/v2.4/release-notes/open-source-2-4-3.md
> +*  The image resizing process now process images marked as hidden in admin. Also added `--skip_hidden_images` option to skip hidden images during `catalog:images:resize` command processing. [GitHub-2
Thanks for review

2021-08-12 09:17 UTC, BarnyShergold approved these changes

2021-08-19 10:33 UTC, dobooth approved these changes

2021-08-19 10:33 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-08-19 10:34 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-08-24 13:35 UTC, Den4ik approved these changes

2021-08-24 14:00 UTC, merged

2021-08-25 06:04 UTC, mozok commented
@BarnyShergold @dobooth Hi.
This PR has mistake. Referred fix (https://github.com/magento/magento2/pull/33452) was merged before release, but was not included in 2.4.3 release tag. It turns out I've mistakenly added information about fix on release page.
Also this comment https://github.com/magento/magento2/issues/28239#issuecomment-889023072 not quite true.

Should I create new PR to remove wrong info, or create revert of current PR?

2021-08-25 09:47 UTC, Den4ik commented
@gabrieldagama Could you explain why https://github.com/magento/magento2/pull/33452 not released with 2.4.3?

2021-08-25 09:57 UTC, mozok commented
Also I was noted, that there is no changes in https://github.com/magento/magento2/blob/2.4.3/app/code/Magento/MediaStorage/Console/Command/ImagesResizeCommand.php 
associated with https://github.com/magento/magento2/pull/33452/files

2021-08-25 10:16 UTC, gabrieldagama commented
> @gabrieldagama Could you explain why [magento/magento2#33452](https://github.com/magento/magento2/pull/33452) not released with 2.4.3?

This was merged 27 days ago. Internally we have had branch cut off before that, this is necessary for the regression process. It will be released on 2.4.4.

2021-08-25 10:51 UTC, Den4ik commented
Thanks for information. @mozok i think we should revert this commit

2021-08-25 14:32 UTC, mozok commented
@Den4ik ok
I don't see usual 'Revert' option near commit message https://github.com/magento/devdocs/pull/9084#event-5200843704
Should I create new PR and delete text, that was added in this PR?

2021-08-25 14:44 UTC, Den4ik commented
@mozok Yep, I mean create PR with revert commit