Suggested update to sentence mistake
magento/devdocs pull request #9150
Opened 2021-09-22 19:28 UTC by df2k2

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-09-23 09:33 UTC, BarnyShergold requested changes
The change is fine, but please complete the PR description as required by the WIKI

2021-09-29 18:22 UTC, dobooth approved these changes

2021-09-29 18:23 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-09-29 18:23 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-09-29 20:27 UTC, merged