Add disable Google reCAPTCHA for Admin panel Reset Password page from command-line
magento/devdocs pull request #9170
Opened 2021-10-03 16:42 UTC by ravi-chandra3197

## Purpose of this pull request

This pull request (PR) ...
disable Google reCAPTCHA for Admin panel Reset Password page from command-line
## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/security/google-recaptcha.html

## Links to Magento source code

-  ...

2021-10-03 23:58 UTC, BarnyShergold requested changes

2021-10-03 23:58 UTC, BarnyShergold commented on src/guides/v2.4/security/google-recaptcha.md
> +Can disable Google reCAPTCHA for Admin panel Reset Password page from command-line:
```suggestion
You can also disable Google reCAPTCHA for Admin panel Reset Password page from the command line:
```

2021-10-04 09:15 UTC, ravi-chandra3197 commented
Hello @BarnyShergold 
Thank you for a suggestion I have update PR as per your suggestion could you please review it?

2021-10-04 17:50 UTC, dobooth approved these changes

2021-10-04 17:51 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-10-04 17:51 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-10-06 18:22 UTC, merged