Added description for reindex in parallel mode command
magento/devdocs pull request #9208
Opened 2021-10-20 16:00 UTC by nitish-ranjan05

## Purpose of this pull request

This pull request helps users to understand reindex in parallel mode command

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-index.html
- https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-index.html

## Description

- Added commands and description for `Reindex in parallel mode`

whatsnew
Added the 'Reindex in parallel mode` section to the [Manage the indexers](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-index.html) topic.

2021-11-03 14:41 UTC, dobooth requested changes

2021-11-03 14:41 UTC, dobooth commented on src/guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
> +Index parallelization can affect only the indexers which are scoped, which means Magento split the data into multiple tables by indexer as its scope instead of keeping all data in one table.
Perhaps this could explained a bit more. Define 'scoped' a bit and how that determines how the data is broken up.

2021-11-15 16:38 UTC, dobooth approved these changes

2021-11-15 16:40 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-11-15 16:41 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-11-15 18:24 UTC, merged