Indexer mode information callout
magento/devdocs pull request #9256
Opened 2021-11-19 13:11 UTC by bjornmeat

Customer_grid index is not supporting on schedule mode. This often leads to confusion. Adding link and info.

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-11-22 10:09 UTC, BarnyShergold requested changes
This change also needs to be applied to the 2.3 version of this file. This can be done on this PR.

2021-11-22 10:09 UTC, BarnyShergold commented on src/guides/v2.4/performance-best-practices/configuration.md
> +{:.bs-callout-info} Currently not all indexers support **Update on Schedule** mode.Please review https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing.html for which modes can be used
Links must be added in correct Markdown format.
```suggestion
    {:.bs-callout-info} Currently not all indexers support **Update on Schedule** mode. Please review [the indexing guide]({{ page.baseurl }}/extension-dev-guide/indexing.html) for which modes can be used with the different indexers.
```

2021-12-07 13:16 UTC, dobooth commented
Hi @bjornmeat. Any updates here?

2021-12-14 11:01 UTC, BarnyShergold commented
@dobooth - What do you want to do with this PR? If we close it, is it important enough to  create another PR that can be dealt with?

2021-12-14 16:31 UTC, dobooth commented
@BarnyShergold I think we should have the content. Closing this PR as abandoned.

2021-12-14 16:31 UTC, closed without merging