Update multiple consumers info
magento/devdocs pull request #9259
Opened 2021-11-23 00:02 UTC by vzabaznov

Update information that multiple consumers should be used only with RabbitMQ

## Purpose of this pull request

This pull request (PR) ...

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2021-11-23 10:01 UTC, BarnyShergold requested changes
Please also add this to the 2.3 version of the file - this can be done on this PR.
Please complete the PR description as required in the WIKI

2021-11-23 10:01 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/mq/manage-message-queues.md
> +   We do not recommned to run multiple consumers on Mysql operated queue. See [`how to change queue from Mysql to Rabbit`]({{ page.baseurl }}/guides/v2.3/extension-dev-guide/message-queues/message-qu
```suggestion
   We do not recommend running multiple consumers on a Mysql operated queue. See [`how to change queue from Mysql to Rabbit`]({{ page.baseurl }}/guides/v2.3/extension-dev-guide/message-queues/message-queues.html#change-message-queue-from-mysql-to-amqp)
```

2021-12-01 23:47 UTC, vzabaznov commented
this functionality is not tested and might not work for 2.3.x

2021-12-07 13:17 UTC, dobooth approved these changes

2021-12-07 13:17 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-12-07 13:18 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-12-10 15:49 UTC, merged