Updated rev share and subscription sales report verbiage under Manage Sales and Revenue Share pages
magento/devdocs pull request #9266
Opened 2021-11-29 14:50 UTC by igorin

… Sales and Revenue Share

## Purpose of this pull request

This pull request (PR) updates the revenue share percentages, and includes mentions of subscription sales transactions under Manage Sales.

## Affected DevDocs pages

- [Revenue Share](https://devdocs.magento.com/marketplace/sellers/revenue-share.html)
- [Manage Sales] (https://devdocs.magento.com/marketplace/sellers/sales.html)

2021-11-29 16:12 UTC, BarnyShergold approved these changes
Just one suggestion but in case you feel it needs to stand then I'll approve.

2021-11-29 22:20 UTC, igorin commented on src/marketplace/sellers/revenue-share.md
> +All Commerce Marketplace sales are subject to a 85/15 revenue share split, with 85% of the revenue for the provider and 15% for Adobe. Sales subject to the revenue share include both paid extensions
let's keep it as is for now and enjoy the extra SEO for "Marketplace Subscriptions"

2021-11-30 17:24 UTC, jeff-matthews requested changes

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +While submitting a new extension to the marketplace, you need to select the Pricing Model for the extension. The Pricing model can only be selected when the initial version is being set up. Once the
```suggestion

When submitting a new extension to the marketplace, you must select the pricing model for the extension. The pricing model can only be selected when the initial version is being set up. After the initial version is created on the Developer Portal, the pricing model cannot be changed for this SKU. Choose Subscription to set the SKU under subscription license, and set the subscription price.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +You may elect to change licensing for their existing extension from Flat Fee to Subscription. In order to do so, you will need to remove their original extension from the Marketplace and replace it w
```suggestion

You may elect to change licensing for an existing extension from Flat Fee to Subscription. In order to do so, you must remove the original extension from the Marketplace and replace it with a new SKU sold under a subscription license.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +You can then either remove the original extension unconditionally, or mark the new extension as a replacement. This will trigger a 180-day grace period for merchants who have purchased the original e
```suggestion
You can then either remove the original extension unconditionally, or mark the new extension as a replacement. This triggers a 180-day grace period for merchants who have purchased the original extension.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +To make that choice, use the "Remove from Store" button on your original extension.
```suggestion
To remove an extension from the Marketplace, use the **Remove from Store** button on your original extension.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +**Important:** once the extension is removed from the Marketplace, the customers will still be able to download the latest version of the module, but you will no longer be able to submit new versions
```suggestion
{:.bs-callout-warning}
After the extension is removed from the Marketplace, customers will still be able to download the latest version of the module, but you will no longer be able to submit new versions. Plan your rollout accordingly.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +**Note:** the grace period will only apply if the replacement extension is a subscription extension.
```suggestion
{:.bs-callout-info}
The grace period only applies if the replacement extension is a subscription extension.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +You can change your extension price every time you submit a new version of your extension.
```suggestion

You can change your extension price every time you submit a new version of your extension.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +Pricing model cannot be changed once at least one version of the extension is initially created on the DevPortal.
```suggestion
Pricing model cannot be changed after at least one version of the extension is initially created on the Developer Portal.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +The existing customers will be notified that the price of the extension has been changed.
```suggestion
Existing customers will be notified that the price of the extension has changed.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +You can see the subscription sales as a regular transactions in the Developer Portal. We are working on improving developer sales tracking functionality and will update documentation when it will be
```suggestion

You can see subscription sales as regular transactions in the Developer Portal. We are working on improving developer sales tracking functionality and will update documentation when it's ready.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +A customer who purchased an extension under a subscription license can request a refund within 25 days. The customer will need to open a Support ticket for this request.
```suggestion

A customer who purchased an extension under a subscription license can request a refund within 25 days. The customer must open a Marketplace Support ticket for this request.
```

2021-11-30 17:24 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +**Important:** Customers can only re-subscribe to a cancelled extension subscription once. Repeated cancellations and re-subscriptions to an extension are not supported.
```suggestion
{:.bs-callout-info}
Customers can only re-subscribe to a cancelled extension subscription once. Repeated cancellations and re-subscriptions to an extension are not supported.
```

2021-11-30 18:22 UTC, igorin commented
Committed all changes - thanks @jeff-matthews for the review!

2021-11-30 18:25 UTC, igorin commented on src/marketplace/sellers/subscriptions/subscriptions.md
> +redirect_from: /marketplace/sellers/subscriptions/subscriptions.html
how about I rename the file to extension-subscriptions.md and redirect to it from /subscriptions/extension-subscriptions.html?

2021-11-30 18:33 UTC, jeff-matthews commented
@igorin, there are actually a bunch more. GitHub collapses them after they reach a certain number. I recommend going to the **Files changed** tab at the top of the PR page and adding all suggestions to "batch".

2021-11-30 18:43 UTC, jeff-matthews commented on src/marketplace/sellers/subscriptions/subscriptions.md
> +redirect_from: /marketplace/sellers/subscriptions/subscriptions.html
renaming it works for me. remove the redirect. it's not necessary for new, unpublished files.

2021-11-30 18:51 UTC, igorin commented on src/marketplace/sellers/subscriptions/selling-subscriptions.md
> +**Important:** once the extension is removed from the Marketplace, the customers will still be able to download the latest version of the module, but you will no longer be able to submit new versions
Resolved

2021-11-30 19:00 UTC, jeff-matthews approved these changes
well done! thanks for the PR @igorin. i'll import into the delivery repo and merge.

2021-11-30 20:02 UTC, merged