Updated PHPStorm UCT related info after the last release
magento/devdocs pull request #9267
Opened 2021-11-29 15:08 UTC by bohdan-harniuk

## Purpose of this pull request

This pull request (PR) updates information about UCT feature after the last release of the PHPStorm plugin for the Magento 2.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/ext-best-practices/phpstorm/built-in-upgrade-compatibility-tool.html

2021-11-29 16:14 UTC, BarnyShergold requested changes
One small change

2021-11-29 16:14 UTC, BarnyShergold commented on src/guides/v2.3/ext-best-practices/phpstorm/built-in-upgrade-compatibility-tool.md
> +There are types of inspections that are covered by this MVP version:
```suggestion
There are three types of inspections that are covered by this MVP version:
```

2021-11-29 16:18 UTC, bohdan-harniuk commented on src/guides/v2.3/ext-best-practices/phpstorm/built-in-upgrade-compatibility-tool.md
> +There are types of inspections that are covered by this MVP version:
Thank you! I've done it.

2021-11-30 20:34 UTC, bohdan-harniuk commented
Hello, @BarnyShergold!

Could you please proceed with the review?

Thanks, 
Bohdan

2021-12-01 14:50 UTC, BarnyShergold approved these changes
Great!

2021-12-03 07:42 UTC, bohdan-harniuk commented
Hello, @BarnyShergold!

If it is okay, why it is not merged?

Thanks, Bohdan

2021-12-03 11:46 UTC, dobooth approved these changes

2021-12-03 11:46 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-12-03 11:48 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-12-03 14:16 UTC, merged