Add section about inspecting compressed data
magento/devdocs pull request #9278
Opened 2021-12-02 14:58 UTC by uglide

## Purpose of this pull request

This pull request (PR) adds a section on how to easily inspect compressed Session and Cache data stored in Redis.
 This task is quite common for Magento developers and this is now supported out of the box in Open Source Redis GUI
More details are here: https://github.com/uglide/RedisDesktopManager/issues/5028

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-session.html
- https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html

2021-12-03 14:17 UTC, BarnyShergold requested changes
One small change
Plus @dobooth is it okay to suggest external application to be installed?

2021-12-03 14:17 UTC, BarnyShergold commented on src/_includes/config/redis-verify.md
> +### Inspect Compressed Sesssion data and Page Cache with GUI tool
```suggestion
### Inspect Compressed Session data and Page Cache with GUI tool
```

2021-12-07 13:22 UTC, dobooth approved these changes

2021-12-07 13:22 UTC, dobooth commented
It's ok to recommend a 3rd party tool.

2021-12-07 13:23 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2021-12-07 13:24 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-12-10 16:22 UTC, merged