define provider for custom checkout form
magento/devdocs pull request #9298
Opened 2021-12-26 18:30 UTC by rsamartino

## Purpose of this pull request

This pull request (PR) fixes a 'this.source is undefined' error when submitting the custom form that is created when following the tutorial on this DevDocs page

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_form.html

2021-12-26 18:30 UTC, magento-engcom-team commented
@rsamartino thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2022-01-05 09:58 UTC, BarnyShergold requested changes
Change is good but there is a linting error later in the file.

Please change -
**A plugin can add custom fields definitions to layout at run-time.**
to
**A plugin can add custom fields definitions to layout at run time.**

2022-01-05 16:46 UTC, dobooth approved these changes

2022-01-05 16:46 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2022-01-05 16:47 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2022-01-05 18:09 UTC, merged