Github issue 8304: remove obsolete sample payment module from payment pages
magento/devdocs pull request #9316
Opened 2022-01-09 12:40 UTC by Viper9x

Fixes #8304
Remove obsolete sample payment module from payment pages

## Purpose of this pull request

Remove obsolete sample payment module from payment pages

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/payments-integrations/base-integration/integration-intro.html
- https://devdocs.magento.com/guides/v2.4/payments-integrations/base-integration/module-configuration.html
- https://devdocs.magento.com/guides/v2.3/payments-integrations/base-integration/integration-intro.html
- https://devdocs.magento.com/guides/v2.3/payments-integrations/base-integration/module-configuration.html

2022-01-10 00:56 UTC, keharper requested changes
@Viper9x I'm putting a block on this PR before someone else merges it.

The links to the dead repo were left in the docs on purpose. They provide a skeleton of what you need to develop a payment module.

I need to ask around to determine the next step. Most likely, I'll ask you to back out these changes and add a note stating the linked repo contains unsupported code.

Semi-related PR: https://github.com/magento/devdocs/pull/7417

2022-01-10 13:05 UTC, Viper9x commented
thanks @keharper
Total agree, I think it would better if we can keep the link to sample module for reference, and add a note to say the module is now not supported.

2022-01-10 22:48 UTC, keharper requested changes
@Viper9x We'll keep the links to the old repo.

2022-01-10 22:48 UTC, keharper commented on src/guides/v2.3/payments-integrations/base-integration/integration-intro.md
> -To simplify the development of a new payment integration, Magento developed the [Payment sample module](https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway).
Revert this deletion and change it to something like

{:.bs-callout-info}
You can also view the [Payment sample module](https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway) in the `magento/magento2-samples` 
 repository to understand the underlying principles.  However, be aware that this code is NOT supported.

2022-01-10 22:48 UTC, keharper commented on src/guides/v2.3/payments-integrations/base-integration/module-configuration.md
> -You can use the [sample Magento_SamplePaymentGateway module](https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway) files as basis for your custom module structure and
Revert this deletion and replace with something like:

{:.bs-callout-info}
You can use the [sample Magento_SamplePaymentGateway module](https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway) files as the basis for your custom module structure and files. However, be aware that this code is NOT supported.

2022-01-13 15:54 UTC, keharper approved these changes

2022-01-13 15:55 UTC, keharper commented
@magento import pr to magento-devdocs/devdocs

2022-01-13 15:57 UTC, m2-github-services commented
@keharper the Pull Request is successfully imported.

2022-01-20 21:12 UTC, merged