Fix path for "Send Emails To" config
magento/devdocs pull request #9342
Opened 2022-01-31 14:51 UTC by makzef

## Purpose of this pull request

This pull request (PR) fixes a typo in config path for "Send Emails To" setting.  
In devdocs was `contact/contact/recipient_email` path, which is not exists. The correct one is `contact/email/recipient_email`.

<img width="1096" alt="Знімок екрана 2022-01-31 о 16 43 51" src="https://user-images.githubusercontent.com/20201927/151814599-5bd1feeb-cd7a-4b29-a5a8-5e11d8fe01f0.png">

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-most.html

## Fixed Issues (if relevant)  

Fixes  magento/magento2#35003

2022-02-01 10:21 UTC, BarnyShergold approved these changes
This is a good fix but also needs to be applied to the 2.3 version of this file (I checked)
Please can you also update this file on this PR, then it can be approved

2022-02-01 10:21 UTC, BarnyShergold requested changes
Approved in error

2022-02-01 11:24 UTC, makzef commented
> This is a good fix but also needs to be applied to the 2.3 version of this file (I checked) Please can you also update this file on this PR, then it can be approved

@BarnyShergold Hello) I added changes you mentioned and updated PR. Thank you!

2022-02-02 11:33 UTC, dobooth approved these changes

2022-02-02 11:34 UTC, dobooth commented
Good eye, @makzef!

2022-02-02 11:34 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2022-02-02 11:35 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2022-02-04 13:45 UTC, BarnyShergold approved these changes
Thank you!

2022-02-07 15:54 UTC, merged