Add example of setting default values
magento/devdocs pull request #9370
Opened 2022-02-23 21:41 UTC by mpchadwick

## Purpose of this pull request

This details how to set default value's for system.xml fields, which is not currently covered in this doc.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-systemxml.html

## Links to Magento source code

- https://github.com/magento/magento2/blob/2.4.3-p1/app/code/Magento/Catalog/etc/config.xml

2022-02-24 16:58 UTC, BarnyShergold requested changes
The addition is fine but you have some linting errors

2022-02-25 12:48 UTC, dobooth approved these changes

2022-02-25 13:17 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2022-02-25 13:18 UTC, m2-github-services commented
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-mpchadwick-devdocs-9370`.

2022-02-25 14:11 UTC, merged