Patch 2
magento/devdocs pull request #9373
Opened 2022-03-01 15:52 UTC by chris-pook

## Purpose of this pull request

This pull request updates the example controller code to use best practise, eliminating the need for DI via __constructor.

## Affected DevDocs pages

https://devdocs.magento.com/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.html
https://devdocs.magento.com/guides/v2.4/ext-best-practices/extension-coding/example-module-adminpage.html

2022-03-01 15:52 UTC, magento-engcom-team commented
@chris-pook thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2022-03-08 17:16 UTC, BarnyShergold requested changes

2022-03-21 17:53 UTC, dobooth commented
Closing as abandoned. Please reopen if needed.

2022-03-21 17:53 UTC, closed without merging

2022-03-21 20:58 UTC, chris-pook commented
Hi @dobooth , ok to reopen please? Pretty sure the code is fine and represents best practise here. I've replied to @BarnyShergold .