Update site-wide-analysis.md
magento/devdocs pull request #9378
Opened 2022-03-07 19:47 UTC by valdislav

## Purpose of this pull request

Update documentation for Site-Wide Analysis Tool an agent. Fix systemd configuration.

## Affected DevDocs pages

[

-  ...](https://devdocs.magento.com/tools/site-wide-analysis.html)

2022-03-07 19:47 UTC, magento-engcom-team commented
@valdislav thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2022-03-07 22:53 UTC, yvoronoy commented
@valdislav and @jeff-matthews Engineering CR Passed, we should be good to proceed and merge
Thank you!

2022-03-07 22:57 UTC, jeff-matthews requested changes

2022-03-07 22:57 UTC, jeff-matthews commented on src/tools/site-wide-analysis.md
> +1. Create a systemd unit file (`/etc/systemd/system/scheduler.service`) with the following configuration. (Replace `<filesystemowner>` with unix user owner of /path/to/agent directory)
```suggestion
1. Create a systemd unit file (`/etc/systemd/system/scheduler.service`) with the following configuration (replace `<filesystemowner>` with the Unix user that owns the directory where the agent is installed).
```

2022-03-08 17:14 UTC, jeff-matthews approved these changes

2022-03-08 17:14 UTC, jeff-matthews commented
@magento import code to magento-devdocs/devdocs

2022-03-08 17:15 UTC, m2-github-services commented
@jeff-matthews the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-valdislav-devdocs-9378`.

2022-03-08 17:52 UTC, merged