Varnish ESI Block
magento/devdocs pull request #9380
Opened 2022-03-09 00:07 UTC by goivvy

## Purpose of this pull request

This pull request (PR) explains how to use ESI with Varnish on Magento 2

Fixes https://github.com/magento/devdocs/issues/9134

## Affected DevDocs pages

## Links to Magento source code

2022-03-10 10:48 UTC, BarnyShergold requested changes
Great new topic! Just a few small grammar issues to correct.

2022-03-10 10:48 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/varnish/use-varnish-esi.md
> +Varnish will fetch content from `http://domain.com/index.php/page_cache/block/esi/blocks` and put it in place of `esi` tag.
```suggestion
Varnish will fetch content from `http://domain.com/index.php/page_cache/block/esi/blocks` and put it in place of the `esi` tag.
```

2022-03-10 10:48 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/varnish/use-varnish-esi.md
> +In the example above content from `esi.phtml` will be added to a homepage and will be automatically updated by Varnish every 30 seconds.
```suggestion
In the example above, content from `esi.phtml` will be added to a homepage and will be automatically updated by Varnish every 30 seconds.
```

2022-03-10 10:48 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/varnish/use-varnish-esi.md
> +Currently, Varnish doesn't support ESI over https so Magento 2 will automatically switch to http.
Please don't use contractions
```suggestion
Currently, Varnish does not support ESI over HTTPS so Magento 2 will automatically switch to HTTP.
```

2022-03-10 10:48 UTC, BarnyShergold commented on src/guides/v2.4/config-guide/varnish/use-varnish-esi.md
> +        // Varnish does not support ESI over HTTPS must change to HTTP
```suggestion
        // Varnish does not support ESI over HTTPS, must change to HTTP
```

2022-03-10 16:26 UTC, goivvy commented
@BarnyShergold corrected.

2022-03-14 16:56 UTC, BarnyShergold approved these changes
Excellent

2022-03-15 15:27 UTC, dobooth commented
Thanks for the excellent contribution, @goivvy. One more thing if you would. We generally symlink upwards: 2.3 as content, 2.4 symlinked. Can you please reverse your topic/symlink?

2022-03-16 19:04 UTC, goivvy commented
@dobooth @BarnyShergold fixed.

2022-03-18 12:26 UTC, dobooth approved these changes

2022-03-18 12:28 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2022-03-18 12:29 UTC, m2-github-services commented
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-goivvy-devdocs-9380`.

2022-03-22 19:20 UTC, merged