Add message that grid snapshots are not automated.
magento/devdocs pull request #9428
Opened 2022-04-29 16:38 UTC by akester

## Purpose of this pull request

This adds a message that snapshots on integration and starter environments are not automatically taken, and that it's the customer's reasonability to take these.  This isn't called out clearly and may cause headaches if customers expect some form of automated backups.

## Affected DevDocs pages

-  https://devdocs.magento.com/cloud/project/project-webint-snap.html

2022-04-29 16:48 UTC, akester commented
Just pointing out that I'm a Platform.sh employee, so I'm not 100% Sure of the correct procedure regarding the CLA.  If there's something different I need to do please let me know or ping me on slack.

2022-04-29 18:43 UTC, hguthrie requested changes
Thank you for suggesting this clarification! I made some changes to be very clear, especially since this section follows a paragraph about Pro backups.
Thanks!

2022-04-29 18:43 UTC, hguthrie commented on src/cloud/project/project-webint-snap.md
> +Snapshots for Starter and Pro Integration environments are not taken automatically.  It is the your responsibility to take manual snapshots or setup a con job to automatically take snapshots for thes
```suggestion
Snapshots for Starter and Pro Integration environments are different from Pro backup and disaster recovery backups. Snapshots are **not** automatic. It is _your_ responsibility to manually create a snapshot or set up a con job to periodically take snapshots of your Starter or Pro Integration environments.
```

2022-04-29 18:43 UTC, hguthrie commented on src/cloud/project/project-webint-snap.md
> +{:.bs-callout-warning}
This suggestion is optional, but what if we present this as a tip? There is a suggestion here about setting up a cron job and I think it's a really good candidate for a positive Tip with a green checkmark.

```suggestion
{:.bs-callout-tip}
```

2022-05-04 15:22 UTC, akester commented
Changes have been made.

2022-05-04 16:15 UTC, hguthrie approved these changes

2022-05-05 19:42 UTC, hguthrie commented
@magento import code to magento-devdocs/devdocs

2022-05-05 19:43 UTC, m2-github-services commented
@hguthrie the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-akester-magento-devdocs-9428`.

2022-05-11 19:14 UTC, merged