Encode "<" as "&lt;"
magento/devdocs pull request #9440
Opened 2022-05-17 21:25 UTC by outis

Fix for #9439.

## Purpose of this pull request

Fix for #9439.

## Affected DevDocs pages

-  ...

## Links to Magento source code

-  ...

2022-05-18 14:15 UTC, BarnyShergold requested changes
Please sign CLA
Please update PR description as per WIKI requirements

2022-05-25 19:52 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2022-05-25 19:52 UTC, dobooth approved these changes

2022-05-25 19:53 UTC, m2-github-services commented
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-outis-devdocs-9440`.

2022-06-10 17:42 UTC, jeff-matthews reviewed
Thanks for the contribution @outis ! We recently moved the 2.4 version of this page to another site and GitHub repo. This change will only affect version 2.3. Would you be willing to open a PR in the new repo with this change for the latest version?

- **site:** https://developer.adobe.com/commerce/php/coding-standards/js/
- **repo:** https://github.com/AdobeDocs/commerce-php/blob/main/src/pages/coding-standards/js.md

2022-06-10 23:17 UTC, outis commented
> This change will only affect version 2.3. Would you be willing to open a PR in the new repo with this change for the latest version?

I'll take a look at it.

2022-06-20 10:31 UTC, merged

2022-06-20 18:47 UTC, outis commented
The issue no longer exists in the commerce-php [docblock coding standard](https://github.com/AdobeDocs/commerce-php/blob/main/src/pages/coding-standards/js-docblock.md). It's been rewritten quite a bit since the Magento versions.