Cleared a wrong comment regarding path repository support
magento/devdocs pull request #9442
Opened 2022-05-18 18:13 UTC by barbazul

## Purpose of this pull request

Clarify support of the Path repository type

## Affected DevDocs pages

[The composer.json file(https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/composer-integration.html)

2022-05-19 09:25 UTC, BarnyShergold requested changes
Please also add the page URL to the PR description

2022-05-19 09:25 UTC, BarnyShergold commented on src/guides/v2.3/extension-dev-guide/build/composer-integration.md
> +Magento does not support the [`path`][3] repository pointing to a folder outside of Magento root.
```suggestion
Magento does not support the [`path`][3] repository pointing to a folder outside of the Magento root.
```

2022-05-19 21:06 UTC, barbazul commented
> Please also add the page URL to the PR description

It's already there. What am I missing?

2022-05-28 10:15 UTC, barbazul commented
No pending requested changes

2022-06-06 14:58 UTC, barbazul commented
@BarnyShergold

2022-06-10 10:30 UTC, BarnyShergold approved these changes
Apologies for the delay

2022-06-10 17:39 UTC, jeff-matthews reviewed
Thanks for the contribution @barbazul! We recently moved the 2.4 version of this page to another site and GitHub repo. This change will only affect version 2.3. Would you be willing to open a PR in the new repo with this change?

- **site:** https://developer.adobe.com/commerce/php/development/build/composer-integration/
- **repo:** https://github.com/AdobeDocs/commerce-php/blob/main/src/pages/development/build/composer-integration.md

2022-06-12 20:37 UTC, barbazul commented
> Thanks for the contribution @barbazul! We recently moved the 2.4 version of this page to another site and GitHub repo. This change will only affect version 2.3. Would you be willing to open a PR in the new repo with this change?
> 
>     * **site:** https://developer.adobe.com/commerce/php/development/build/composer-integration/
> 
>     * **repo:** https://github.com/AdobeDocs/commerce-php/blob/main/src/pages/development/build/composer-integration.md

Here  you go: https://github.com/AdobeDocs/commerce-php/pull/22

2022-06-20 09:51 UTC, dobooth approved these changes

2022-06-20 09:52 UTC, dobooth commented
@magento import pr to magento-devdocs/devdocs

2022-06-20 09:53 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2022-06-20 10:31 UTC, merged