fix nginx version in system requirement
magento/devdocs pull request #9456
Opened 2022-06-02 20:27 UTC by lalittmohan

## Purpose of this pull request

This pull request (PR) fix Nginx version on system requirement page

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html
- https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements.html

## Links to Magento source code

- N/A

2022-06-08 09:08 UTC, BarnyShergold requested changes

2022-06-08 09:08 UTC, BarnyShergold commented on src/_data/codebase/v2_4/system-requirements.yml
> +
Remove all empty lines that were added to this file

2022-06-08 12:30 UTC, lalittmohan reviewed
fix space

2022-06-10 10:26 UTC, BarnyShergold approved these changes
All good! Thanks

2022-06-10 17:34 UTC, jeff-matthews reviewed
Thanks @lalittmohan. I just need to confirm with internal staff before merging.

2022-06-21 13:11 UTC, dobooth approved these changes

2022-06-21 13:11 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2022-06-21 13:13 UTC, m2-github-services commented
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-lalittmohan-devdocs-9456`.

2022-06-21 17:21 UTC, merged