targetWidget parameter and return was missing
magento/devdocs pull request #9464
Opened 2022-06-10 08:57 UTC by jasperzeinstra

## Purpose of this pull request

As stated in https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_mixins.html#examples, when writing a mixin for jQuery widgets you should have a parameter "targetWidget" and also return a jQuery widget. In this case about adding validation rules we don't change the targetWidget, so we should just return this. Not returning the targetWidget will throw a JS error.

## Affected DevDocs pages

- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/validations/custom-validation.html
- https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/validations/custom-validation.html

2022-06-10 10:26 UTC, BarnyShergold requested changes
You have linting errors on Line 50 - I've made the suggestion to fix

2022-06-10 10:26 UTC, BarnyShergold commented on src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
> +
```suggestion

```

2022-08-02 16:38 UTC, dobooth commented
Got confirmation from the dev guild.

2022-08-02 16:38 UTC, dobooth commented
@magento import code to magento-devdocs/devdocs

2022-08-02 16:39 UTC, m2-github-services commented
@dobooth the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-jasperzeinstra-devdocs-9464`.

2022-08-02 17:03 UTC, dobooth commented
Fixed in https://github.com/AdobeDocs/commerce-frontend-core/pull/31

2022-08-02 17:03 UTC, closed without merging