ACP2E-954: Fixed the invalid filter definition for FilterMatchTypeInput
magento/devdocs pull request #9473
Opened 2022-06-27 02:32 UTC by kavingas

## Purpose of this pull request

This pull request (PR) ACP2E-954: Fixed the invalid filter definition for FilterMatchTypeInput

## Affected DevDocs pages
- https://devdocs.magento.com/guides/v2.3/graphql/custom-filters.html

2022-06-27 11:30 UTC, BarnyShergold requested changes
Please also sign the Adobe CLA

2022-06-27 11:30 UTC, BarnyShergold commented on src/guides/v2.3/graphql/custom-filters.md
> +-  `FilterMatchTypeInput` - Specify this data type when the **Catalog Input Type for Store Owner** field for your custom attribute is set to Text Field or Text Area. Your filter must contain the `mat
```suggestion
-  `FilterMatchTypeInput` - Specify this data type when the **Catalog Input Type for Store Owner** field for your custom attribute is set to Text Field or Text Area. Your filter must contain the `match` attribute, which will define a filter that performs a fuzzy search.
```

2022-07-05 02:40 UTC, kavingas commented
> Please also sign the Adobe CLA

I just signed the Adobe CLA

2022-07-29 13:58 UTC, keharper commented
@kavingas This appears to be a duplicate of https://github.com/magento-commerce/devdocs/pull/3064. We'll reopen it if I'm wrong.

2022-07-29 13:58 UTC, closed without merging