Update link to AWS OpenSearch documentation
magento/devdocs pull request #9492
Opened 2022-08-04 11:45 UTC by jlnarvaez

## Purpose of this pull request

This pull request (PR) is for add link to AWS OpenSearch documentation.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-aws.html

2022-08-04 15:25 UTC, hguthrie requested changes
Thanks for trying to fix this broken link!
The link you added is not the correct one, though.

2022-08-08 06:47 UTC, jlnarvaez commented
> Thanks for trying to fix this broken link! The link you added is not the correct one, though.

Sorry, I don't know why this link is pasted. Now I think that link is the correct.

2022-08-08 14:00 UTC, hguthrie approved these changes
That works!

2022-08-08 14:43 UTC, hguthrie commented
@magento import code to magento-devdocs/devdocs

2022-08-08 14:44 UTC, m2-github-services commented
@hguthrie the branch with the code is successfully imported into the `magento-devdocs/devdocs` repository. Branch name: `imported-jlnarvaez-devdocs-9492`.

2022-08-09 19:42 UTC, merged